{{- if .Values.broker.ingress.v1.enabled -}}
{{- $ingressPath := .Values.broker.ingress.v1.path -}}
{{- $serviceName := include "pinot.broker.fullname" . -}}
{{- $servicePort := .Values.broker.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
{{- if .Values.broker.ingress.v1.annotations }}
  annotations:
{{ toYaml .Values.broker.ingress.v1.annotations | indent 4 }}
{{- end }}
  labels:
{{- include "pinot.brokerLabels" . | nindent 4 }}
spec:
{{- if .Values.broker.ingress.v1.ingressClassName }}
  ingressClassName: {{ .Values.broker.ingress.v1.ingressClassName }}
{{- end }}
{{- if .Values.broker.ingress.v1.tls }}
  tls:
{{ toYaml .Values.broker.ingress.v1.tls | indent 4 }}
{{- end }}
  rules:
    {{- range .Values.broker.ingress.v1.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
    {{- end }}
{{- end }}
