/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.segment.spi.index.metadata;

import com.google.common.collect.Maps;
import it.unimi.dsi.fastutil.ints.IntSet;
import it.unimi.dsi.fastutil.longs.LongArrayList;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import javax.annotation.Nullable;
import org.apache.commons.configuration2.Configuration;
import org.apache.commons.configuration2.PropertiesConfiguration;
import org.apache.pinot.segment.spi.ColumnMetadata;
import org.apache.pinot.segment.spi.V1Constants.MetadataKeys.Column;
import org.apache.pinot.segment.spi.V1Constants.MetadataKeys.Segment;
import org.apache.pinot.segment.spi.index.IndexService;
import org.apache.pinot.segment.spi.index.IndexType;
import org.apache.pinot.segment.spi.partition.PartitionFunction;
import org.apache.pinot.segment.spi.partition.PartitionFunctionFactory;
import org.apache.pinot.segment.spi.partition.metadata.ColumnPartitionMetadata;
import org.apache.pinot.spi.config.table.FieldConfig.EncodingType;
import org.apache.pinot.spi.data.ComplexFieldSpec;
import org.apache.pinot.spi.data.DateTimeFieldSpec;
import org.apache.pinot.spi.data.DimensionFieldSpec;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.FieldSpec.DataType;
import org.apache.pinot.spi.data.FieldSpec.FieldType;
import org.apache.pinot.spi.data.MetricFieldSpec;
import org.apache.pinot.spi.data.TimeFieldSpec;
import org.apache.pinot.spi.data.TimeGranularitySpec;
import org.apache.pinot.spi.env.CommonsConfigurationUtils;
import org.apache.pinot.spi.utils.BytesUtils;


@SuppressWarnings({"rawtypes", "unchecked"})
public class ColumnMetadataImpl implements ColumnMetadata {
  private static final long SIZE_MASK = 0xffffffffffffL;

  private final FieldSpec _fieldSpec;
  private final int _totalDocs;
  private final int _cardinality;
  private final boolean _hasDictionary;
  private final EncodingType _forwardIndexEncoding;
  private final boolean _sorted;
  private final Comparable _minValue;
  private final Comparable _maxValue;
  private final boolean _minMaxValueInvalid;
  private final int _lengthOfShortestElement;
  private final int _lengthOfLongestElement;
  private final boolean _isAscii;
  private final int _totalNumberOfEntries;
  private final int _maxNumberOfMultiValues;
  private final int _maxRowLengthInBytes;
  private final int _bitsPerElement;
  private final PartitionFunction _partitionFunction;
  private final Set<Integer> _partitions;
  private final boolean _autoGenerated;

  /// List of longs, each encodes:
  /// - 2 byte - numeric id of IndexType
  /// - 6 byte - index size
  ///
  /// Use non-default size to save space for most columns
  private final LongArrayList _indexTypeSizeList = new LongArrayList(2);

  private ColumnMetadataImpl(FieldSpec fieldSpec, int totalDocs, int cardinality, boolean hasDictionary,
      EncodingType forwardIndexEncoding, boolean sorted, @Nullable Comparable minValue, @Nullable Comparable maxValue,
      boolean minMaxValueInvalid, int lengthOfShortestElement, int lengthOfLongestElement, boolean isAscii,
      int totalNumberOfEntries, int maxNumberOfMultiValues, int maxRowLengthInBytes, int bitsPerElement,
      @Nullable PartitionFunction partitionFunction, @Nullable Set<Integer> partitions, boolean autoGenerated) {
    _fieldSpec = fieldSpec;
    _totalDocs = totalDocs;
    _cardinality = cardinality;
    _hasDictionary = hasDictionary;
    _forwardIndexEncoding = forwardIndexEncoding;
    _sorted = sorted;
    _minValue = minValue;
    _maxValue = maxValue;
    _minMaxValueInvalid = minMaxValueInvalid;
    _lengthOfShortestElement = lengthOfShortestElement;
    _lengthOfLongestElement = lengthOfLongestElement;
    _isAscii = isAscii;
    _bitsPerElement = bitsPerElement;
    _maxNumberOfMultiValues = maxNumberOfMultiValues;
    _maxRowLengthInBytes = maxRowLengthInBytes;
    _totalNumberOfEntries = totalNumberOfEntries;
    _partitionFunction = partitionFunction;
    _partitions = partitions;
    _autoGenerated = autoGenerated;
  }

  @Override
  public FieldSpec getFieldSpec() {
    return _fieldSpec;
  }

  @Override
  public int getTotalDocs() {
    return _totalDocs;
  }

  @Override
  public int getCardinality() {
    return _cardinality;
  }

  @Override
  public boolean hasDictionary() {
    return _hasDictionary;
  }

  @Override
  public EncodingType getForwardIndexEncoding() {
    return _forwardIndexEncoding;
  }

  @Override
  public boolean isSorted() {
    return _sorted;
  }

  @Nullable
  @Override
  public Comparable<?> getMinValue() {
    return _minValue;
  }

  @Nullable
  @Override
  public Comparable<?> getMaxValue() {
    return _maxValue;
  }

  @Override
  public boolean isMinMaxValueInvalid() {
    return _minMaxValueInvalid;
  }

  @Override
  public int getLengthOfShortestElement() {
    return _lengthOfShortestElement;
  }

  @Override
  public int getLengthOfLongestElement() {
    return _lengthOfLongestElement;
  }

  @Override
  public boolean isAscii() {
    return _isAscii;
  }

  @Override
  public int getBitsPerElement() {
    return _bitsPerElement;
  }

  @Override
  public int getMaxNumberOfMultiValues() {
    return _maxNumberOfMultiValues;
  }

  @Override
  public int getTotalNumberOfEntries() {
    return _totalNumberOfEntries;
  }

  @Override
  public int getMaxRowLengthInBytes() {
    return _maxRowLengthInBytes;
  }

  @Nullable
  @Override
  public PartitionFunction getPartitionFunction() {
    return _partitionFunction;
  }

  @Nullable
  @Override
  public Set<Integer> getPartitions() {
    return _partitions;
  }

  @Override
  public boolean isAutoGenerated() {
    return _autoGenerated;
  }

  @Override
  public long getIndexSizeFor(IndexType type) {
    short indexId = IndexService.getInstance().getNumericId(type);
    for (long typeAndSize : _indexTypeSizeList) {
      if (indexId == unpackIndexType(typeAndSize)) {
        return unpackIndexSize(typeAndSize);
      }
    }
    return UNAVAILABLE;
  }

  // size should be non-negative 48-bit value
  public void addIndexSize(short indexType, long size) {
    if (size < 0 || size > SIZE_MASK) {
      throw new IllegalArgumentException(
          "Index size should be a non-negative integer value between 0 and " + SIZE_MASK);
    }
    long typeAndSize = ((long) indexType) << 48 | (size & SIZE_MASK);
    _indexTypeSizeList.add(typeAndSize);
  }

  @Override
  public int getNumIndexes() {
    return _indexTypeSizeList.size();
  }

  @Override
  public short getIndexType(int position) {
    return unpackIndexType(_indexTypeSizeList.getLong(position));
  }

  private static short unpackIndexType(long typeAndSize) {
    return (short) ((typeAndSize >>> 48));
  }

  @Override
  public long getIndexSize(int position) {
    return unpackIndexSize(_indexTypeSizeList.getLong(position));
  }

  private static long unpackIndexSize(long typeAndSize) {
    return typeAndSize & SIZE_MASK;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColumnMetadataImpl that = (ColumnMetadataImpl) o;
    return _totalDocs == that._totalDocs
        && _cardinality == that._cardinality
        && _hasDictionary == that._hasDictionary
        && _forwardIndexEncoding == that._forwardIndexEncoding
        && _sorted == that._sorted
        && _minMaxValueInvalid == that._minMaxValueInvalid
        && _lengthOfShortestElement == that._lengthOfShortestElement
        && _lengthOfLongestElement == that._lengthOfLongestElement
        && _isAscii == that._isAscii
        && _totalNumberOfEntries == that._totalNumberOfEntries
        && _maxNumberOfMultiValues == that._maxNumberOfMultiValues
        && _maxRowLengthInBytes == that._maxRowLengthInBytes
        && _bitsPerElement == that._bitsPerElement
        && _autoGenerated == that._autoGenerated
        && Objects.equals(_fieldSpec, that._fieldSpec)
        && Objects.equals(_minValue, that._minValue)
        && Objects.equals(_maxValue, that._maxValue)
        && Objects.equals(_partitionFunction, that._partitionFunction)
        && Objects.equals(_partitions, that._partitions)
        && Objects.equals(_indexTypeSizeList, that._indexTypeSizeList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_fieldSpec, _totalDocs, _cardinality, _hasDictionary, _forwardIndexEncoding, _sorted,
        _minValue, _maxValue, _minMaxValueInvalid, _lengthOfShortestElement, _lengthOfLongestElement, _isAscii,
        _totalNumberOfEntries, _maxNumberOfMultiValues, _maxRowLengthInBytes, _bitsPerElement, _partitionFunction,
        _partitions, _autoGenerated, _indexTypeSizeList);
  }

  @Override
  public String toString() {
    return "ColumnMetadataImpl{"
        + "_fieldSpec=" + _fieldSpec
        + ", _totalDocs=" + _totalDocs
        + ", _cardinality=" + _cardinality
        + ", _hasDictionary=" + _hasDictionary
        + ", _forwardIndexEncoding=" + _forwardIndexEncoding
        + ", _sorted=" + _sorted
        + ", _minValue=" + _minValue
        + ", _maxValue=" + _maxValue
        + ", _minMaxValueInvalid=" + _minMaxValueInvalid
        + ", _lengthOfShortestElement=" + _lengthOfShortestElement
        + ", _lengthOfLongestElement=" + _lengthOfLongestElement
        + ", _isAscii=" + _isAscii
        + ", _totalNumberOfEntries=" + _totalNumberOfEntries
        + ", _maxNumberOfMultiValues=" + _maxNumberOfMultiValues
        + ", _maxRowLengthInBytes=" + _maxRowLengthInBytes
        + ", _bitsPerElement=" + _bitsPerElement
        + ", _partitionFunction=" + _partitionFunction
        + ", _partitions=" + _partitions
        + ", _autoGenerated=" + _autoGenerated
        + ", _indexTypeSizeList=" + _indexTypeSizeList
        + '}';
  }

  public static ColumnMetadataImpl fromPropertiesConfiguration(PropertiesConfiguration config, int totalDocs,
      String column) {
    FieldSpec fieldSpec = extractFieldSpec(column, config);
    boolean hasDictionary = config.getBoolean(Column.getKeyFor(column, Column.HAS_DICTIONARY), true);
    // Old segments may not have FORWARD_INDEX_ENCODING — derive from HAS_DICTIONARY in that case.
    EncodingType forwardIndexEncoding = config.getEnum(Column.getKeyFor(column, Column.FORWARD_INDEX_ENCODING),
        EncodingType.class, hasDictionary ? EncodingType.DICTIONARY : EncodingType.RAW);
    Builder builder = new Builder()
        .setFieldSpec(fieldSpec)
        .setTotalDocs(totalDocs)
        .setCardinality(config.getInt(Column.getKeyFor(column, Column.CARDINALITY)))
        .setHasDictionary(hasDictionary)
        .setForwardIndexEncoding(forwardIndexEncoding)
        .setSorted(config.getBoolean(Column.getKeyFor(column, Column.IS_SORTED), false))
        .setLengthOfShortestElement(
            config.getInt(Column.getKeyFor(column, Column.LENGTH_OF_SHORTEST_ELEMENT), UNAVAILABLE))
        .setLengthOfLongestElement(
            config.getInt(Column.getKeyFor(column, Column.LENGTH_OF_LONGEST_ELEMENT), UNAVAILABLE))
        .setDictionaryElementSize(config.getInt(Column.getKeyFor(column, Column.DICTIONARY_ELEMENT_SIZE), UNAVAILABLE))
        .setAscii(config.getBoolean(Column.getKeyFor(column, Column.IS_ASCII), false))
        .setTotalNumberOfEntries(config.getInt(Column.getKeyFor(column, Column.TOTAL_NUMBER_OF_ENTRIES), UNAVAILABLE))
        .setMaxNumberOfMultiValues(
            config.getInt(Column.getKeyFor(column, Column.MAX_MULTI_VALUE_ELEMENTS), UNAVAILABLE))
        .setBitsPerElement(config.getInt(Column.getKeyFor(column, Column.BITS_PER_ELEMENT), UNAVAILABLE))
        .setAutoGenerated(config.getBoolean(Column.getKeyFor(column, Column.IS_AUTO_GENERATED), false));

    // Set min/max value
    DataType storedType = fieldSpec.getDataType().getStoredType();
    if (fieldSpec instanceof ComplexFieldSpec) {
      // Complex field does not have min/max value
      builder.setMinMaxValueInvalid(true);
    } else {
      // Set min/max value if available
      // NOTE: Use getProperty() instead of getString() to avoid variable substitution ('${anotherKey}'), which can
      //       cause problem for special values such as '$${' where the first '$' is identified as escape character.
      // TODO: Use getProperty() for other properties as well to avoid the overhead of variable substitution
      String minString = (String) config.getProperty(Column.getKeyFor(column, Column.MIN_VALUE));
      String maxString = (String) config.getProperty(Column.getKeyFor(column, Column.MAX_VALUE));
      // Set min/max value if available
      if (minString != null) {
        builder.setMinValue(parseValue(storedType, column, minString));
      }
      if (maxString != null) {
        builder.setMaxValue(parseValue(storedType, column, maxString));
      }
      if (minString == null && maxString == null) {
        builder.setMinMaxValueInvalid(config.getBoolean(Column.getKeyFor(column, Column.MIN_MAX_VALUE_INVALID), false));
      }
    }

    // Set partition function
    PartitionFunction partitionFunction = extractPartitionFunction(column, config);
    if (partitionFunction != null) {
      builder.setPartitionFunction(partitionFunction);
      builder.setPartitions(extractPartitions(column, config));
    }

    return builder.build();
  }

  public static FieldSpec extractFieldSpec(String column, PropertiesConfiguration config) {
    String fieldName = config.getString(Column.getKeyFor(column, Column.COLUMN_NAME), column);
    FieldType fieldType = config.getEnum(Column.getKeyFor(column, Column.COLUMN_TYPE), FieldType.class);
    DataType dataType = config.getEnum(Column.getKeyFor(column, Column.DATA_TYPE), DataType.class);
    boolean isSingleValue = config.getBoolean(Column.getKeyFor(column, Column.IS_SINGLE_VALUED), true);
    String defaultNullValueString = config.getString(Column.getKeyFor(column, Column.DEFAULT_NULL_VALUE), null);
    if (defaultNullValueString != null && dataType.getStoredType() == DataType.STRING) {
      defaultNullValueString = CommonsConfigurationUtils.recoverSpecialCharacterInPropertyValue(defaultNullValueString);
    }
    Integer maxLength = config.getInteger(Column.getKeyFor(column, Column.SCHEMA_MAX_LENGTH), null);
    String maxLengthExceedStrategyString =
        config.getString(Column.getKeyFor(column, Column.SCHEMA_MAX_LENGTH_EXCEED_STRATEGY), null);
    FieldSpec.MaxLengthExceedStrategy maxLengthExceedStrategy = maxLengthExceedStrategyString != null
        ? FieldSpec.MaxLengthExceedStrategy.valueOf(maxLengthExceedStrategyString) : null;
    switch (fieldType) {
      case DIMENSION:
        return new DimensionFieldSpec(fieldName, dataType, isSingleValue, maxLength, defaultNullValueString,
            maxLengthExceedStrategy);
      case METRIC:
        return new MetricFieldSpec(fieldName, dataType, defaultNullValueString, maxLength, maxLengthExceedStrategy);
      case TIME:
        TimeUnit timeUnit = TimeUnit.valueOf(config.getString(Segment.TIME_UNIT, "DAYS").toUpperCase());
        return new TimeFieldSpec(new TimeGranularitySpec(dataType, timeUnit, fieldName));
      case DATE_TIME:
        String format = config.getString(Column.getKeyFor(column, Column.DATETIME_FORMAT));
        String granularity = config.getString(Column.getKeyFor(column, Column.DATETIME_GRANULARITY));
        return new DateTimeFieldSpec(fieldName, dataType, format, granularity, defaultNullValueString, null);
      case COMPLEX:
        List<String> childFieldNames =
            config.getList(String.class, Column.getKeyFor(column, Column.COMPLEX_CHILD_FIELD_NAMES));
        Map<String, FieldSpec> childFieldSpecs = new HashMap<>();
        for (String childField : childFieldNames) {
          childFieldSpecs.put(childField,
              extractFieldSpec(ComplexFieldSpec.getFullChildName(column, childField), config));
        }
        return new ComplexFieldSpec(fieldName, dataType, true, childFieldSpecs);
      default:
        throw new IllegalStateException("Unsupported field type: " + fieldType);
    }
  }

  @Nullable
  public static PartitionFunction extractPartitionFunction(String column, PropertiesConfiguration config) {
    String partitionFunctionName = config.getString(Column.getKeyFor(column, Column.PARTITION_FUNCTION), null);
    if (partitionFunctionName == null) {
      return null;
    }
    int numPartitions = config.getInt(Column.getKeyFor(column, Column.NUM_PARTITIONS));
    Configuration partitionFunctionConfig = config.subset(Column.getKeyFor(column, Column.PARTITION_FUNCTION_CONFIG));
    Map<String, String> partitionFunctionConfigMap;
    if (!partitionFunctionConfig.isEmpty()) {
      partitionFunctionConfigMap = new HashMap<>();
      partitionFunctionConfig.forEach((k, v) -> {
        // NOTE:
        // A partition function config value can have comma and this value is read as a List from
        // PropertiesConfiguration.getProperty, hence we need to rebuild original comma separated string value from
        // this list of values.
        partitionFunctionConfigMap.put(k, v instanceof List ? String.join(",", (List) v) : v.toString());
      });
    } else {
      partitionFunctionConfigMap = null;
    }
    return PartitionFunctionFactory.getPartitionFunction(partitionFunctionName, numPartitions,
        partitionFunctionConfigMap);
  }

  public static IntSet extractPartitions(String column, PropertiesConfiguration config) {
    return ColumnPartitionMetadata.extractPartitions(config.getList(Column.getKeyFor(column, Column.PARTITION_VALUES)));
  }

  private static Comparable parseValue(DataType storedType, String column, String valueString) {
    switch (storedType) {
      case INT:
        return Integer.valueOf(valueString);
      case LONG:
        return Long.valueOf(valueString);
      case FLOAT:
        return Float.valueOf(valueString);
      case DOUBLE:
        return Double.valueOf(valueString);
      case BIG_DECIMAL:
        return new BigDecimal(valueString);
      case STRING:
        return CommonsConfigurationUtils.recoverSpecialCharacterInPropertyValue(valueString);
      case BYTES:
        return BytesUtils.toByteArray(valueString);
      default:
        throw new IllegalStateException("Unsupported data type: " + storedType + " for column: " + column);
    }
  }

  // NOTE: This method is only meant to retain compatibility of serialization for endpoint:
  //       `/tables/{tableName}/segments/{segmentName}/metadata`
  @SuppressWarnings("unused")
  public Map<IndexType<?, ?, ?>, Long> getIndexSizeMap() {
    IndexService service = IndexService.getInstance();
    Map<IndexType<?, ?, ?>, Long> result = Maps.newHashMapWithExpectedSize(_indexTypeSizeList.size());
    for (long typeAndSize : _indexTypeSizeList) {
      short type = unpackIndexType(typeAndSize);
      long size = unpackIndexSize(typeAndSize);
      result.put(service.get(type), size);
    }
    return result;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static class Builder {
    private FieldSpec _fieldSpec;
    private int _totalDocs;
    private int _cardinality;
    private boolean _hasDictionary;
    private EncodingType _forwardIndexEncoding;
    private boolean _sorted;
    private Comparable<?> _minValue;
    private Comparable<?> _maxValue;
    private boolean _minMaxValueInvalid;
    private int _lengthOfShortestElement;
    private int _lengthOfLongestElement;
    private int _dictionaryElementSize;
    private boolean _isAscii;
    private int _totalNumberOfEntries;
    private int _maxNumberOfMultiValues;
    private int _bitsPerElement;
    private PartitionFunction _partitionFunction;
    private Set<Integer> _partitions;
    private boolean _autoGenerated;

    public Builder setFieldSpec(FieldSpec fieldSpec) {
      _fieldSpec = fieldSpec;
      return this;
    }

    public Builder setTotalDocs(int totalDocs) {
      _totalDocs = totalDocs;
      return this;
    }

    public Builder setCardinality(int cardinality) {
      _cardinality = cardinality;
      return this;
    }

    public Builder setHasDictionary(boolean hasDictionary) {
      _hasDictionary = hasDictionary;
      return this;
    }

    public Builder setForwardIndexEncoding(EncodingType forwardIndexEncoding) {
      _forwardIndexEncoding = forwardIndexEncoding;
      return this;
    }

    public Builder setSorted(boolean sorted) {
      _sorted = sorted;
      return this;
    }

    public Builder setMinValue(Comparable<?> minValue) {
      _minValue = minValue;
      return this;
    }

    public Builder setMaxValue(Comparable<?> maxValue) {
      _maxValue = maxValue;
      return this;
    }

    public Builder setMinMaxValueInvalid(boolean minMaxValueInvalid) {
      _minMaxValueInvalid = minMaxValueInvalid;
      return this;
    }

    public Builder setLengthOfShortestElement(int lengthOfShortestElement) {
      _lengthOfShortestElement = lengthOfShortestElement;
      return this;
    }

    public Builder setLengthOfLongestElement(int lengthOfLongestElement) {
      _lengthOfLongestElement = lengthOfLongestElement;
      return this;
    }

    public Builder setDictionaryElementSize(int dictionaryElementSize) {
      _dictionaryElementSize = dictionaryElementSize;
      return this;
    }

    public Builder setAscii(boolean isAscii) {
      _isAscii = isAscii;
      return this;
    }

    public Builder setTotalNumberOfEntries(int totalNumberOfEntries) {
      _totalNumberOfEntries = totalNumberOfEntries;
      return this;
    }

    public Builder setMaxNumberOfMultiValues(int maxNumberOfMultiValues) {
      _maxNumberOfMultiValues = maxNumberOfMultiValues;
      return this;
    }

    public Builder setBitsPerElement(int bitsPerElement) {
      _bitsPerElement = bitsPerElement;
      return this;
    }

    public Builder setPartitionFunction(PartitionFunction partitionFunction) {
      _partitionFunction = partitionFunction;
      return this;
    }

    public Builder setPartitions(Set<Integer> partitions) {
      _partitions = partitions;
      return this;
    }

    public Builder setAutoGenerated(boolean autoGenerated) {
      _autoGenerated = autoGenerated;
      return this;
    }

    public ColumnMetadataImpl build() {
      // Canonicalize length of shortest/longest element
      DataType storedType = _fieldSpec.getDataType().getStoredType();
      if (storedType.isFixedWidth()) {
        int size = storedType.size();
        _lengthOfShortestElement = size;
        _lengthOfLongestElement = size;
      } else {
        // Pre-1.6.0 segments don't write LENGTH_OF_LONGEST_ELEMENT; fall back to DICTIONARY_ELEMENT_SIZE,
        // which has been written for dictionary-encoded columns since well before 1.6.0 (including the
        // zero-length case where every entry is an empty string). Leaving the field at the UNAVAILABLE
        // sentinel would propagate as `numBytesPerValue = -1` into BaseImmutableDictionary.getBuffer().
        if (_lengthOfLongestElement < 0 && _hasDictionary) {
          _lengthOfLongestElement = _dictionaryElementSize;
        }
      }

      // Canonicalize MV related fields
      int maxRowLengthInBytes;
      if (_fieldSpec.isSingleValueField()) {
        _totalNumberOfEntries = _totalDocs;
        _maxNumberOfMultiValues = 0;
        maxRowLengthInBytes = _lengthOfLongestElement;
      } else {
        if (_lengthOfShortestElement >= 0 && _lengthOfShortestElement == _lengthOfLongestElement) {
          maxRowLengthInBytes = _maxNumberOfMultiValues * _lengthOfLongestElement;
        } else {
          maxRowLengthInBytes = UNAVAILABLE;
        }
      }

      // Canonicalize bits per element
      if (!_hasDictionary) {
        _bitsPerElement = UNAVAILABLE;
      }

      if (_forwardIndexEncoding == null) {
        _forwardIndexEncoding = _hasDictionary ? EncodingType.DICTIONARY : EncodingType.RAW;
      }

      return new ColumnMetadataImpl(_fieldSpec, _totalDocs, _cardinality, _hasDictionary, _forwardIndexEncoding,
          _sorted, _minValue, _maxValue, _minMaxValueInvalid, _lengthOfShortestElement, _lengthOfLongestElement,
          _isAscii, _totalNumberOfEntries, _maxNumberOfMultiValues, maxRowLengthInBytes, _bitsPerElement,
          _partitionFunction, _partitions, _autoGenerated);
    }
  }
}
