/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.plugin.minion.tasks.refreshsegment;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.apache.commons.configuration2.PropertiesConfiguration;
import org.apache.commons.io.FileUtils;
import org.apache.helix.AccessOption;
import org.apache.helix.store.zk.ZkHelixPropertyStore;
import org.apache.helix.zookeeper.datamodel.ZNRecord;
import org.apache.pinot.common.metrics.MinionMetrics;
import org.apache.pinot.common.utils.config.SchemaSerDeUtils;
import org.apache.pinot.common.utils.config.TableConfigSerDeUtils;
import org.apache.pinot.core.common.MinionConstants;
import org.apache.pinot.core.minion.PinotTaskConfig;
import org.apache.pinot.minion.MinionContext;
import org.apache.pinot.plugin.minion.tasks.MinionTaskTestUtils;
import org.apache.pinot.plugin.minion.tasks.SegmentConversionResult;
import org.apache.pinot.segment.local.segment.creator.impl.SegmentIndexCreationDriverImpl;
import org.apache.pinot.segment.local.segment.index.loader.IndexLoadingConfig;
import org.apache.pinot.segment.local.segment.index.loader.defaultcolumn.DefaultColumnHandlerFactory;
import org.apache.pinot.segment.local.segment.readers.GenericRowRecordReader;
import org.apache.pinot.segment.local.segment.store.SegmentLocalFSDirectory;
import org.apache.pinot.segment.spi.ColumnMetadata;
import org.apache.pinot.segment.spi.V1Constants;
import org.apache.pinot.segment.spi.creator.SegmentGeneratorConfig;
import org.apache.pinot.segment.spi.index.metadata.SegmentMetadataImpl;
import org.apache.pinot.segment.spi.store.SegmentDirectory;
import org.apache.pinot.segment.spi.utils.SegmentMetadataUtils;
import org.apache.pinot.spi.config.instance.InstanceType;
import org.apache.pinot.spi.config.table.TableConfig;
import org.apache.pinot.spi.config.table.TableType;
import org.apache.pinot.spi.config.table.ingestion.IngestionConfig;
import org.apache.pinot.spi.config.table.ingestion.TransformConfig;
import org.apache.pinot.spi.data.DimensionFieldSpec;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.Schema;
import org.apache.pinot.spi.data.readers.GenericRow;
import org.apache.pinot.spi.utils.ReadMode;
import org.apache.pinot.spi.utils.builder.TableConfigBuilder;
import org.apache.pinot.spi.utils.builder.TableNameBuilder;
import org.mockito.Mockito;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotEquals;
import static org.testng.Assert.assertNull;
import static org.testng.Assert.assertTrue;


/// RefreshSegment must not record-replay rebuild for transform BACKFILL/UPDATE. That path stamps
/// `autoGenerated=false` and freezes the column. Server preprocess is the apply path.
public class RefreshSegmentTaskExecutorTest {
  private static final File TEMP_DIR =
      new File(FileUtils.getTempDirectory(), RefreshSegmentTaskExecutorTest.class.getSimpleName());
  private static final String TABLE_NAME = "refreshDerivedTable";
  private static final String TABLE_NAME_WITH_TYPE = TableNameBuilder.OFFLINE.tableNameWithType(TABLE_NAME);
  private static final String SEGMENT_NAME = "testSegment";
  private static final String SRC = "src";
  private static final String DERIVED = "derived";
  private static final String NEW_COL = "newCol";
  private static final String ORIGINAL_TRANSFORM = "plus(src, 1)";
  private static final String UPDATED_TRANSFORM = "plus(src, 2)";

  @BeforeClass
  public void setUp()
      throws Exception {
    FileUtils.deleteDirectory(TEMP_DIR);
    MinionMetrics.register(Mockito.mock(MinionMetrics.class));
  }

  @AfterClass
  public void tearDown()
      throws Exception {
    FileUtils.deleteDirectory(TEMP_DIR);
  }

  @Test
  public void testRefreshSegmentDoesNotFreezeBackfilledDerivedColumn()
      throws Exception {
    File indexDir = buildSegmentWithAutoGeneratedDerived("backfillFreeze", ORIGINAL_TRANSFORM);
    removeTransformFunctionFromMetadata(indexDir, DERIVED);
    assertTrue(new SegmentMetadataImpl(indexDir).getColumnMetadataFor(DERIVED).isAutoGenerated());

    stubTableAndSchema(tableConfig(ORIGINAL_TRANSFORM), schemaWithDerived());
    SegmentConversionResult result = convert(indexDir, new File(TEMP_DIR, "backfillWorking"));

    assertEquals(result.getFile(), indexDir);
    ColumnMetadata derived = new SegmentMetadataImpl(indexDir).getColumnMetadataFor(DERIVED);
    assertTrue(derived.isAutoGenerated());
    assertNull(derived.getTransformFunction());
    assertNull(derived.getTransformFunctionBackfilled());
  }

  @Test
  public void testRefreshSegmentDoesNotRebuildOnTransformUpdate()
      throws Exception {
    File indexDir = buildSegmentWithAutoGeneratedDerived("updateFreeze", ORIGINAL_TRANSFORM);
    ColumnMetadata before = new SegmentMetadataImpl(indexDir).getColumnMetadataFor(DERIVED);
    assertEquals(before.getTransformFunction(), ORIGINAL_TRANSFORM);
    assertEquals(before.getMinValue(), 11);

    stubTableAndSchema(tableConfig(UPDATED_TRANSFORM), schemaWithDerived());
    SegmentConversionResult result = convert(indexDir, new File(TEMP_DIR, "updateWorking"));

    assertEquals(result.getFile(), indexDir);
    ColumnMetadata after = new SegmentMetadataImpl(indexDir).getColumnMetadataFor(DERIVED);
    assertTrue(after.isAutoGenerated());
    assertEquals(after.getTransformFunction(), ORIGINAL_TRANSFORM);
    assertEquals(after.getMinValue(), 11);
  }

  @Test
  public void testRefreshSegmentStillRebuildsWhenAddingColumn()
      throws Exception {
    File indexDir = buildSegmentWithAutoGeneratedDerived("addColumn", ORIGINAL_TRANSFORM);
    Schema schema = schemaWithDerived();
    schema.addField(new DimensionFieldSpec(NEW_COL, FieldSpec.DataType.STRING, true));
    stubTableAndSchema(tableConfig(ORIGINAL_TRANSFORM), schema);

    File workingDir = new File(TEMP_DIR, "addColumnWorking");
    SegmentConversionResult result = convert(indexDir, workingDir);

    assertNotEquals(result.getFile(), indexDir);
    assertTrue(result.getFile().isDirectory());
    assertTrue(new SegmentMetadataImpl(result.getFile()).getAllColumns().contains(NEW_COL));
  }

  private static SegmentConversionResult convert(File indexDir, File workingDir)
      throws Exception {
    FileUtils.forceMkdir(workingDir);
    RefreshSegmentTaskExecutor executor = new RefreshSegmentTaskExecutor();
    executor.setMinionEventObserver(MinionTaskTestUtils.getMinionProgressObserver());
    PinotTaskConfig taskConfig = new PinotTaskConfig(MinionConstants.RefreshSegmentTask.TASK_TYPE,
        Map.of(MinionConstants.TABLE_NAME_KEY, TABLE_NAME_WITH_TYPE, MinionConstants.SEGMENT_NAME_KEY, SEGMENT_NAME));
    return executor.convert(taskConfig, indexDir, workingDir);
  }

  @SuppressWarnings("unchecked")
  private static void stubTableAndSchema(TableConfig tableConfig, Schema schema)
      throws Exception {
    ZkHelixPropertyStore<ZNRecord> helixPropertyStore = Mockito.mock(ZkHelixPropertyStore.class);
    Mockito.when(helixPropertyStore.get("/CONFIGS/TABLE/" + TABLE_NAME_WITH_TYPE, null, AccessOption.PERSISTENT))
        .thenReturn(TableConfigSerDeUtils.toZNRecord(tableConfig));
    Mockito.when(helixPropertyStore.get("/SCHEMAS/" + TABLE_NAME, null, AccessOption.PERSISTENT))
        .thenReturn(SchemaSerDeUtils.toZNRecord(schema));
    MinionContext.getInstance().setHelixPropertyStore(helixPropertyStore);
  }

  private static File buildSegmentWithAutoGeneratedDerived(String dirName, String transformFunction)
      throws Exception {
    File outDir = new File(TEMP_DIR, dirName);
    FileUtils.deleteQuietly(outDir);
    Schema baseSchema = new Schema.SchemaBuilder().setSchemaName(TABLE_NAME)
        .addMetric(SRC, FieldSpec.DataType.INT)
        .build();
    TableConfig baseTableConfig = new TableConfigBuilder(TableType.OFFLINE).setTableName(TABLE_NAME).build();
    List<GenericRow> rows = new ArrayList<>();
    GenericRow row = new GenericRow();
    row.putValue(SRC, 10);
    rows.add(row);
    GenericRow row2 = new GenericRow();
    row2.putValue(SRC, 20);
    rows.add(row2);
    SegmentGeneratorConfig config = new SegmentGeneratorConfig(baseTableConfig, baseSchema);
    config.setInstanceType(InstanceType.MINION);
    config.setOutDir(outDir.getPath());
    config.setSegmentName(SEGMENT_NAME);
    SegmentIndexCreationDriverImpl driver = new SegmentIndexCreationDriverImpl();
    driver.init(config, new GenericRowRecordReader(rows));
    driver.build();
    File indexDir = new File(outDir, SEGMENT_NAME);
    try (SegmentDirectory segmentDirectory = new SegmentLocalFSDirectory(indexDir, ReadMode.mmap);
        SegmentDirectory.Writer writer = segmentDirectory.createWriter()) {
      DefaultColumnHandlerFactory.getDefaultColumnHandler(indexDir, segmentDirectory.getSegmentMetadata(),
          new IndexLoadingConfig(tableConfig(transformFunction), schemaWithDerived()), writer).updateDefaultColumns();
    }
    assertTrue(new SegmentMetadataImpl(indexDir).getColumnMetadataFor(DERIVED).isAutoGenerated());
    return indexDir;
  }

  private static Schema schemaWithDerived() {
    return new Schema.SchemaBuilder().setSchemaName(TABLE_NAME)
        .addMetric(SRC, FieldSpec.DataType.INT)
        .addMetric(DERIVED, FieldSpec.DataType.INT)
        .build();
  }

  private static TableConfig tableConfig(String transformFunction) {
    IngestionConfig ingestionConfig = new IngestionConfig();
    ingestionConfig.setTransformConfigs(List.of(new TransformConfig(DERIVED, transformFunction)));
    return new TableConfigBuilder(TableType.OFFLINE).setTableName(TABLE_NAME).setIngestionConfig(ingestionConfig)
        .build();
  }

  private static void removeTransformFunctionFromMetadata(File indexDir, String column)
      throws Exception {
    PropertiesConfiguration segmentProperties = SegmentMetadataUtils.getPropertiesConfiguration(indexDir);
    segmentProperties.clearProperty(
        V1Constants.MetadataKeys.Column.getKeyFor(column, V1Constants.MetadataKeys.Column.TRANSFORM_FUNCTION));
    segmentProperties.clearProperty(V1Constants.MetadataKeys.Column.getKeyFor(column,
        V1Constants.MetadataKeys.Column.TRANSFORM_FUNCTION_BACKFILLED));
    SegmentMetadataUtils.savePropertiesConfiguration(segmentProperties, indexDir);
  }
}
