/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.core.common;

import java.nio.ByteBuffer;
import java.util.Base64;
import org.apache.datasketches.cpc.CpcSketch;
import org.apache.datasketches.frequencies.FrequentItemsSketch;
import org.apache.datasketches.frequencies.FrequentLongsSketch;
import org.apache.datasketches.kll.KllDoublesSketch;
import org.apache.datasketches.tuple.TupleSketch;
import org.apache.datasketches.tuple.aninteger.IntegerSummary;
import org.apache.pinot.segment.local.utils.CustomSerDeUtils;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;


/// Regression test for cross-version serial compatibility of DataSketches objects.
///
/// The Base64 fixtures below were generated with datasketches-java 6.2.0 (the version shipped before the 9.x
/// upgrade) and represent the bytes that exist today in BYTES columns, star-tree aggregated values and
/// intermediate query results of deployed clusters. Each test asserts that the current datasketches-java version
/// still deserializes them correctly through the same [ObjectSerDe] instances used on the query path. Do NOT
/// regenerate these fixtures with a newer datasketches version - that would defeat the purpose of the test.
///
/// Fixture recipe (datasketches-java 6.2.0): 1000 distinct integer keys (0..999) per sketch;
/// frequency sketches received keys `i % 10` / `"s" + (i % 10)`, i.e. 100 occurrences per item.
public class DataSketchesSerialCompatTest {
  private static final String THETA_ORDERED_620 =
      "AgMDAAAazJPoAwAAAACAP9WJ7fK6dCoA3qxr4eHZZQD6dLNMFrFuAMfEgYUTf3MA/z7bSTH6lgBRZwE+7+LdAEu/fu5+QPUA5MdYEprEBgGvXx"
      + "WmSZJOAQoi27cch18BiGVXN9EKdAF7f+xm7Xh/Afs4eYkTJI8Bub+f6vqeqgF4PUbjfXzTAe+vrs9b3fQBlN7WyKB1KgLR7rWxGbSTAm3z+4hV"
      + "jZYCc0eibjlNmQKumtEZpHAnA6WQe+U0+W0DuDO1GsNucgMPXRGQ3IixAzk+6xYTzrMD5mI4bj1/0wM4XaDwZjvVA3NiaN5La/wDSWK7kGK2/A"
      + "Pop71o/guGBJ1D/+JVgaAE4trPn83qvgRFpUczrKzdBO0LTW1SugYF/I4BX1yQKgVTe4ImtqZDBY6nDkifGFgFCsR19Lb1ZAVS7BlJHS1oBYkC"
      + "PEtPTGkFKZIHncBZbwUV+X3LvYahBSWWeWyGPrIF98550oN/yQUWUnbRYWjiBWqpyt4kCu0FofaJYj2PBAb7irflPvt7BtL6/VNWDrUG20AN7O"
      + "dQzQZdvZ9541UyB67L0A3zAFYHxqPHz0/0jgeYe3jOVSmtBzwvexgKD7sHt85zc3q/2Af5pTFJsvfhB2MxmlcrLeYHjpWNEGFd8Acfco3xbYEO"
      + "CAtZYHNAkzAIQN4u4cnbPQiSo7xw/Jc/CNqGewlfR0UIaYu5kbhoVwjcP59UDJlaCKkPeAxQUHcI9azX1bj9ewj6aflZPKKDCKD9BmF25Y4I5g"
      + "vHbkmvpQgc9dXFcQbECPOF0Rdl9sUIvhEek4VG/giQ4d0UI8smCUNs8OgU4DcJGKUmy7vFXQmowdotX/qHCZsmPsrMW5cJb4+pYQUerQmjW5QX"
      + "zU6uCaG6RKGKXOIJtGWaAgpH9AkoIIQlgHxRCgUDwCUQecIKsh6LHEUlSAthTs01Qn9vCyAZ3mW8Y54LJr+FKnSHwAtNETqMK8/yC9afhNy05h"
      + "UMO/Rz/J53JQyyb0VgFxA2DM3dMbQZioAMcheLPeVuiwyAoBdQMjm0DKwoeQfM1s8M/cbFSAae0QzkkNLibxfWDClzdbhQdeEMg7kyzPlbfw2v"
      + "CIHtp9OhDcoh6wMdmb0Ni4I9PgVtzg1//pnso1sZDrgh5FDua2YOsmILovQE1Q5qkYsLC+csD61nsbOVWF8PlOXnMZ2LYA+NeNmPYKaCD1uT+U"
      + "gl2ocPQ1tVNu7wmw9ysJ9FRMecDyT6oqAzR6IPD/dgftE9wQ+htuPRggTcD42ivBhKh+8P+XfHDAk6ChButddTTU0NEMQTUCbcFRcQkImrOXHA"
      + "GBA7J2vj1fwtEP4WIRP7mLwQ1yHhBW4Z1hCaWlVHG+7kELx6uhb5O/kQWr90ON8mERFvK7zg+WtdEeiv/P3Yb5URAHhHNuAfnxFeRAcXahOiEY"
      + "NFfaKZ6a4RkZ31XPZvuhFsRRrZVkDAEalB7ZfhP9URCm0UCRZm1RF2xpAbu5ADEgRkxiW4NQkSa8bONx2CERKg/nAl1BI3EveHBSgW60kSOq80"
      + "JUB8gRLPVVB60gaTEhlki4wn2JQSIzyZ51PjvxIunwwS0BblEl9nG9hORA8T8yh3Xow4HxNFLnTwuj2PE6ZTbV6AZqkT+ZqeZAHysBM/XDSKh6"
      + "LHE9UKUugeKMoTTUWpPUIu9hMnT2g3yAUJFMsxC4dlBgoU53Ak5KbbFxS3/6nmHBcbFLUKIyFOnykUkJv3cVxkLRTXxOhkyD1UFAOtk/BdoXEU"
      + "vTJzckaRzBTd/BiVlFndFF4QKeEI5t8UrPUwSzu79RToAvoztij4FJKXgjbltPoUT0brs+vVIBUbTNFJlZhSFTBAtV3Ww2YV6ex3T6iAfhXOJ5"
      + "i4Ws9/FcoDYarnM58VE+nHY7M+nxVDXrfaZJezFWatbFgPltAVjO2EWqFu7BX61riVr+r4FcpwHyrrjiEWcXxrntjZZxbhuOfIN0CjFt9mfzCC"
      + "gqkWq/iLKMymqRZTUj9v2ImrFtFeoEKNnOsWCxcQ+TJ2ABePjGGL0NMRFwP65QUNbTIXlbO1CggRPBdQhFhOeizQF60ExIWycdEXdZk2tVcy6B"
      + "cO7PR2JzoOGGafQy1udYoYUD1Coya1qxi7EayzlbvCGPMaSqnZaN4Yn+ztiGyA/Bh526OgaHA/GZWci/6z1IoZ4ljTRiePtRnJIN6oJn6+GVlU"
      + "XH2VZNYZzCQhCqlc3RnWfd5ZaxHhGY9mvalLU+wZKtvQXYFv+RnZYQ82iDQnGligfvAgpUMas8FBsXZNehpu+20XlTisGuScec0cU84aSeUjzE"
      + "C72BqsW+JmH57ZGrenx3ITWdsavbctHIN3VRsNkVTKht+AG6YM04BTkpMbo1AJ1GLPwxtwQqOPE6fGG5ujhBEG3ckbP16bJGSm1huOptONUTTl"
      + "G/l5qTyRifYbUjWcO3Es/Bt84iRSDh1MHLlg7c31zF0cVZ+xc1+udBxP8k3gvAyuHCcpvfRIDtUcYfm1Dgrg5RwFCie+dYIGHfvr0BRSGQgdTu"
      + "7oUlLYCx3npLnMH3ZrHW+xaen9hnIdeTwuTqHVix1wVtdQdUCfHQkCvUGwWKQdEIYEJOXtwB3qITeGIdk+HmgH9b05cVkebakWvEpmYR6qPAKn"
      + "d/tkHsWQrmZW9XseaS4kUMz7lB7Dl/wSgXCdHioDFntvuLYeS6RB0D6x6h6Kq4i29x0JH1GyvHambw0fAUc5g+GYUx/lAXZhZZdZH9ogcq9w7W"
      + "YfuGJ6Xm3AZx8qGIvOQTtxHyOlWzga/XQfBhNdn2kpiR+F1iC77N/BHwJeoci3h8kfuke1VGTg/h9mx6sYkegpIJr7KY1majggZUavqhOkQSDl"
      + "a2HuyIBEIKvoupWxdEggAW4pMD2oaiBVcQ0ikReoID663KNvb7YgepozehV9/iAfSCTacPgXISQKPvxyxUAhmphx/uQ/QSF0aZQGnF9lIbbyjo"
      + "lPX3IhPG/YJMzkdiHGJNYSRf5+IY8fDSIzNZUh9FDJp1rK2SFwV1aKXPoTIjFbuxNXQhQirFCasegVHiJQ5yUMpQktIhrRMAuZjC8iitRk/Ts1"
      + "TCLAoq2UCA5aIt16ta8fH2EioMTR912wZyI1oJ1kb7LkItOIKA6TPvwixshM3og9KyPqS4qRYc5gI1D6wBNbJWkjbMx+3shZpiMaNYd8IgfoIx"
      + "ud9uE8/fAjjE+tMcIeCCTfTr/rOSE3JJb1Ho147j4kVLPec0PyTyR+Cu/6YX1VJCijcJ7ffF8k6DjBeEMYmSTPv4fCNfO5JPD1dTMn1BslIlG8"
      + "idsmHSXRzpB7mVgmJbQZMYD0ciclDCcFhh8pdiW426UaAMyJJSXrwmIuDqYl95b71QlJqiWVlFelpz64Jc4RCXwy+QkmsVwEBcZvGyaM/62Hnx"
      + "8eJhXgItfNUycmTWn11tWLKiZzlmxobBg2Jsjtqwp7iDomjNDJhkzJOiYuy+tamBGAJsqsqRfTLZsmcP+Av8uYwSYDISVUhMrYJjleZ6KA1hon"
      + "b/3c9FyuLiepXadS1oY1J7e/QnmVNkoneGVzrfuJSydOB9MYSH9vJ196fBWCYIYnF42JbY/ckifT8jEaYsOnJ/DsvyC0xK0nCKDbpGhfryfJQ5"
      + "tIB9LSJ5BUCEa4Uyooy10wLfbEPChYGWTZCw+EKOhCIaDpIcYovWX7U8sm4SjBKlFkVBnqKCPr2aJeGB0p1blD14YpNimZNt43R7I/KfD2pOEV"
      + "nX0psolb489juSnwmCwi+ZO/Ke/tjLF2O9Iplym7IcuW7inpibPEJykPKlIqyiZ1/XMqcpcqKwQlfSo5IEvBRWfFKvn+HCvEf+gqustp16fyIi"
      + "udi/lovrc2KxJorLksZkcrD8Inw9cVTCuefLnsoBp0KyvMP32+EYQrmKEvKfUslyvRtnKyfRm8K4DCsYdl2s4rpeevYnkt4CtjxfJQV18YLBi6"
      + "bxyHmx8s71Z8MD9XNiwuaIb6r2NNLDfrZzIbio4sHXD3CaFBlCy2/7KauJGmLFoAnkI4NrIsXhtllRo+uiyrAiKZ97S+LMvWYUISwsMsdvSeyE"
      + "oSyywI8K3c5voSLeBBcEzihjstgUGvejpIPS0pe7UvUVZOLWqv35lcaGgtmtQYKDOmoS0li/n/s6tALmrY4+4zPUouZ9D3YBMITC6zGCJ64fp4"
      + "LsCVLvC1NMgujKZiWOmnzS75VfilcSXULmheuQafVPEuB3A90e2WFi+sdwTsHmklL1f3YKWmUDov9lIjgTMLVy+awwugCmRjLyor2CD1YeIvOe"
      + "EWLODS/y95PEu02iZLMF4PgvG7QlkwUkY+Iw/PgjBtB243mWy0MJkSsQiFE7cwRQsEQ9NgwDCnZBNlpo/XMNZbZmz9jCYxxViylFsjKDHfjMDm"
      + "RUdLMfCYAS+9blUxTyUsBqmjVjEHRN/7yM9gMe1x6ia4hYQxyuEQukCGkjG6wMcVau2xMSAY66sUorMxQksyUC9v/zHbjOc75owOMtQoUNm08h"
      + "oy13Gh4GtyXTJgaJOK84d+MmMUN6OcOtQyPqG4wYz8AjN/cfd5DtcxM5wVfbRdSToz+9i9G1VkOjMJBTE9AeRPM+GQPauRJVozPhW8D8fmiTNI"
      + "1wVVIf6TM7zDm1up0pkzao9+4Dp6pjOWftXgVcDOM4al3+bnYNQzVqqm2zlrFDTd5IBItcImNFR9bncmOKY0e7GQCyhtxTSSdQWmSd7fNF9MzN"
      + "VvIug0wB51shtp+DThU3uOJnf4NJ296gleQRc1oYsubGdLIDWms+9EGMRLNXrtNE9uVlI1RuLEMqskVTUiDXHyJYOWNflQ/WrBxaQ1hwkFtvRB"
      + "pzUj31PXSD6wNRNBl4NTusU1G3YxWo5V/zVFMTSHfvgNNlRQ4WHpl3I2zLRfVZ9pxjbXomAmSW/QNj3hFkwV5dE2oLghJQQ94TZCIn4/fWAfN9"
      + "dobd7qjzw3eiurFapVXzehDaUC5jBqNwz/V0oJ1mo30aL9LGsVdTcBmUCoozF8NykxXTSeuYE3DAUj0xPLjTcVOJMvHdOuN2NdwnrlCJY4VVwW"
      + "97pnIDnELlms8pshOaDjWFFZQVY5Ckunw8njYTlz94MfE9uHOXa7JYfcvaY5y4koqzQa1zkD7R8Vu2D4OZ00V45JZi06QLT7eYpAQTrax0T96f"
      + "tSOlz2twbsOmM6jBgv++XzhDpXHsScr0GXOjyPiZZU+7w6gIzs6Zto3jqe2lYkR8jqOsa1RrYquhM7iMJKUMLkFzvCNObiWYQdO8b/7p64Pzc7"
      + "tqHFx6hBOTtx/mpsjsBGO8BXGaKG0GM7kNQMF+q0oTvVxvryMWXNOw8U6SPD4uI7ADhR1b+J+TvA36U5DYD7O5xFlEVQCwk8oOtrKoKwHjyX0U"
      + "W/4lsuPBajAtfuZjw8PsCxqj4lcTxrPBo3zAV2PBoXX0lgX4c84qn+6rtpoDwOw0G5NWeoPI2Bn5T5Bf48BmIkToTIBj2LM/iJ2o0HPVgZ2+S4"
      + "1hw9D5dOMJJETj1cq1RAEz15PWIjuyHvSbM9/Mb7B+KjxD30QraTrwnHPXchJfT9MRU+25cE8XrbIj7KUCfUTu4/PlAfAKaZEVk+cBINyavtWj"
      + "5HTiGtBNigPlh6mT3IV7E+32pMOKf+xD5Yz4n447zjPvWQU3wXTPk+yWWfUojJAz8AIfRd3YsXP8K8Xf/IekI/cIcvm19DUj9BHnjCrCFgP2f4"
      + "rfV42Ys/t2Wl29aNjT9QPfIy1EOmP9pYlMZjZrI/yHsJociK+T+BWF5gIGonQGbX0q7m12BAo/XzlxOLkkA0CPX4kc+7QIGECRDLOu5ArcE6ZV"
      + "C87kCC9/Gqx1FMQdd51rNf/XBBTcSb//B6tUEbU+X7i4bUQc/FtTlDANpB47D+ZsLR6EHfMvsIPswNQuJbt4LyiCRCVKyZSIwbOULbBbv+Oblb"
      + "QgEJA0qko3xCFWQQf49LtkLReU6ft2HHQlBn+cyoMeJC6aaXgHaY+EJhWBwM0oX9Ql6OijkkUQBDMQ5r/BI6E0P/GRv2XN5gQ5QSEbCAtohDRs"
      + "EO3QyCnkPpeF47IZnsQ6emXwDuxX1EebCYWepgs0RcLT2J8wS4RFiJbcGEhrlE4e4o4grYzUSEVO9y4iHjRMHHjmWp+/pEfxC5fQuLHkWfZhBC"
      + "Gc8mRf+6+ClB/3NF/enlu9v8fUU5yt5yMeV+RVSNknmTtqhFUfU2TY33ykXUlB1n/HHMRecrBHcmgiFGnpqOJbftM0ZgQDaN3aRERrqEmS6a2m"
      + "xG1gnyME7ThUbEh+Q5oxC/RgyqXuWJ8O5GorHnc716C0cSL9P0iRaMR7nwFrkO/JhHtjwv3MoZ0keagaEl/jv5R6m2F0IpjgFILbcQXk9zE0gN"
      + "Xujm1xlASBOU9X9uw0pIt2IaKY0JS0iTWdN3axB/SHk+DjkrXMxIqr2jwfsmC0lnA4i2yDMoSWQ9Em6L1ztJYgxqzQqSYknO4TLiQ3KvSR4U+E"
      + "1yjNRJaT7GWk+zDUo4Q5NSXSVISoHTWeeb9Y9KuXwEMRs6kUoE4rjHk+vkSm20D9OBch1LIAujP4N/Xkv/qW8Me85+S2mUiVB2FpNLNXTFEwtI"
      + "qEt0UsdRNtOrS6Z+ZQMsvLhLrFucjSmeMkxIIUgPILQyTBsheG9wzD1MSXbRXGekdEzUzTpi3zWbTLzvMl6Kh6xM1GBiKtOOsExboEzctJLnTE"
      + "/iUX9fW+lM/OYWNiKZQk3W4/l0Zy5nTSYDWJkL8HhNNz0wvJnlm02Rh2/kx1uuTYn83DDll9JNEO5POfMUI06XVp+Aiz9ETrkGA71JAY1Obq0A"
      + "Z75M6E7jDDUWyQruTr3Go78gl/FOZ1YkGQANSk8U/frdos9WT8QghgMWintPEdyOkl/tuE9T5q6zh/fCT1nUVw3Q7/NPFLL6R7Zr+k+Rw/+Ni4"
      + "gJUDO1luENbEhQx2FY90DES1CZcvITs05zUJiirH3HgJBQTsb6GkfbrVCwyeikgeAQUd+KqPdgBhxRNWZ/6Js3QFGk+GbIDahfUVifzq2qXotR"
      + "GH3DjdJ9zlHa78F/F1PUUeI+ZCw9zORRdVc0DlMb6VH5SiibEi4JUixiJ1jWexVSe/6PI4GOG1IHGbov/psjUr1o87Aqq2xSu9UNeSOa5FJvaN"
      + "IX9un5UjLMo/ybQypTwOD5osfFulMEAbRA5N/KUxi2gY/3XMxTDm9jF7Go8lMvQnPsdhX/U5Jn58Q/AgNUy+AsnsOpE1RAcfgWcYomVNUnWDsu"
      + "TVlUsAoUO0XEWlQbtOyqqHNiVKDtOpBQap5U/o9J+ItCrlSgEpTdH1K4VPms7Qm9GABV1J3aP2evIVUYPUjILtA7VbMfQa9benZVTCPPxId5rl"
      + "VSh541nnS9VWqVviro2ytWQ3sAzzjSMFaTwE1ivTVdVvMqN4kNdGNWqXU6yOEwe1aJxwgkAAXFVrL364NhSstWXLB85FYj11Y7Af+htkPbVm8H"
      + "2FUfaQFX7vW0tqwTDle2iBlmUBIQV120WTtBsxNXv9aVWlxVH1dZ2E/hQm48VzHDh8DqnGdXy18UNiUraFdAz8KxxqyMVxHWaEb0OplXBaRrw3"
      + "IvuVfqRUYEZq/NV++pFu6FCedXELNxZUAC9ldRIXh3d4BmWBclEIxuL95YvrK87ci441jinrROoM4HWVSndiDOGiFZfwsWGSJ0OVm5udU+Lrja"
      + "WWYhQe9OgTham+KZzk6UaVp5x4W3sT53WuHakiK+rohaeN2Va4AajVp+zZjQ3v2+WkoceR6MttVad16Y3BUEHVtU2ESgvW0eW3JIT4bFyidb02"
      + "w2ffYwQ1ukdjV9asaMW4sij8TzfZJbUUTXSxT5m1tbV3jNDAuuW0bUezw9asVbjQNh4Dmh5Vu8I7SEfvjrWzS2+1xO4P5b/bRhCXnaQlxoPYMr"
      + "KQZrXG3iqdZfxnZcZBh4lmsLiFwmpHUV9R2IXFp3Hqj73pJc2Up48jnZn1xcBi7IQHe5XEtY4Hpcv7xc8FI6P1k4zVzxyGBs/9PcXAWGRWbqNO"
      + "FcuxtirpF0Fl2zCExS8ZVIXbpAs8HaBmldSX40gs2mcF01CrUbLkp9XcgK07dUoyZeOp9AD59rSF5yKERHxNxOXtK3VRdU/dNeln94GNUS4V7C"
      + "MWyPNwP2XhvW83E+wfdeSTrUDYAENF99+2Uujxg8X20uiZ/x7UNfkm8/v8QuaF/llTtknKhoX9a13XTrsGxfE4eZYMw/bV9wgowxkSqQXyPI36"
      + "bokJxfWqbWLQZupV+VnHg7bcaqX/TjC4NQWdlfCzRUObe56F/nJd9iiEoRYDlJ4BjSUl5gPJZ3OSC6gGDLabF2q5ukYBJcMvvWUq5gp5SvAqP5"
      + "9GBflFoVj2M1YSOwqWFqcTVhg773Co/jQ2GwNt4NUb11YS+9Xb4GgIVhubT4fXfb6mE9kCVgCiX0YcyFZE48wA1iBpwtzT/QRGIrlw4eer9RYu"
      + "odhYER1mxi1N7FK/IbwmKXeZVdEmHzYmJmfhc6avZiH2wHCB3qAGPJZPqBWk80Y9DBSDJL4UxjgbzZ1TVUUWP75kFJKCqtY4Bgr3VaBfpjGNin"
      + "0wOuI2Sxi+8tOzaZZLhku1cMoLVk3AB+582U/mTdRyan41j/ZA5FPGUKkzBlwfKIeHe+NWUxcQmgc1JOZSMMb0XBgoBltNN9Ojr1gWXCmx6fXp"
      + "axZbFspFHO3+1l7wvSqxnZ/2UAeyO6qOJ9ZjBjxw+Prdpmhq+CKKGzWWdSvNnJeNPRZwT88IM1qwlo0R7D+TT+mGhVMd6302mdaNIOv8+DGqxo"
      + "a4bBypAaumiGL728xefOaEv7tOSQCiRpqyFVM0L9KWlwA7Tin1YsadqIQVuTsDNpF/IFeXZMV2nu92UVt7dwaRlDVKEtjHFpJtBa0wQtpWl8V8"
      + "+/pfD7aX5I27YSHwpqsIrwgx+bE2pVosJRiPQmao1rzffcLVRq1fqh+9B9VGodgzwV/oJpanmPvd1N/5BqQ+F1Bzxan2oxVVNZUWy9alTU/J5T"
      + "GOdqamS4tGs09mru5eaOBgf9alDQI8zG2WprhBiXuuO0dWvsDSVQpU8NbA88wRMtXn9siiactiAfhWxHEn+xm56rbCoZLk7S+7xszWjKsTfODW"
      + "1fII0E+BtIbe4eAKkWHVht+OTb9Ap8WW0UFMJFBoFabSGi7NfX1mdtGxVZPD9Me20MWdKuC+WrbcU3nQPj6+xtJc3zC1G/UG7z58pHjMdXbmEO"
      + "RJL6tHtuFjXLFNGcim5aI0hoDruxbpnnpAcNOtVu1sMXHdRS4m64iM6RGLIVbxnHyx748x5vabbp0BxMI2/cn/yx1Ecob9XEQtt6b09vzHs/Oz"
      + "1lrW+mL5IKfReyb04FtgdKJcpvn2wvpe7FzG9+TVMuCbUvcMV/w2SAI0Fw+wSWVB04UHBAnNyT5x6WcCd88QJ7zZdwimPEo6QFpHDn7Zjoky7K"
      + "cIW4o4NuBtxwmpBPXadK43ByfbbkOcoocQERWtK/NUJxoXT5pmcpbHFJqpj8ZYyVcc8WtQFoUg5yE7E2hhLfL3LQcoytr72yckyasf1kL79yxX"
      + "jBCjbv63LuT703Q8LvciEoVStvfwZzn69JeVTSLHMcrvFDkZ1ocyYLbVtqtrZzAGUs5kQbx3N8/Hi0MD8BdB2CduIgoUN0V+l6Cg4jWXR529Pb"
      + "KW2zdFcJN71SX7Z0h6W6+SUzCXVsyU0wW3xAdXzYxdwuukd1qR7AYu+yt3WFTOgYaWPZdcN73tj1fPN1u3foXfTHD3br53hbDf4ddgY88T4RgB"
      + "52WaRVDXaAJHbJrHnCSY0odnKw+D/L51p2AsSp14P7dnZRVr/+meOHdr9bN0A59Jd2mFQw2XMdpnb6nu8zTg3GdtuXTffvn9B2IRoC48Zc2nb+"
      + "9D5ZA/rjdhzAWhaX0id3buTFyYTDSnd3m7/vS0y/dxH28GHIkeN3qfpXL1Nj+XfTjD5cRmD8d2sCDKKYZDN47/RANwSoYng9xdSkgQmCeAQVuQ"
      + "iizYR4/TqfOxQdAHk35tG4sKQFeRK+gYm9mxV5bMK9GajjG3nsWqj/O20yeRVY1FKeXjt5tiI+M6NOXHnTZJsJBpWJecQ+OMBgopJ5Sr9Qau+n"
      + "tHmsq08Ee2zDeVHBZMpJuNJ5MwKuHQNa6nkIb14ogYbqeSJhg/GnNO153Py6aCzJIXqFZAcWBokiejq709nf1z569t+QKk2yVHqelkZHzdSDer"
      + "Y8m0DMOIV6Al2SD33l33pHFxYtIU3xeqw/6tgxGgp7nd5eYJqQF3tyFT1f4DlhexSPcWUvsnF7XqL0UXhVkntCxdV12uiZe53tGzCuqLJ7E3zL"
      + "43g2MnzZc8WQws9QfFT6IUaqrot8l15DVd8il3xwzOnnR629fLDM0++KlMF84PSL6pmDw3w2U52a/SzFfOSnt0CVOxl9aSlmx+Y/I303Phk3Xm"
      + "QtfVDsNSqp1UF9qlf5SChhSn3FqxUxdxlhfec9QYcVsZF9qN+AqobWuX1l1KBbsD3AfdlSpqR1R+J9/YQ3xqsW533D8rmNpV3yfTEQdD+vVfl9"
      + "6pgJOV03MH6/7wCNc4wwftgtI3dLuTV+8N0X8Wt2/n7ctCA0xSVtf2QzddqfWL5/m56n4Vqlw3/3XorjaDXEf/WhA2wR7sR/tHIbsHex13+31B"
      + "fXKcfff+dPeXlgcvR/";

  private static final String THETA_UNORDERED_620 =
      "AgMDAAAKzJPoAwAAAACAPwig26RoX68nFeAi181TJyYcwFoWl9IndygghCWAfFEKMEC1XdbDZhU1oJ1kb7LkIjkgS8FFZ8UqPsCxqj4lcTxYoH"
      + "7wIKVDGloAnkI4NrIsW6BM3LSS50xfII0E+BtIbWBANo3dpERGgGCvdVoF+mOTwE1ivTVdVtyf/LHURyhvuWDtzfXMXRy6QLPB2gZpXcDg+aLH"
      + "xbpTxCCGAxaKe0/JIN6oJn6+GcvgLJ7DqRNU1GBiKtOOsEzaIHKvcO1mH9tADeznUM0G3AB+582U/mSAoBdQMjm0DAAh9F3dixc/AyElVITK2C"
      + "YEAbRA5N/KUxNBl4NTusU1GyF4b3DMPUwiYYPxpzTtebrAxxVq7bExOeEWLODS/y87Af+htkPbVj3hFkwV5dE2PqG4wYz8AjND4XUHPFqfakbB"
      + "Dt0Mgp5DSCFIDyC0MkxRIXh3d4BmWGYhQe9OgThadyEl9P0xFT6BQa96Okg9LY2Bn5T5Bf48kOHdFCPLJgmYoS8p9SyXK5qBoSX+O/lHUcFkyk"
      + "m40nmowdotX/qHCalB7ZfhP9URqyFVM0L9KWmtwTplULzuQLPBQbF2TXoatqHFx6hBOTu4IeRQ7mtmDsdhWPdAxEtQyuEQukCGkjHO4TLiQ3Kv"
      + "SdDBSDJL4Uxj1yHhBW4Z1hDZYQ82iDQnGuBBcEzihjst5QF2YWWXWR/qITeGIdk+HvWhA2wR7sR/BOK4x5Pr5EoGYiROhMgGPQkCvUGwWKQdCi"
      + "LbtxyHXwEPwifD1xVMKx2CduIgoUN0IaLs19fWZ20sYidY1nsVUi9Cc+x2Ff9TMwKuHQNa6nlCIn4/fWAfN0bixDKrJFU1SWK7kGK2/ANP4lF/"
      + "X1vpTFWiwlGI9CZqXqL0UXhVkntrAgyimGQzeGzCvRmo4xt5beKp1l/GdlxwQqOPE6fGG3NiaN5La/wDfOIkUg4dTBzKIesDHZm9DYDCsYdl2s"
      + "4riMJKUMLkFzuJAjxLT0xpBYuCPT4Fbc4NjaK8GEqH7w+Yoqx9x4CQUJvimc5OlGlaqwIimfe0viyyYgui9ATVDrYiPjOjTlx5t2IaKY0JS0i4"
      + "YnpebcBnH8CirZQIDloi0aL9LGsVdTfXomAmSW/QNuZiOG49f9MD6EIhoOkhxij0QraTrwnHPQUDwCUQecIKDsNBuTVnqDwWowLX7mY8PBlDVK"
      + "EtjHFpHYM8Ff6CaWomA1iZC/B4TSijcJ7ffF8kKgMWe2+4th4wY8cPj63aZjHDh8DqnGdXOEOTUl0lSEpwgowxkSqQX0wjz8SHea5VWiNIaA67"
      + "sW5iI7sh70mzPWcDiLbIMyhJcAO04p9WLGmLIo/E832SW+gC+jO2KPgUimPEo6QFpHCNA2HgOaHlW5HD/42LiAlQkqO8cPyXPwiawwugCmRjL5"
      + "ujhBEG3ckbnUP/4lWBoASg41hRWUFWObwjtIR++OtbxqPHz0/0jgfJQ5tIB9LSJ8oDYarnM58V1sMXHdRS4m704wuDUFnZXwLEqdeD+3Z2BGTG"
      + "Jbg1CRIFpGvDci+5VwdE3/vIz2AxCsR19Lb1ZAUVZBB/j0u2Qhlki4wn2JQSJqR1FfUdiFxLpEHQPrHqHk3Em//werVBUIRYTnos0BdRRNdLFP"
      + "mbW1mkVQ12gCR2XkQHF2oTohFqZLi0azT2am7kxcmEw0p31uP5dGcuZ028w5tbqdKZM4GECRDLOu5AhWQHFgaJInqgxNH3XbBnIqdkE2Wmj9cw"
      + "rQTEhbJx0Re4ZLtXDKC1ZLqEmS6a2mxGxiTWEkX+fiHHxIGFE39zAMlk+oFaTzRjzCQhCqlc3RnTZJsJBpWJedXEQtt6b09v18ToZMg9VBTd5I"
      + "BItcImNOekucwfdmsd+OTb9Ap8WW37BJZUHThQcP2EN8arFud9AGUs5kQbx3MJBTE9AeRPMwwFI9MTy403DkU8ZQqTMGUXJRCMbi/eWBilJsu7"
      + "xV0JI6VbOBr9dB89xdSkgQmCeELF1XXa6Jl7RaVHM6ys3QRJ5SPMQLvYGk1FqT1CLvYTTgW2B0olym9PJSwGqaNWMWPF8lBXXxgsbEUa2VZAwB"
      + "F4ZXOt+4lLJ4NFfaKZ6a4RhqXf5udg1DOHpbr5JTMJdYhlVzfRCnQBlOXnMZ2LYA+cRZRFUAsJPLRlmgIKR/QJt2Wl29aNjT+9ZftTyybhKMll"
      + "n1KIyQM/zIVkTjzADWLPxbU5QwDaQdsFu/45uVtC5yXfYohKEWDqRUYEZq/NV+7l5o4GB/1q84XRF2X2xQj5pTFJsvfhBwWGRWbqNOFcEIYEJO"
      + "XtwB01Zn/omzdAUTfm0biwpAV5Tsb6GkfbrVBPRuuz69UgFVJGPiMPz4IwU+aus4f3wk9aptYtBm6lX1wGLshAd7lcYmZ+Fzpq9mJlRq+qE6RB"
      + "IGvGzjcdghESdsaQG7uQAxJrhsHKkBq6aIomnLYgH4VsjKZiWOmnzS6OptONUTTlG49mvalLU+wZmyY+ysxblwmfZhBCGc8mRaemXwDuxX1EuQ"
      + "YDvUkBjU69xqO/IJfxTtXG+vIxZc072oZ7CV9HRQjfZn8wgoKpFumml4B2mPhC++ZBSSgqrWP85hY2IplCTf3GxUgGntEMAUc5g+GYUx8MJwWG"
      + "Hyl2JROHmWDMP21fGcfLHvjzHm87J2vj1fwtEE4H0xhIf28nUGf5zKgx4kJRZwE+7+LdAFKHnjWedL1VVKd2IM4aIVlfZxvYTkQPE2bHqxiR6C"
      + "kgaAf1vTlxWR5tB243mWy0MG8H2FUfaQFXcIcvm19DUj9zR6JuOU2ZAnnHhbexPndaiccIJAAFxVaOpw5InxhYBZGHb+THW65NkmfnxD8CA1SZ"
      + "56QHDTrVbqXnr2J5LeArrWexs5VYXw9Q5yUMpQktIrenx3ITWdsa/Mb7B+KjxD26R7VUZOD+H8HHjmWp+/pExIfkOaMQv0bOJ5i4Ws9/FdUnWD"
      + "suTVlU2sdE/en7UjrdRyan41j/ZOTHWBKaxAYB6Ke9aP4LhgTr53hbDf4ddvPnykeMx1du94cFKBbrSRISaKy5LGZHKx9IJNpw+BchIShVK29/"
      + "BnMjyN+m6JCcXy5ohvqvY00sNAj1+JHPu0Dkp7dAlTsZfWBok4rzh34yb2jSF/bp+VJyKERHxNxOXn5I27YSHwpqq+i6lbF0SCCsKHkHzNbPDK"
      + "8Ige2n06ENswhMUvGVSF22iBlmUBIQV7iIzpEYshVvvWjzsCqrbFLGyEzeiD0rI81oyrE3zg1t04goDpM+/CLUKFDZtPIaMtdobd7qjzw32ohB"
      + "W5OwM2nxyGBs/9PcXPMod16MOB8TAQkDSqSjfEIT6cdjsz6fFScpvfRIDtUcOUngGNJSXmBNafXW1YsqJlfpegoOI1l0WIltwYSGuURySE+Gxc"
      + "onW2kpZsfmPyN9aqnK3iQK7QVsyU0wW3xAdW2pFrxKZmEedGmUBpxfZSGHCQW29EGnNZCJqzlxwBgQlym7IcuW7imwyeikgeAQUbKJW+PPY7kp"
      + "Vwk3vVJftnTLiSirNBrXOdWJ7fK6dCoA1gnyME7ThUbLabF2q5ukYOmJs8QnKQ8q76kW7oUJ51f6aflZPKKDCP3p5bvb/H1F/6lvDHvOfksFCi"
      + "e+dYIGHQyqXuWJ8O5GJAo+/HLFQCE1CrUbLkp9XTnK3nIx5X5FSaqY/GWMlXFSKsomdf1zKlaqpts5axQ0fgrv+mF9VSSwChQ7RcRaVLUKIyFO"
      + "nykUsIrwgx+bE2rBKlFkVBnqKMgK07dUoyZe4qn+6rtpoDzVClLoHijKE9lKePI52Z9c32pMOKf+xD7zKjeJDXRjVvlKKJsSLglS+4q35T77ew"
      + "YKS6fDyeNhOSALoz+Df15LI+vZol4YHSkl68JiLg6mJSYLbVtqtrZzKivYIPVh4i8uy+tamBGAJjfrZzIbio4sQksyUC9v/zFFCwRD02DAMFyr"
      + "VEATPXk934qo92AGHFFpi7mRuGhXCG8rvOD5a10ReiurFapVXzd/CxYZInQ5WYqriLb3HQkfjWvN99wtVGqdi/lovrc2K6DrayqCsB48oYsubG"
      + "dLIDWsq08Ee2zDea7L0A3zAFYHsYvvLTs2mWS6y2nXp/IiKyWL+f+zq0AuxasVMXcZYX3la2HuyIBEIOYLx25Jr6UI5ysEdyaCIUbqS4qRYc5g"
      + "I+0LTW1SugYF7wvSqxnZ/2X769AUUhkIHQ7s9HYnOg4YG0zRSZWYUhUfbAcIHeoAYyMMb0XBgoBlK8w/fb4RhCsyzKP8m0MqU0Ns8OgU4DcJUO"
      + "w1KqnVQX1S7BlJHS1oBVSsmUiMGzlCX0zM1W8i6DRiDGrNCpJiSWzMft7IWaYjcMzp50etvXyAjOzpm2jeOoVM6BhpY9l1j4xhi9DTERefbC+l"
      + "7sXMb6YM04BTkpMbsMzT74qUwXyxbKRRzt/tZcmsecJJjSh2yqypF9MtmybTjD5cRmD8d9uM5zvmjA4y3qxr4eHZZQDfjMDmRUdLMeMMNRbJCu"
      + "5O6ex3T6iAfhXw7L8gtMStJ/Ws19W4/XsI+aztCb0YAFUD7R8Vu2D4OQptFAkWZtURF42JbY/ckiciDXHyJYOWNSXN8wtRv1Bu02w2ffYwQ1sD"
      + "rZPwXaFxFFSNknmTtqhFXC09ifMEuERmrWxYD5bQFW6tAGe+TOhOeu00T25WUjV+zZjQ3v2+WozthFqhbuwVne0bMK6osnug7TqQUGqeVKENpQ"
      + "LmMGo3fk1TLgm1L3DI7asKe4g6JtTNOmLfNZtM2C0jd0u5NX7n7Zjoky7KcOwNJVClTw1s7+2MsXY70ikBbikwPahqIBDuTznzFCNOHK7xQ5Gd"
      + "aHMxDmv8EjoTQ0UudPC6PY8TR04hrQTYoD5O7uhSUtgLHZ/s7YhsgPwYXo6KOSRRAENhTs01Qn9vC2kuJFDM+5QebS6Jn/HtQ19hDkSS+rR7br"
      + "fOc3N6v9gHxC5ZrPKbITnRzpB7mVgmJdIOv8+DGqxo306/6zkhNyTh7ijiCtjNRPfOedKDf8kF/I4BX1yQKgUIb14ogYbqeQ5vYxexqPJTEi/T"
      + "9IkWjEcUj3FlL7JxeydPaDfIBQkU0e61sRm0kwI6rzQlQHyBEjxv2CTM5HYhQM/CscasjFdYz4n447zjPl4PgvG7Qlkwaq/fmVxoaC1vj6lhBR"
      + "6tCXmPvd1N/5Bqhi+9vMXnzmiMT60xwh4IJJJvP7/ELmhfn69JeVTSLHOmL5IKfReyb6kPeAxQUHcIhq+CKKGzWWeyb0VgFxA2DLzvMl6Kh6xM"
      + "v+8AjXOMMH48j4mWVPu8OtrvwX8XU9RR5095eWBy9H/or/z92G+VEe5PvTdDwu9yPC97GAoPuwf+j0n4i0KuVAdwPdHtlhYvCPCt3Ob6Ei0dcP"
      + "cJoUGULCOwqWFqcTVhJtBa0wQtpWkxEHQ/r1X5fT2QJWAKJfRhUNAjzMbZamtqj37gOnqmM1RQ4WHpl3I2XLB85FYj11ZeECnhCObfFGfQ92AT"
      + "CEwucrD4P8vnWnZ5sJhZ6mCzRH8QuX0Lix5FjNDJhkzJOiaakE9dp0rjcKNQCdRiz8MbpZB75TT5bQOsUJqx6BUeIrnwFrkO/JhHxZCuZlb1ex"
      + "7KUCfUTu4/Pu+vrs9b3fQB4ZA9q5ElWjPjsP5mwtHoQeSQ0uJvF9YM53Ak5KbbFxT0UMmnWsrZIfWQU3wXTPk++VD9asHFpDUBEVrSvzVCcQ2R"
      + "VMqG34AbE7E2hhLfL3Ia0TALmYwvIiJRvInbJh0lKTFdNJ65gTcxcQmgc1JOZUBx+BZxiiZURTE0h374DTZNETqMK8/yC1VxDSKRF6ggYzGaVy"
      + "st5gdqkYsLC+csD3Kwn0VEx5wPb7Fp6f2Gch17sZALKG3FNH9x93kO1zEzl9FFv+JbLjyisedzvXoLR7sRrLOVu8IYvhEek4VG/gjKcB8q644h"
      + "FsIxbI83A/ZeyzELh2UGChTOEQl8MvkJJtdxoeBrcl0y7XHqJriFhDEUsvpHtmv6TxZSdtFhaOIFF/IFeXZMV2kfco3xbYEOCCmSB53AWW8FVT"
      + "Het9NpnWhHEn+xm56rbE/yTeC8DK4cUbK8dqZvDR9TUj9v2ImrFnASDcmr7Vo+dFLHUTbTq0uUEhGwgLaIQ5kSsQiFE7cwoBKU3R9SuFS0chuw"
      + "d7HXf7byjolPX3IhvTJzckaRzBS+srztyLjjWJly8hOzTnNQwfKIeHe+NWXD8rmNpV3yfdByjK2vvbJy0/IxGmLDpyfZUqakdUfifd8y+wg+zA"
      + "1C8FI6P1k4zVz2UiOBMwtXLwYTXZ9pKYkfELNxZUAC9lcbU+X7i4bUQSlzdbhQdeEMNlOdmv0sxXxUs95zQ/JPJFuT+Ugl2ocPZDN12p9Yvn9t"
      + "8/uIVY2WAoHTWeeb9Y9KizP4idqNBz2Vs7UKCBE8F6az70QYxEs1tNN9Ojr1gWW4M7Uaw25yA8QTUCbcFRcQ2XPFkMLPUHzhU3uOJnf4NAs0VD"
      + "m3uehfDxTpI8Pi4jsTlPV/bsNKSBQUwkUGgVptG7TsqqhzYlQeFPhNcozUSTV0xRMLSKhLO/Rz/J53JQxAtPt5ikBBOkbUezw9asVbVNT8nlMY"
      + "52pZVFx9lWTWGV20WTtBsxNXX5RaFY9jNWFjFDejnDrUMmXUoFuwPcB9aZSJUHYWk0tttA/TgXIdS3b0nshKEsssplNtXoBmqROEVO9y4iHjRI"
      + "rUZP07NUwikNQMF+q0oTuVlFelpz64JZhUMNlzHaZ2mtQYKDOmoS2dNFeOSWYtOqF0+aZnKWxxp5SvAqP59GC31BfXKcfff7m0+H132+phwjTm"
      + "4lmEHTvMtF9Vn2nGNtSUHWf8ccxFWdRXDdDv80/ctCA0xSVtf+D0i+qZg8N87/RANwSoYnj6dLNMFrFuAP20YQl52kJc/vQ+WQP643YEFbkIos"
      + "2EeJBUCEa4UyooFjXLFNGcim4aNYd8IgfoIxsVWTw/THttHPXVxXEGxAgxVVNZUWy9ajO1luENbEhQPhW8D8fmiTNR9TZNjffKRVI1nDtxLPwb"
      + "apW+KujbK1ZutddTTU0NEHIVPV/gOWF7jpWNEGFd8AeSdQWmSd7fNJb1Ho147j4knBV9tF1JOjOj9fOXE4uSQKl1OsjhMHtWrPUwSzu79RS71Q"
      + "15I5rkUsCVLvC1NMguxrVGtiq6EzvPVVB60gaTEta13XTrsGxf5ZU7ZJyoaF/u9bS2rBMOV/D1dTMn1Bsl+VX4pXEl1C4R9vBhyJHjdxi2gY/3"
      + "XMxTG9bzcT7B914llnlshj6yBRt2MVqOVf81NLb7XE7g/ls8lnc5ILqAYEl20VxnpHRMUVa//pnjh3Zc9rcG7DpjOmdWJBkADUpPabbp0BxMI2"
      + "9wVtdQdUCfHXOWbGhsGDYmhdYgu+zfwR+XVp+Aiz9ETpk23jdHsj8pnpZGR83Ug3qhtuPRggTcD6R2NX1qxoxbqbYXQimOAUiwNt4NUb11Yb/W"
      + "lVpcVR9Xy9ZhQhLCwyzPFrUBaFIOctG2crJ9Gbwr71Z8MD9XNizw9qThFZ19KfeW+9UJSaol+ta4la/q+BX+FiET+5i8EAsXEPkydgAXD5dOMJ"
      + "JETj0aF19JYF+HPA/3YH7RPcEPK5cOHnq/UWIttxBeT3MTSKH2iWI9jwQGRxcWLSFN8XpI1wVVIf6TM1f3YKWmUDovWnceqPveklxbV3jNDAuu"
      + "W2bX0q7m12BAcFdWilz6EyJylyorBCV9KnP3gx8T24c5dVc0DlMb6VF8V8+/pfD7aYL38arHUUxBkpeCNuW0+hSqV/lIKGFKfax3BOweaSUvsv"
      + "frg2FKy1YR1mhG9DqZV7t36F30xw92vbctHIN3VRvAVxmihtBjO8OX/BKBcJ0exTedA+Pr7G3St1UXVP3TXtuXBPF62yI+7vdlFbe3cGn5d8cM"
      + "CToKEAA4UdW/ifk7FTiTLx3TrjcY2KfTA64jZCAY66sUorMxcheLPeVuiwwqGIvOQTtxH0tY4Hpcv7xcVNhEoL1tHltZ2E/hQm48VxVY1FKeXj"
      + "t5YVgcDNKF/UJkGHiWawuIXGf4rfV42Ys/atjj7jM9Si4AeEc24B+fEXzYxdwuukd1gVheYCBqJ0CEGJe647R1a4W4o4NuBtxwjBgv++XzhDqN"
      + "eNmPYKaCD5qYcf7kP0EhoLghJQQ94Tak+GbIDahfUav4iyjMpqkWsxgieuH6eC7bl03375/QdsV4wQo27+ty2liUxmNmsj/huOfIN0CjFuJY00"
      + "Ynj7UZ6DjBeEMYmSTpeF47IZnsQ+qYCTldNzB+8JgsIvmTvyn7OHmJEySPAQGZQKijMXw3Bxm6L/6bI1LwmAEvvW5VMQtZYHNAkzAIDFnSrgvl"
      + "q23FWLKUWyMoMRX5fcu9hqEFIBneZbxjngsqGS5O0vu8bFgZ2+S41hw9Yfm1Dgrg5Rx1mTa1VzLoF4O5Msz5W38Nk1nTd2sQf0iXeZVdEmHzYl"
      + "gZZNkLD4QotBkxgPRyJyW5udU+LrjaWdF5Tp+3YcdC1blD14YpNinXedazX/1wQfvYvRtVZDoz+XmpPJGJ9hv/GRv2XN5gQwP65QUNbTIXGLpv"
      + "HIebHywhGgLjxlzadiT6oqAzR6IPPrrco29vtiBJOtQNgAQ0X0yasf1kL79yUPrAE1slaSNU+iFGqq6LfFh6mT3IV7E+X3p8FYJghid6mjN6FX"
      + "3+IJpaVUcb7uQQnpqOJbftM0ahukShilziCan6Vy9TY/l3rprRGaRwJwO8eroW+Tv5ENL6/VNWDrUG1fqh+9B9VGrderWvHx9hIuHakiK+roha"
      + "4trPn83qvgTsWqj/O20yefMaSqnZaN4Y+ZqeZAHysBP9Op87FB0Aef+6+ClB/3NFAHsjuqjifWae2lYkR8jqOil7tS9RVk4tKtvQXYFv+RkxW7"
      + "sTV0IUIjq709nf1z56Q1tVNu7wmw9DewDPONIwVkv7tOSQCiRpU3uCJramQwVeG2WVGj66LG77bReVOKwadrslh9y9pjl3m7/vS0y/d3nb09sp"
      + "bbN0fftlLo8YPF+Qm/dxXGQtFJh7eM5VKa0HmvspjWZqOCCjW5QXzU6uCaxbnI0pnjJMedujoGhwPxm426UaAMyJJbsbYq6RdBZdv1s3QDn0l3"
      + "bCmx6fXpaxZcN73tj1fPN1yHsJociK+T/Mez87PWWtb6xb4mYfntka1ltmbP2MJjHiW7eC8ogkQgT88IM1qwloBjzxPhGAHnYPPMETLV5/bBHc"
      + "jpJf7bhPElwy+9ZSrmATfMvjeDYyfCM8medT478SJ3zxAnvNl3A/XDSKh6LHE0Cc3JPnHpZwShx5Hoy21VpSvNnJeNPRZ1VcFve6ZyA5azwaN8"
      + "wFdjxxfGue2NlnFnk8Lk6h1YsdfPx4tDA/AXSBvNnVNVRRY4n83DDll9JNlZx4O23Gql+efLnsoBp0K6o8Aqd3+2QesVwEBcZvGya2PJtAzDiF"
      + "erl8BDEbOpFKwrxd/8h6Qj/c/LpoLMkhet38GJWUWd0UBpwtzT/QRGLknHnNHFPOGgJdkg995d96D10RkNyIsQMU/frdos9WTxh9w43Sfc5RG5"
      + "324Tz98CN5PEu02iZLMC+9Xb4GgIVhNz0wvJnlm004XaDwZjvVA5Wci/6z1IoZUD3yMtRDpj9UfW53JjimNF29n3njVTIHY13CeuUIljhkPRJu"
      + "i9c7SWg9gyspBmtcb/3c9FyuLidyfbbkOcoocVA9QqMmtasYeN2Va4AajVqRnfVc9m+6ERg9SMgu0DtVnb3qCV5BFzWg/QZhduWOCKldp1LWhj"
      + "Unqr2jwfsmC0nLXTAt9sQ8KM3dMbQZioAM1J3aP2evIVXWfd5ZaxHhGXg9RuN9fNMB5z1BhxWxkX3qHYWBEdZsYvDdF/Frdv5+Al6hyLeHyR8N"
      + "Xujm1xlASBK+gYm9mxV5Nz4ZN15kLX05PusWE86zAz9emyRkptYbQN4u4cnbPQhBHnjCrCFgP0Net9pkl7MVSX40gs2mcF1XHsScr0GXOmheuQ"
      + "afVPEuaT7GWk+zDUpx/mpsjsBGO3demNwVBB1beT4OOStczEh7/o8jgY4bUn/+meyjWxkOg773Co/jQ2GU3tbIoHUqApZ+1eBVwM4zl15DVd8i"
      + "l3ybnqfhWqXDf7Y8L9zKGdJHnd5eYJqQF3ug/nAl1BI3EqZ+ZQMsvLhLqR7AYu+yt3U5XmeigNYaJ7IeixxFJUgLwB51shtp+DTEPjjAYKKSed"
      + "Eew/k0/pho1N7FK/IbwmLRXqBCjZzrFuKetE6gzgdZ7h4AqRYdWG33XorjaDXEf/n+HCvEf+gq+p7vM04Nxnb/PttJMfqWAAz/V0oJ1mo3I99T"
      + "10g+sDXiPmQsPczkUSa/hSp0h8ALLp8MEtAW5RI6n0APn2tIXkq/UGrvp7R5S79+7n5A9QBQHwCmmRFZPlWfsXNfrnQcWJ/Orapei1Fav3Q43y"
      + "YREWafQy1udYoYcP+Av8uYwSZ7f+xm7Xh/AYz/rYefHx4mjx8NIjM1lSGWf3gY1RLhXqjfgKqG1rl9rD/q2DEaCnuvXxWmSZJOAbMfQa9benZV"
      + "tv+ymriRpiy3/6nmHBcbFLm/n+r6nqoBwN+lOQ2A+zvFf8NkgCNBcMb/7p64Pzc7y18UNiUraFfPv4fCNfO5JNafhNy05hUM3D+fVAyZWgi3v0"
      + "J5lTZKJ/bfkCpNslR6";

  private static final String INT_TUPLE_620 =
      "AgMJAQAKzJPoAwAAAAAAANNsNn32MENbAQAAAAAI8K3c5voSLQEAAAAAt79CeZU2SicBAAAAABXgItfNUycmAQAAAAAcwFoWl9IndwEAAAAAHX"
      + "D3CaFBlCwBAAAAACOwqWFqcTVhAQAAAAAm0FrTBC2laQEAAAAAKCCEJYB8UQoBAAAAAIYvvbzF585oAQAAAAAwQLVd1sNmFQEAAAAAMRB0P69V"
      + "+X0BAAAAADWgnWRvsuQiAQAAAAA5IEvBRWfFKgEAAAAAPZAlYAol9GEBAAAAAD7Asao+JXE8AQAAAABQ0CPMxtlqawEAAAAAVFDhYemXcjYBAA"
      + "AAAFigfvAgpUMaAQAAAABaAJ5CODayLAEAAAAAW6BM3LSS50wBAAAAAFywfORWI9dWAQAAAABeECnhCObfFAEAAAAAaq/fmVxoaC0BAAAAAGBA"
      + "No3dpERGAQAAAABn0PdgEwhMLgEAAAAA3J/8sdRHKG8BAAAAAHKw+D/L51p2AQAAAAB5sJhZ6mCzRAEAAAAACKDbpGhfrycBAAAAAH8QuX0Lix"
      + "5FAQAAAACAYK91WgX6YwEAAAAAjNDJhkzJOiYBAAAAAJPATWK9NV1WAQAAAACakE9dp0rjcAEAAAAAo1AJ1GLPwxsBAAAAAKWQe+U0+W0DAQAA"
      + "AACsUJqx6BUeIgEAAAAAB3A90e2WFi8BAAAAALnwFrkO/JhHAQAAAAC6QLPB2gZpXQEAAAAAwOD5osfFulMBAAAAAMQghgMWintPAQAAAADFkK"
      + "5mVvV7HgEAAAAAySDeqCZ+vhkBAAAAAMpQJ9RO7j8+AQAAAADL4Cyew6kTVAEAAAAA1GBiKtOOsEwBAAAAANogcq9w7WYfAQAAAADbQA3s51DN"
      + "BgEAAAAA3AB+582U/mQBAAAAAIxPrTHCHggkAQAAAADhkD2rkSVaMwEAAAAA47D+ZsLR6EEBAAAAAOSQ0uJvF9YMAQAAAADncCTkptsXFAEAAA"
      + "AA9FDJp1rK2SEBAAAAAPWQU3wXTPk+AQAAAAD5UP1qwcWkNQEAAAAAACH0Xd2LFz8BAAAAAAERWtK/NUJxAQAAAAADISVUhMrYJgEAAAAABAG0"
      + "QOTfylMBAAAAAA2RVMqG34AbAQAAAAATQZeDU7rFNQEAAAAAGtEwC5mMLyIBAAAAABsheG9wzD1MAQAAAAAiYYPxpzTteQEAAAAAKTFdNJ65gT"
      + "cBAAAAADFxCaBzUk5lAQAAAAA54RYs4NL/LwEAAAAAOwH/obZD21YBAAAAAD3hFkwV5dE2AQAAAAA+objBjPwCMwEAAAAAQHH4FnGKJlQBAAAA"
      + "AEPhdQc8Wp9qAQAAAABFMTSHfvgNNgEAAAAARsEO3QyCnkMBAAAAAEghSA8gtDJMAQAAAABNETqMK8/yCwEAAAAAUSF4d3eAZlgBAAAAAFVxDS"
      + "KRF6ggAQAAAABjMZpXKy3mBwEAAAAAZiFB706BOFoBAAAAAHKwn0VEx5wPAQAAAABqkYsLC+csDwEAAAAAb7Fp6f2Gch0BAAAAAICgF1AyObQM"
      + "AQAAAAB3ISX0/TEVPgEAAAAAe7GQCyhtxTQBAAAAAH9x93kO1zEzAQAAAACBQa96Okg9LQEAAAAAjYGflPkF/jwBAAAAAJDh3RQjyyYJAQAAAA"
      + "CX0UW/4lsuPAEAAAAAmKEvKfUslysBAAAAAJqBoSX+O/lHAQAAAACisedzvXoLRwEAAAAAqMHaLV/6hwkBAAAAAKlB7ZfhP9URAQAAAACrIVUz"
      + "Qv0paQEAAAAArcE6ZVC87kABAAAAALPBQbF2TXoaAQAAAAC2ocXHqEE5OwEAAAAAuCHkUO5rZg4BAAAAAMpwHyrrjiEWAQAAAAC7EayzlbvCGA"
      + "EAAAAAvhEek4VG/ggBAAAAAMIxbI83A/ZeAQAAAADHYVj3QMRLUAEAAAAAyuEQukCGkjEBAAAAAMsxC4dlBgoUAQAAAADOEQl8MvkJJgEAAAAA"
      + "0MFIMkvhTGMBAAAAANdxoeBrcl0yAQAAAADZYQ82iDQnGgEAAAAA4EFwTOKGOy0BAAAAAOUBdmFll1kfAQAAAADqITeGIdk+HgEAAAAA7XHqJr"
      + "iFhDEBAAAAAPWhA2wR7sR/AQAAAADXIeEFbhnWEAEAAAAABOK4x5Pr5EoBAAAAAAZiJE6EyAY9AQAAAAAJAr1BsFikHQEAAAAACiLbtxyHXwEB"
      + "AAAAAA/CJ8PXFUwrAQAAAAC5YO3N9cxdHAEAAAAAFLL6R7Zr+k8BAAAAABZSdtFhaOIFAQAAAAAX8gV5dkxXaQEAAAAAVTHet9NpnWgBAAAAAB"
      + "2CduIgoUN0AQAAAAAfco3xbYEOCAEAAAAAIaLs19fWZ20BAAAAACmSB53AWW8FAQAAAADO4TLiQ3KvSQEAAAAALGInWNZ7FVIBAAAAAC9Cc+x2"
      + "Ff9TAQAAAAAzAq4dA1rqeQEAAAAAIlG8idsmHSUBAAAAAEIifj99YB83AQAAAABG4sQyqyRVNQEAAAAARxJ/sZueq2wBAAAAAEliu5BitvwDAQ"
      + "AAAABfII0E+BtIbQEAAAAAT/JN4LwMrhwBAAAAAFGyvHambw0fAQAAAABTUj9v2ImrFgEAAAAAVaLCUYj0JmoBAAAAAF6i9FF4VZJ7AQAAAABr"
      + "AgyimGQzeAEAAAAAbMK9GajjG3kBAAAAAG3iqdZfxnZcAQAAAABwQqOPE6fGGwEAAAAAc2Jo3ktr/AMBAAAAAHRSx1E206tLAQAAAAB84iRSDh"
      + "1MHAEAAAAAgMKxh2XazisBAAAAAFHBZMpJuNJ5AQAAAACIwkpQwuQXOwEAAAAAiQI8S09MaQUBAAAAAIuCPT4Fbc4NAQAAAABP4lF/X1vpTAEA"
      + "AAAAjaK8GEqH7w8BAAAAAMoh6wMdmb0NAQAAAACYoqx9x4CQUAEAAAAAmRKxCIUTtzABAAAAAJvimc5OlGlaAQAAAACgEpTdH1K4VAEAAAAAqw"
      + "Iimfe0viwBAAAAALrAxxVq7bExAQAAAACyYgui9ATVDgEAAAAAtHIbsHex138BAAAAALbyjolPX3IhAQAAAAC3YhopjQlLSAEAAAAAuGJ6Xm3A"
      + "Zx8BAAAAAL0yc3JGkcwUAQAAAAC+srztyLjjWAEAAAAAwKKtlAgOWiIBAAAAAMHyiHh3vjVlAQAAAADD8rmNpV3yfQEAAAAA0HKMra+9snIBAA"
      + "AAANGi/SxrFXU3AQAAAADT8jEaYsOnJwEAAAAA16JgJklv0DYBAAAAANlSpqR1R+J9AQAAAACUEhGwgLaIQwEAAAAA3zL7CD7MDUIBAAAAAOZi"
      + "OG49f9MDAQAAAADoQiGg6SHGKAEAAAAA8FI6P1k4zVwBAAAAAPRCtpOvCcc9AQAAAAD2UiOBMwtXLwEAAAAAcIKMMZEqkF8BAAAAAAUDwCUQec"
      + "IKAQAAAAAGE12faSmJHwEAAAAADsNBuTVnqDwBAAAAABCzcWVAAvZXAQAAAABwEg3Jq+1aPgEAAAAAFqMC1+5mPDwBAAAAABlDVKEtjHFpAQAA"
      + "AAAbU+X7i4bUQQEAAAAAHYM8Ff6CaWoBAAAAACYDWJkL8HhNAQAAAAAoo3Ce33xfJAEAAAAA6AL6M7Yo+BQBAAAAACoDFntvuLYeAQAAAAAwY8"
      + "cPj63aZgEAAAAAMcOHwOqcZ1cBAAAAADZTnZr9LMV8AQAAAACZcvITs05zUAEAAAAAOEOTUl0lSEoBAAAAAEwjz8SHea5VAQAAAABUs95zQ/JP"
      + "JAEAAAAAWiNIaA67sW4BAAAAAFuT+Ugl2ocPAQAAAABiI7sh70mzPQEAAAAAZDN12p9Yvn8BAAAAAGcDiLbIMyhJAQAAAABt8/uIVY2WAgEAAA"
      + "AAiyKPxPN9klsBAAAAALYiPjOjTlx5AQAAAACB01nnm/WPSgEAAAAAimPEo6QFpHABAAAAAIsz+InajQc9AQAAAACNA2HgOaHlWwEAAAAAkcP/"
      + "jYuICVABAAAAAJKjvHD8lz8IAQAAAACVs7UKCBE8FwEAAAAAE7E2hhLfL3IBAAAAAJrDC6AKZGMvAQAAAACbo4QRBt3JGwEAAAAAnUP/4lWBoA"
      + "QBAAAAAKDjWFFZQVY5AQAAAACms+9EGMRLNQEAAAAAtNN9Ojr1gWUBAAAAALgztRrDbnIDAQAAAAC8I7SEfvjrWwEAAAAAxBNQJtwVFxABAAAA"
      + "AMajx89P9I4HAQAAAADJQ5tIB9LSJwEAAAAAygNhqucznxUBAAAAANbj+XRnLmdNAQAAAAApc3W4UHXhDAEAAAAA2XPFkMLPUHwBAAAAAOFTe4"
      + "4md/g0AQAAAABwA7Tin1YsaQEAAAAA9OMLg1BZ2V8BAAAAAALEqdeD+3Z2AQAAAAAEZMYluDUJEgEAAAAABaRrw3IvuVcBAAAAAAdE3/vIz2Ax"
      + "AQAAAAAKxHX0tvVkBQEAAAAACzRUObe56F8BAAAAAA8U6SPD4uI7AQAAAAATlPV/bsNKSAEAAAAAFBTCRQaBWm0BAAAAABVkEH+PS7ZCAQAAAA"
      + "AZZIuMJ9iUEgEAAAAAG7TsqqhzYlQBAAAAAB4U+E1yjNRJAQAAAAAmpHUV9R2IXAEAAAAANXTFEwtIqEsBAAAAADv0c/yedyUMAQAAAABAtPt5"
      + "ikBBOgEAAAAARtR7PD1qxVsBAAAAAEukQdA+seoeAQAAAABNxJv/8Hq1QQEAAAAAUIRYTnos0BcBAAAAAKZTbV6AZqkTAQAAAABU1PyeUxjnag"
      + "EAAAAAWVRcfZVk1hkBAAAAAF20WTtBsxNXAQAAAABeRAcXahOiEQEAAAAAX5RaFY9jNWEBAAAAAGMUN6OcOtQyAQAAAABl1KBbsD3AfQEAAAAA"
      + "aZSJUHYWk0sBAAAAAGpkuLRrNPZqAQAAAABttA/TgXIdSwEAAAAAbuTFyYTDSncBAAAAAHb0nshKEsssAQAAAACBhAkQyzruQAEAAAAAhFTvcu"
      + "Ih40QBAAAAAIVkBxYGiSJ6AQAAAACK1GT9OzVMIgEAAAAAkNQMF+q0oTsBAAAAAJWUV6WnPrglAQAAAACYVDDZcx2mdgEAAAAAmtQYKDOmoS0B"
      + "AAAAAJBUCEa4UyooAQAAAACdNFeOSWYtOgEAAAAAoMTR912wZyIBAAAAAKF0+aZnKWxxAQAAAACnlK8Co/n0YAEAAAAArQTEhbJx0RcBAAAAAL"
      + "zDm1up0pkzAQAAAAC31BfXKcfffwEAAAAAuGS7VwygtWQBAAAAALm0+H132+phAQAAAAC6hJkumtpsRgEAAAAAwjTm4lmEHTsBAAAAAMYk1hJF"
      + "/n4hAQAAAADHxIGFE39zAAEAAAAAyWT6gVpPNGMBAAAAAMwkIQqpXN0ZAQAAAADWwxcd1FLibgEAAAAA02SbCQaViXkBAAAAANSUHWf8ccxFAQ"
      + "AAAADVxELbem9PbwEAAAAA18ToZMg9VBQBAAAAANy0IDTFJW1/AQAAAADd5IBItcImNAEAAAAA4PSL6pmDw3wBAAAAAOekucwfdmsdAQAAAADv"
      + "9EA3BKhieAEAAAAA+OTb9Ap8WW0BAAAAAPp0s0wWsW4AAQAAAAD7BJZUHThQcAEAAAAA/bRhCXnaQlwBAAAAAP70PlkD+uN2AQAAAAAAZSzmRB"
      + "vHcwEAAAAABBW5CKLNhHgBAAAAAAkFMT0B5E8zAQAAAAAMBSPTE8uNNwEAAAAADkU8ZQqTMGUBAAAAAKdkE2Wmj9cwAQAAAAAWNcsU0ZyKbgEA"
      + "AAAAFyUQjG4v3lgBAAAAABilJsu7xV0JAQAAAAAaNYd8IgfoIwEAAAAAGxVZPD9Me20BAAAAABz11cVxBsQIAQAAAAAjpVs4Gv10HwEAAAAAMV"
      + "VTWVFsvWoBAAAAADO1luENbEhQAQAAAABRRNdLFPmbWwEAAAAAPcXUpIEJgngBAAAAAD4VvA/H5okzAQAAAABCxdV12uiZewEAAAAARaVHM6ys"
      + "3QQBAAAAAEnlI8xAu9gaAQAAAABNRak9Qi72EwEAAAAATgW2B0olym8BAAAAAE8lLAapo1YxAQAAAABR9TZNjffKRQEAAAAAUjWcO3Es/BsBAA"
      + "AAAFnUVw3Q7/NPAQAAAABjxfJQV18YLAEAAAAAapW+KujbK1YBAAAAAGxFGtlWQMARAQAAAAButddTTU0NEAEAAAAAchU9X+A5YXsBAAAAAHhl"
      + "c637iUsnAQAAAACDRX2imemuEQEAAAAAhqXf5udg1DMBAAAAAIeluvklMwl1AQAAAACIZVc30Qp0AQEAAAAAjpWNEGFd8AcBAAAAAJJ1BaZJ3t"
      + "80AQAAAACU5ecxnYtgDwEAAAAAlvUejXjuPiQBAAAAAJxFlEVQCwk8AQAAAACj9fOXE4uSQAEAAAAAqXU6yOEwe1YBAAAAAKz1MEs7u/UUAQAA"
      + "AAC0ZZoCCkf0CQEAAAAAt2Wl29aNjT8BAAAAALvVDXkjmuRSAQAAAAC9ZftTyybhKAEAAAAAwJUu8LU0yC4BAAAAAFmkVQ12gCR2AQAAAADGtU"
      + "a2KroTOwEAAAAAyWWfUojJAz8BAAAAAMyFZE48wA1iAQAAAADPVVB60gaTEgEAAAAA1rXddOuwbF8BAAAAANsFu/45uVtCAQAAAADllTtknKho"
      + "XwEAAAAA5yXfYohKEWABAAAAAOpFRgRmr81XAQAAAAD9hDfGqxbnfQEAAAAA8PV1MyfUGyUBAAAAAPOF0Rdl9sUIAQAAAAD5pTFJsvfhBwEAAA"
      + "AA+VX4pXEl1C4BAAAAAAWGRWbqNOFcAQAAAAAQhgQk5e3AHQEAAAAAEfbwYciR43cBAAAAABi2gY/3XMxTAQAAAAAb1vNxPsH3XgEAAAAAJZZ5"
      + "bIY+sgUBAAAAABHWaEb0OplXAQAAAAA0tvtcTuD+WwEAAAAANWZ/6Js3QFEBAAAAADfm0biwpAV5AQAAAAA8lnc5ILqAYAEAAAAAnBV9tF1JOj"
      + "MBAAAAAEl20VxnpHRMAQAAAAAbdjFajlX/NQEAAAAATsb6GkfbrVABAAAAAE9G67Pr1SAVAQAAAABRVr/+meOHdgEAAAAAUkY+Iw/PgjABAAAA"
      + "AFPmrrOH98JPAQAAAABaptYtBm6lXwEAAAAAXPa3Buw6YzoBAAAAAGJmfhc6avZiAQAAAABlRq+qE6RBIAEAAAAAZ1YkGQANSk8BAAAAAGm26d"
      + "AcTCNvAQAAAABrxs43HYIREgEAAAAAcFbXUHVAnx0BAAAAAHOWbGhsGDYmAQAAAAB2xpAbu5ADEgEAAAAAhdYgu+zfwR8BAAAAAM/FtTlDANpB"
      + "AQAAAACKJpy2IB+FbAEAAAAAjKZiWOmnzS4BAAAAAO71tLasEw5XAQAAAACOptONUTTlGwEAAAAAj2a9qUtT7BkBAAAAAJdWn4CLP0ROAQAAAA"
      + "CZNt43R7I/KQEAAAAAmyY+ysxblwkBAAAAAGuGwcqQGrpoAQAAAACelkZHzdSDegEAAAAAn2YQQhnPJkUBAAAAAKG249GCBNwPAQAAAACkdjV9"
      + "asaMWwEAAAAAp6ZfAO7FfUQBAAAAAKm2F0IpjgFIAQAAAACwNt4NUb11YQEAAAAAuQYDvUkBjU4BAAAAAMy0X1WfacY2AQAAAAC9xqO/IJfxTg"
      + "EAAAAAv9aVWlxVH1cBAAAAAO7l5o4GB/1qAQAAAADPFrUBaFIOcgEAAAAA0bZysn0ZvCsBAAAAANXG+vIxZc07AQAAAADahnsJX0dFCAEAAAAA"
      + "32Z/MIKCqRYBAAAAAKH2iWI9jwQGAQAAAADpppeAdpj4QgEAAAAA71Z8MD9XNiwBAAAAAPD2pOEVnX0pAQAAAAD3lvvVCUmqJQEAAAAA+ta4la"
      + "/q+BUBAAAAAPvmQUkoKq1jAQAAAAD85hY2IplCTQEAAAAA/cbFSAae0QwBAAAAAP4WIRP7mLwQAQAAAAABRzmD4ZhTHwEAAAAAy9ZhQhLCwywB"
      + "AAAAAAsXEPkydgAXAQAAAAAMJwWGHyl2JQEAAAAAD5dOMJJETj0BAAAAABOHmWDMP21fAQAAAAAZx8se+PMebwEAAAAAGhdfSWBfhzwBAAAAAF"
      + "wGLshAd7lcAQAAAAArlw4eer9RYgEAAAAALbcQXk9zE0gBAAAAAA/3YH7RPcEPAQAAAAA7J2vj1fwtEAEAAAAARxcWLSFN8XoBAAAAAEjXBVUh"
      + "/pMzAQAAAABOB9MYSH9vJwEAAAAAUOclDKUJLSIBAAAAAFFnAT7v4t0AAQAAAABSh541nnS9VQEAAAAAVKd2IM4aIVkBAAAAAFf3YKWmUDovAQ"
      + "AAAABadx6o+96SXAEAAAAAW1d4zQwLrlsBAAAAAF9nG9hORA8TAQAAAABm19Ku5tdgQAEAAAAAaAf1vTlxWR4BAAAAAG0HbjeZbLQwAQAAAABv"
      + "B9hVH2kBVwEAAAAAcFdWilz6EyIBAAAAAHKXKisEJX0qAQAAAABz94MfE9uHOQEAAAAA/Mb7B+KjxD0BAAAAAHnHhbexPndaAQAAAAB8V8+/pf"
      + "D7aQEAAAAAUGf5zKgx4kIBAAAAAIL38arHUUxBAQAAAACJxwgkAAXFVgEAAAAAjqcOSJ8YWAUBAAAAAJGHb+THW65NAQAAAACSZ+fEPwIDVAEA"
      + "AAAAmeekBw061W4BAAAAAKXnr2J5LeArAQAAAACqV/lIKGFKfQEAAAAArHcE7B5pJS8BAAAAAK1nsbOVWF8PAQAAAACy9+uDYUrLVgEAAAAAt6"
      + "fHchNZ2xoBAAAAALpHtVRk4P4fAQAAAAC7d+hd9McPdgEAAAAAc0eibjlNmQIBAAAAAL23LRyDd1UbAQAAAADAVxmihtBjOwEAAAAAwceOZan7"
      + "+kQBAAAAAMOX/BKBcJ0eAQAAAADEh+Q5oxC/RgEAAAAAxTedA+Pr7G0BAAAAAM4nmLhaz38VAQAAAADSt1UXVP3TXgEAAAAAcheLPeVuiwwBAA"
      + "AAANrHRP3p+1I6AQAAAADblwTxetsiPgEAAAAA3Ucmp+NY/2QBAAAAANUnWDsuTVlUAQAAAADkx1gSmsQGAQEAAAAAkpeCNuW0+hQBAAAAAOin"
      + "vWj+C4YEAQAAAADr53hbDf4ddgEAAAAA7vdlFbe3cGkBAAAAAPPnykeMx1duAQAAAAD3hwUoFutJEgEAAAAA+XfHDAk6ChABAAAAAAA4UdW/if"
      + "k7AQAAAAASaKy5LGZHKwEAAAAAFTiTLx3TrjcBAAAAABjYp9MDriNkAQAAAAAfSCTacPgXIQEAAAAAIBjrqxSiszEBAAAAACEoVStvfwZzAQAA"
      + "AAAjyN+m6JCcXwEAAAAAKhiLzkE7cR8BAAAAAC5ohvqvY00sAQAAAAA0CPX4kc+7QAEAAAAAS1jgely/vFwBAAAAAFTYRKC9bR5bAQAAAABmx6"
      + "sYkegpIAEAAAAAWdhP4UJuPFcBAAAAAGBok4rzh34yAQAAAABhWBwM0oX9QgEAAAAAZBh4lmsLiFwBAAAAAGf4rfV42Ys/AQAAAABq2OPuMz1K"
      + "LgEAAAAAb2jSF/bp+VIBAAAAAHIoREfE3E5eAQAAAAB82MXcLrpHdQEAAAAAfkjbthIfCmoBAAAAAIFYXmAgaidAAQAAAACEGJe647R1awEAAA"
      + "AAhbijg24G3HABAAAAAHVXNA5TG+lRAQAAAACMGC/75fOEOgEAAAAAjXjZj2Cmgg8BAAAAANuXTffvn9B2AQAAAACamHH+5D9BIQEAAAAAFVjU"
      + "Up5eO3kBAAAAAKT4ZsgNqF9RAQAAAACr6LqVsXRIIAEAAAAArCh5B8zWzwwBAAAAAK8Ige2n06ENAQAAAACzCExS8ZVIXQEAAAAAtogZZlASEF"
      + "cBAAAAALiIzpEYshVvAQAAAAC9aPOwKqtsUgEAAAAAxXjBCjbv63IBAAAAAMbITN6IPSsjAQAAAADNaMqxN84NbQEAAAAA04goDpM+/CIBAAAA"
      + "ANQoUNm08hoyAQAAAADXaG3e6o88NwEAAAAA5Ke3QJU7GX0BAAAAANqIQVuTsDNpAQAAAADhuOfIN0CjFgEAAAAA4ljTRiePtRkBAAAAAOg4wX"
      + "hDGJkkAQAAAADpeF47IZnsQwEAAAAA6pgJOV03MH4BAAAAAAB4RzbgH58RAQAAAADwmCwi+ZO/KQEAAAAA8chgbP/T3FwBAAAAAPMod16MOB8T"
      + "AQAAAACzGCJ64fp4LgEAAAAA+zh5iRMkjwEBAAAAAAGZQKijMXw3AQAAAAAHGbov/psjUgEAAAAAC1lgc0CTMAgBAAAAAAxZ0q4L5attAQAAAA"
      + "CguCElBD3hNgEAAAAAxViylFsjKDEBAAAAABPpx2OzPp8VAQAAAAAV+X3LvYahBQEAAAAAIBneZbxjngsBAAAAAPCYAS+9blUxAQAAAAAnKb30"
      + "SA7VHAEAAAAAKhkuTtL7vGwBAAAAADlJ4BjSUl5gAQAAAABNafXW1YsqJgEAAAAAcIcvm19DUj8BAAAAAFfpegoOI1l0AQAAAABYiW3BhIa5RA"
      + "EAAAAAckhPhsXKJ1sBAAAAAGH5tQ4K4OUcAQAAAAABCQNKpKN8QgEAAAAA2liUxmNmsj8BAAAAAGkpZsfmPyN9AQAAAABqqcreJArtBQEAAAAA"
      + "bMlNMFt8QHUBAAAAAG2pFrxKZmEeAQAAAAB0aZQGnF9lIQEAAAAAdZk2tVcy6BcBAAAAAIO5Msz5W38NAQAAAACHCQW29EGnNQEAAAAAkImrOX"
      + "HAGBABAAAAAJNZ03drEH9IAQAAAACXKbshy5buKQEAAAAAq/iLKMymqRYBAAAAALDJ6KSB4BBRAQAAAACyiVvjz2O5KQEAAAAAtBkxgPRyJyUB"
      + "AAAAAPvYvRtVZDozAQAAAAC5udU+LrjaWQEAAAAAWBnb5LjWHD0BAAAAAMuJKKs0Gtc5AQAAAADReU6ft2HHQgEAAAAA1blD14YpNikBAAAAAN"
      + "YJ8jBO04VGAQAAAADXedazX/1wQQEAAAAAWBlk2QsPhCgBAAAAAOKp/uq7aaA8AQAAAADpibPEJykPKgEAAAAA76kW7oUJ51cBAAAAAMtpsXar"
      + "m6RgAQAAAAD5eak8kYn2GwEAAAAA+mn5WTyigwgBAAAAAP3p5bvb/H1FAQAAAAD/GRv2XN5gQwEAAAAAA/rlBQ1tMhcBAAAAAAUKJ751ggYdAQ"
      + "AAAAAMql7lifDuRgEAAAAAGLpvHIebHywBAAAAACEaAuPGXNp2AQAAAAAk+qKgM0eiDwEAAAAANQq1Gy5KfV0BAAAAAFcJN71SX7Z0AQAAAAA5"
      + "yt5yMeV+RQEAAAAAPrrco29vtiABAAAAAJd5lV0SYfNiAQAAAABJqpj8ZYyVcQEAAAAATJqx/WQvv3IBAAAAAFD6wBNbJWkjAQAAAABSKsomdf"
      + "1zKgEAAAAAVPohRqqui3wBAAAAAFaqpts5axQ0AQAAAABYepk9yFexPgEAAAAAX3p8FYJghicBAAAAAHqaM3oVff4gAQAAAAB+Cu/6YX1VJAEA"
      + "AAAA1Ynt8rp0KgABAAAAAJpaVUcb7uQQAQAAAACemo4lt+0zRgEAAAAAobpEoYpc4gkBAAAAAKn6Vy9TY/l3AQAAAACumtEZpHAnAwEAAAAAsA"
      + "oUO0XEWlQBAAAAALUKIyFOnykUAQAAAAC8eroW+Tv5EAEAAAAAsIrwgx+bE2oBAAAAAMgK07dUoyZeAQAAAABJOtQNgAQ0XwEAAAAA0vr9U1YO"
      + "tQYBAAAAANUKUugeKMoTAQAAAADZSnjyOdmfXAEAAAAA3Xq1rx8fYSIBAAAAAN9qTDin/sQ+AQAAAADh2pIivq6IWgEAAAAA4trPn83qvgQBAA"
      + "AAACQKPvxyxUAhAQAAAADBKlFkVBnqKAEAAAAA7Fqo/zttMnkBAAAAAN+KqPdgBhxRAQAAAADzKjeJDXRjVgEAAAAA/6lvDHvOfksBAAAAAPma"
      + "nmQB8rATAQAAAAD7irflPvt7BgEAAAAA/TqfOxQdAHkBAAAAAP+6+ClB/3NFAQAAAAAAeyO6qOJ9ZgEAAAAA+UoomxIuCVIBAAAAAApLp8PJ42"
      + "E5AQAAAADV+qH70H1UagEAAAAAIAujP4N/XksBAAAAACPr2aJeGB0pAQAAAAAl68JiLg6mJQEAAAAAJgttW2q2tnMBAAAAACl7tS9RVk4tAQAA"
      + "AAAq29BdgW/5GQEAAAAALsvrWpgRgCYBAAAAACor2CD1YeIvAQAAAAAxW7sTV0IUIgEAAAAA8xpKqdlo3hgBAAAAADfrZzIbio4sAQAAAAA6u9"
      + "PZ39c+egEAAAAAQksyUC9v/zEBAAAAAENbVTbu8JsPAQAAAABFCwRD02DAMAEAAAAAS/u05JAKJGkBAAAAAEN7AM840jBWAQAAAABTe4ImtqZD"
      + "BQEAAAAAJYv5/7OrQC4BAAAAAFyrVEATPXk9AQAAAABeG2WVGj66LAEAAAAAaYu5kbhoVwgBAAAAAG77bReVOKwaAQAAAABvK7zg+WtdEQEAAA"
      + "AAdrslh9y9pjkBAAAAAHebv+9LTL93AQAAAAB529PbKW2zdAEAAAAAeiurFapVXzcBAAAAAH37ZS6PGDxfAQAAAAB/CxYZInQ5WQEAAAAAiquI"
      + "tvcdCR8BAAAAAI1rzffcLVRqAQAAAACQm/dxXGQtFAEAAAAAmHt4zlUprQcBAAAAAJr7KY1majggAQAAAACdi/lovrc2KwEAAAAAoOtrKoKwHj"
      + "wBAAAAAKGLLmxnSyA1AQAAAACjW5QXzU6uCQEAAAAArFucjSmeMkwBAAAAAK7L0A3zAFYHAQAAAACxi+8tOzaZZAEAAAAAuNulGgDMiSUBAAAA"
      + "ALrLaden8iIrAQAAAAC7G2KukXQWXQEAAAAAv1s3QDn0l3YBAAAAAMKbHp9elrFlAQAAAADDe97Y9XzzdQEAAAAAxasVMXcZYX0BAAAAAMh7Ca"
      + "HIivk/AQAAAADMez87PWWtbwEAAAAA1ltmbP2MJjEBAAAAAOJbt4LyiCRCAQAAAADla2HuyIBEIAEAAAAA5gvHbkmvpQgBAAAAAOcrBHcmgiFG"
      + "AQAAAADqS4qRYc5gIwEAAAAA7QtNbVK6BgUBAAAAAO8L0qsZ2f9lAQAAAAB526OgaHA/GQEAAAAArFviZh+e2RoBAAAAAPvr0BRSGQgdAQAAAA"
      + "AE/PCDNasJaAEAAAAABjzxPhGAHnYBAAAAAA7s9HYnOg4YAQAAAAAPPMETLV5/bAEAAAAAEdyOkl/tuE8BAAAAABJcMvvWUq5gAQAAAAATfMvj"
      + "eDYyfAEAAAAAG0zRSZWYUhUBAAAAAB9sBwgd6gBjAQAAAAAjPJnnU+O/EgEAAAAAJ3zxAnvNl3ABAAAAACvMP32+EYQrAQAAAAAyzKP8m0MqUw"
      + "EAAAAAP1w0ioeixxMBAAAAAECc3JPnHpZwAQAAAABDbPDoFOA3CQEAAAAAShx5Hoy21VoBAAAAAFDsNSqp1UF9AQAAAABSvNnJeNPRZwEAAAAA"
      + "VKyZSIwbOUIBAAAAAFVcFve6ZyA5AQAAAABfTMzVbyLoNAEAAAAAYgxqzQqSYkkBAAAAAGs8GjfMBXY8AQAAAABszH7eyFmmIwEAAAAAcMzp50"
      + "etvXwBAAAAAHF8a57Y2WcWAQAAAAB5PC5OodWLHQEAAAAAfPx4tDA/AXQBAAAAAICM7OmbaN46AQAAAACBvNnVNVRRYwEAAAAAhUzoGGlj2XUB"
      + "AAAAAIn83DDll9JNAQAAAABS7BlJHS1oBQEAAAAAlZx4O23Gql8BAAAAAJ58ueygGnQrAQAAAACfbC+l7sXMbwEAAAAArKtPBHtsw3kBAAAAAK"
      + "YM04BTkpMbAQAAAACqPAKnd/tkHgEAAAAAsMzT74qUwXwBAAAAALFcBAXGbxsmAQAAAAC2PJtAzDiFegEAAAAAuXwEMRs6kUoBAAAAAI+MYYvQ"
      + "0xEXAQAAAADCvF3/yHpCPwEAAAAAyax5wkmNKHYBAAAAAMqsqRfTLZsmAQAAAADTjD5cRmD8dwEAAAAA24znO+aMDjIBAAAAANz8umgsySF6AQ"
      + "AAAADd/BiVlFndFAEAAAAA3qxr4eHZZQABAAAAAN+MwOZFR0sxAQAAAAB5PEu02iZLMAEAAAAA4ww1FskK7k4BAAAAAOScec0cU84aAQAAAADp"
      + "7HdPqIB+FQEAAAAA8Oy/ILTErScBAAAAAPWs19W4/XsIAQAAAAD5rO0JvRgAVQEAAAAAAl2SD33l33oBAAAAAAPtHxW7YPg5AQAAAAAjDG9FwY"
      + "KAZQEAAAAAlZyL/rPUihkBAAAAAAptFAkWZtURAQAAAAAPXRGQ3IixAwEAAAAAFP363aLPVk8BAAAAABeNiW2P3JInAQAAAAAYfcON0n3OUQEA"
      + "AAAAG5324Tz98CMBAAAAABg9SMgu0DtVAQAAAAAiDXHyJYOWNQEAAAAAJc3zC1G/UG4BAAAAAC+9Xb4GgIVhAQAAAAA3PTC8meWbTQEAAAAAOF"
      + "2g8GY71QMBAAAAALFspFHO3+1lAQAAAABQPfIy1EOmPwEAAAAAVI2SeZO2qEUBAAAAAJ/s7YhsgPwYAQAAAABdvZ9541UyBwEAAAAAY13CeuUI"
      + "ljgBAAAAAGQ9Em6L1ztJAQAAAABmrWxYD5bQFQEAAAAAaD2DKykGa1wBAAAAAAacLc0/0ERiAQAAAABurQBnvkzoTgEAAAAAb/3c9FyuLicBAA"
      + "AAAHJ9tuQ5yihxAQAAAAB43ZVrgBqNWgEAAAAAeu00T25WUjUBAAAAAH7NmNDe/b5aAQAAAACM7YRaoW7sFQEAAAAAkZ31XPZvuhEBAAAAAFA9"
      + "QqMmtasYAQAAAACd7RswrqiyewEAAAAAoP0GYXbljggBAAAAAKENpQLmMGo3AQAAAACpXadS1oY1JwEAAAAAqr2jwfsmC0kBAAAAAMjtqwp7iD"
      + "omAQAAAADLXTAt9sQ8KAEAAAAAzd0xtBmKgAwBAAAAANSd2j9nryFVAQAAAADWfd5ZaxHhGQEAAAAA2C0jd0u5NX4BAAAAAOftmOiTLspwAQAA"
      + "AADqHYWBEdZsYgEAAAAA7A0lUKVPDWwBAAAAAAOtk/BdoXEUAQAAAADv7YyxdjvSKQEAAAAA8N0X8Wt2/n4BAAAAAJ296gleQRc1AQAAAACg7T"
      + "qQUGqeVAEAAAAAXC09ifMEuEQBAAAAAAJeoci3h8kfAQAAAACe2lYkR8jqOgEAAAAADV7o5tcZQEgBAAAAAOc9QYcVsZF9AQAAAAAQ7k858xQj"
      + "TgEAAAAAEr6Bib2bFXkBAAAAAByu8UORnWhzAQAAAABUfW53JjimNAEAAAAA1M06Yt81m0wBAAAAAAFuKTA9qGogAQAAAAAxDmv8EjoTQwEAAA"
      + "AANz4ZN15kLX0BAAAAADk+6xYTzrMDAQAAAAA/XpskZKbWGwEAAAAAQN4u4cnbPQgBAAAAAEEeeMKsIWA/AQAAAABDXrfaZJezFQEAAAAARS50"
      + "8Lo9jxMBAAAAAEdOIa0E2KA+AQAAAABJfjSCzaZwXQEAAAAATu7oUlLYCx0BAAAAAH5NUy4JtS9wAQAAAABXHsScr0GXOgEAAAAAXo6KOSRRAE"
      + "MBAAAAAGFOzTVCf28LAQAAAABoXrkGn1TxLgEAAAAAaT7GWk+zDUoBAAAAAG0uiZ/x7UNfAQAAAABx/mpsjsBGOwEAAAAAd16Y3BUEHVsBAAAA"
      + "AHk+DjkrXMxIAQAAAAB7/o8jgY4bUgEAAAAAf/6Z7KNbGQ4BAAAAAIO+9wqP40NhAQAAAAC2PC/cyhnSRwEAAAAAlN7WyKB1KgIBAAAAAJZ+1e"
      + "BVwM4zAQAAAACXXkNV3yKXfAEAAAAAm56n4Vqlw38BAAAAAJ3eXmCakBd7AQAAAACg/nAl1BI3EgEAAAAApn5lAyy8uEsBAAAAAKkewGLvsrd1"
      + "AQAAAACyHoscRSVICwEAAAAAt85zc3q/2AcBAAAAAMAedbIbafg0AQAAAADELlms8pshOQEAAAAAxD44wGCiknkBAAAAANEew/k0/phoAQAAAA"
      + "DSDr/PgxqsaAEAAAAA1N7FK/IbwmIBAAAAANFeoEKNnOsWAQAAAADfTr/rOSE3JAEAAAAA4e4o4grYzUQBAAAAAGEORJL6tHtuAQAAAADRzpB7"
      + "mVgmJQEAAAAAaS4kUMz7lB4BAAAAAO4eAKkWHVhtAQAAAAD3znnSg3/JBQEAAAAA+f4cK8R/6CoBAAAAAPqe7zNODcZ2AQAAAAD8jgFfXJAqBQ"
      + "EAAAAA/z7bSTH6lgABAAAAAHg9RuN9fNMBAQAAAAAIb14ogYbqeQEAAAAADP9XSgnWajcBAAAAAA5vYxexqPJTAQAAAAASL9P0iRaMRwEAAAAA"
      + "FI9xZS+ycXsBAAAAACPfU9dIPrA1AQAAAAA5XmeigNYaJwEAAAAAJr+FKnSHwAsBAAAAACdPaDfIBQkUAQAAAAAunwwS0BblEgEAAAAAOq80JU"
      + "B8gRIBAAAAADxv2CTM5HYhAQAAAABAz8KxxqyMVwEAAAAA916K42g1xH8BAAAAAEq/UGrvp7R5AQAAAABLv37ufkD1AAEAAAAAOp9AD59rSF4B"
      + "AAAAAFAfAKaZEVk+AQAAAABVn7FzX650HAEAAAAAWJ/Orapei1EBAAAAAFq/dDjfJhERAQAAAABeD4Lxu0JZMAEAAAAAZp9DLW51ihgBAAAAAO"
      + "I+ZCw9zORRAQAAAABqj37gOnqmMwEAAAAAPI+JllT7vDoBAAAAAG+PqWEFHq0JAQAAAABw/4C/y5jBJgEAAAAA4p60TqDOB1kBAAAAAHmPvd1N"
      + "/5BqAQAAAAB7f+xm7Xh/AQEAAAAAhq+CKKGzWWcBAAAAAIz/rYefHx4mAQAAAADR7rWxGbSTAgEAAAAAjx8NIjM1lSEBAAAAAFjPifjjvOM+AQ"
      + "AAAACSbz+/xC5oXwEAAAAAln94GNUS4V4BAAAAAJ+vSXlU0ixzAQAAAAA8L3sYCg+7BwEAAAAApi+SCn0Xsm8BAAAAAKjfgKqG1rl9AQAAAACp"
      + "D3gMUFB3CAEAAAAArD/q2DEaCnsBAAAAAK9fFaZJkk4BAQAAAACyb0VgFxA2DAEAAAAAsx9Br1t6dlUBAAAAALb/spq4kaYsAQAAAAC3/6nmHB"
      + "cbFAEAAAAAub+f6vqeqgEBAAAAALzvMl6Kh6xMAQAAAAC/7wCNc4wwfgEAAAAAwN+lOQ2A+zsBAAAAAMV/w2SAI0FwAQAAAADG/+6euD83OwEA"
      + "AAAAy18UNiUraFcBAAAAAM+/h8I187kkAQAAAADWn4TctOYVDAEAAAAA2u/BfxdT1FEBAAAAANw/n1QMmVoIAQAAAADnT3l5YHL0fwEAAAAA6K"
      + "/8/dhvlREBAAAAAO5PvTdDwu9yAQAAAADvr67PW930AQEAAAAA9t+QKk2yVHoBAAAAAP6PSfiLQq5UAQAAAAA=";

  private static final String KLL_DOUBLES_620 =
      "BQEPAMgACADoAwAAAAAAAMgAAwBiAAAAxAAAAMUAAAAAAAAAAAAAAAAAAAAAOI9AAAAAAAA4j0AAAAAAADCPQAAAAAAAKI9AAAAAAAAgj0AAAA"
      + "AAABiPQAAAAAAAEI9AAAAAAAAIj0AAAAAAAACPQAAAAAAA+I5AAAAAAADwjkAAAAAAAOiOQAAAAAAA4I5AAAAAAADYjkAAAAAAANCOQAAAAAAA"
      + "yI5AAAAAAADAjkAAAAAAALiOQAAAAAAAsI5AAAAAAACojkAAAAAAAKCOQAAAAAAAmI5AAAAAAACQjkAAAAAAAIiOQAAAAAAAgI5AAAAAAAB4jk"
      + "AAAAAAAHCOQAAAAAAAaI5AAAAAAABgjkAAAAAAAFiOQAAAAAAAUI5AAAAAAABIjkAAAAAAAECOQAAAAAAAOI5AAAAAAAAwjkAAAAAAACiOQAAA"
      + "AAAAII5AAAAAAAAYjkAAAAAAABCOQAAAAAAACI5AAAAAAAAAjkAAAAAAAPiNQAAAAAAA8I1AAAAAAADojUAAAAAAAOCNQAAAAAAA2I1AAAAAAA"
      + "DQjUAAAAAAAMiNQAAAAAAAwI1AAAAAAAC4jUAAAAAAALCNQAAAAAAAqI1AAAAAAACgjUAAAAAAAJiNQAAAAAAAkI1AAAAAAACIjUAAAAAAAICN"
      + "QAAAAAAAeI1AAAAAAABwjUAAAAAAAGiNQAAAAAAAYI1AAAAAAABYjUAAAAAAAFCNQAAAAAAASI1AAAAAAABAjUAAAAAAADiNQAAAAAAAMI1AAA"
      + "AAAAAojUAAAAAAACCNQAAAAAAAGI1AAAAAAAAQjUAAAAAAAAiNQAAAAAAAAI1AAAAAAAD4jEAAAAAAAPCMQAAAAAAA6IxAAAAAAADgjEAAAAAA"
      + "ANiMQAAAAAAA0IxAAAAAAADIjEAAAAAAAMCMQAAAAAAAuIxAAAAAAACwjEAAAAAAAKiMQAAAAAAAoIxAAAAAAACYjEAAAAAAAJCMQAAAAAAAiI"
      + "xAAAAAAACAjEAAAAAAAHiMQAAAAAAAcIxAAAAAAABojEAAAAAAAGCMQAAAAAAAWIxAAAAAAABQjEAAAAAAAEiMQAAAAAAAQIxAAAAAAAA4jEAA"
      + "AAAAADCMQAAAAAAAAHtAAAAAAAAACEAAAAAAAAAcQAAAAAAAACZAAAAAAAAALkAAAAAAAAAzQAAAAAAAADdAAAAAAAAAO0AAAAAAAAA/QAAAAA"
      + "AAgEFAAAAAAACAQ0AAAAAAAIBFQAAAAAAAgEdAAAAAAACASUAAAAAAAIBLQAAAAAAAgE1AAAAAAACAT0AAAAAAAMBQQAAAAAAAwFFAAAAAAADA"
      + "UkAAAAAAAMBTQAAAAAAAwFRAAAAAAADAVUAAAAAAAMBWQAAAAAAAwFdAAAAAAADAWEAAAAAAAMBZQAAAAAAAwFpAAAAAAADAW0AAAAAAAMBcQA"
      + "AAAAAAwF1AAAAAAADAXkAAAAAAAMBfQAAAAAAAYGBAAAAAAADgYEAAAAAAAGBhQAAAAAAA4GFAAAAAAABgYkAAAAAAAOBiQAAAAAAAYGNAAAAA"
      + "AADgY0AAAAAAAGBkQAAAAAAA4GRAAAAAAABgZUAAAAAAAOBlQAAAAAAAYGZAAAAAAADgZkAAAAAAAGBnQAAAAAAA4GdAAAAAAABgaEAAAAAAAO"
      + "BoQAAAAAAAYGlAAAAAAADgaUAAAAAAAGBqQAAAAAAA4GpAAAAAAABga0AAAAAAAOBrQAAAAAAAYGxAAAAAAADgbEAAAAAAAGBtQAAAAAAA4G1A"
      + "AAAAAABgbkAAAAAAAOBuQAAAAAAAYG9AAAAAAADgb0AAAAAAADBwQAAAAAAAcHBAAAAAAACwcEAAAAAAAPBwQAAAAAAAMHFAAAAAAABwcUAAAA"
      + "AAALBxQAAAAAAA8HFAAAAAAAAwckAAAAAAAHByQAAAAAAAsHJAAAAAAADwckAAAAAAADBzQAAAAAAAcHNAAAAAAACwc0AAAAAAAPBzQAAAAAAA"
      + "MHRAAAAAAABwdEAAAAAAALB0QAAAAAAA8HRAAAAAAAAwdUAAAAAAAHB1QAAAAAAAsHVAAAAAAADwdUAAAAAAADB2QAAAAAAAcHZAAAAAAACwdk"
      + "AAAAAAAPB2QAAAAAAAMHdAAAAAAABwd0AAAAAAALB3QAAAAAAA8HdAAAAAAAAweEAAAAAAAHB4QAAAAAAAsHhAAAAAAADweEAAAAAAADB5QAAA"
      + "AAAAcHlAAAAAAACweUAAAAAAAPB5QAAAAAAAMHpAAAAAAABwekAAAAAAALB6QAAAAAAA8HpAAAAAAAAge0AAAAAAAGB7QAAAAAAAoHtAAAAAAA"
      + "Dge0AAAAAAACB8QAAAAAAAYHxAAAAAAACgfEAAAAAAAOB8QAAAAAAAIH1AAAAAAABgfUAAAAAAAKB9QAAAAAAA4H1AAAAAAAAgfkAAAAAAAGB+"
      + "QAAAAAAAoH5AAAAAAADgfkAAAAAAACB/QAAAAAAAYH9AAAAAAACgf0AAAAAAAOB/QAAAAAAAEIBAAAAAAAAwgEAAAAAAAFCAQAAAAAAAcIBAAA"
      + "AAAACQgEAAAAAAALCAQAAAAAAA0IBAAAAAAADwgEAAAAAAABCBQAAAAAAAMIFAAAAAAABQgUAAAAAAAHCBQAAAAAAAkIFAAAAAAACwgUAAAAAA"
      + "ANCBQAAAAAAA8IFAAAAAAAAQgkAAAAAAADCCQAAAAAAAUIJAAAAAAABwgkAAAAAAAJCCQAAAAAAAsIJAAAAAAADQgkAAAAAAAPCCQAAAAAAAEI"
      + "NAAAAAAAAwg0AAAAAAAFCDQAAAAAAAcINAAAAAAACQg0AAAAAAALCDQAAAAAAA0INAAAAAAADwg0AAAAAAABCEQAAAAAAAMIRAAAAAAABQhEAA"
      + "AAAAAHCEQAAAAAAAkIRAAAAAAACwhEAAAAAAANCEQAAAAAAA8IRAAAAAAAAQhUAAAAAAADCFQAAAAAAAUIVAAAAAAABwhUAAAAAAAJCFQAAAAA"
      + "AAsIVAAAAAAADQhUAAAAAAAPCFQAAAAAAAEIZAAAAAAAAwhkAAAAAAAFCGQAAAAAAAcIZAAAAAAACQhkAAAAAAALCGQAAAAAAA0IZAAAAAAADw"
      + "hkAAAAAAABCHQAAAAAAAMIdAAAAAAABYh0AAAAAAAHiHQAAAAAAAmIdAAAAAAAC4h0AAAAAAANiHQAAAAAAA+IdAAAAAAAAYiEAAAAAAADiIQA"
      + "AAAAAAWIhAAAAAAAB4iEAAAAAAAJiIQAAAAAAAuIhAAAAAAADYiEAAAAAAAPiIQAAAAAAAGIlAAAAAAAA4iUAAAAAAAFiJQAAAAAAAeIlAAAAA"
      + "AACYiUAAAAAAALiJQAAAAAAA2IlAAAAAAAD4iUAAAAAAABiKQAAAAAAAOIpAAAAAAABYikAAAAAAAHiKQAAAAAAAmIpAAAAAAAC4ikAAAAAAAN"
      + "iKQAAAAAAA+IpAAAAAAAAYi0AAAAAAADiLQAAAAAAAWItAAAAAAAB4i0AAAAAAAJiLQAAAAAAAuItAAAAAAADYi0AAAAAAAPiLQAAAAAA"
      + "AGIxA";

  private static final String CPC_620 =
      "CAEQDAAOzJO/AwAAqQAAAAAAAIDpf61AukbLwgc7j0DFwrQAo3IWU1I/O7Fs5pj30w05ooCjuSCv+qlPTMUZ/YSP8XJoRlRtm1Zo0zi8QGbquA"
      + "tDJJ2ZqXwsxUyanrnuEF8YFbMrKnd94+Z2iBmrn0ZcUJXEZ8dqxQsbUzSxMbaGgghJ9D1/12xUeOPmRQ3UOeslUYJeO/Y8ITE8F8pt2RgIRCd9"
      + "SlxJop/nCMqKymds6z1fum0e+mUU0anDeD0nyKtariSL39evohMifJRRjHAUixgxml109au5sbgCZkrF6PUQJyy8JpbAIire8rvDv+wZKbMTNT"
      + "MdqzdSraPB1F6z8j6TnLSusYRjrGhG5Ykniio2cofwhKRTYvbESpWWE8f8e+QDUzk5RMP8IbpNYv25Y3q1Q5SIU0KCiRKjb0rnvWiysfYp+dFa"
      + "3HxOOTM1mlVVTVQz8PYMxGm78tRR+NC+NTVlO1VJVi2mkSdbWhHJdCz0aXxEGz1Fqp+a6VeyF+XGvd2YJ8iqq9YnFZ29Ue5fmWkZ0Q/fGrYYJf"
      + "SmzXRUJZ3Thr6bmsIF025KYGb7jrXbzUydOZvhd+x82xsrldy1tfHvZaSiRC0zM4g+GzwhiEctxmJ8V5WmiYVXiNksedLJldp4K0lejtLqyE53"
      + "P4PIrc1ME4hsSRA+Z3T8RD9mSjbU7U6BkCYsI6VpCilgjcP58mY1Tm0FCwh1N/KSUrWEkKRFl401PTLvnzn/RNmsqZRMnO6EVmfIeYJm79dxV3"
      + "PSJtrcNjqx7BOo4/5IckW2wxAiVowpGhOmBRqtNtQWX9vaWqvuw2kzcrulaqM1OFOMVOBStTTkC7UnzpKLWSWaWSMbfQ+zxNvUm0nrzZpH2r7j"
      + "SDujrWui5UgKCdNd94kmdLmyuhBVf2ObtYnqdZw2eq68mdoGvVFdGG3rI7RlGAAA";

  private static final String FREQ_LONGS_620 =
      "BAEKCAQAAAAKAAAAAAAAAOgDAAAAAAAAAAAAAAAAAABkAAAAAAAAAGQAAAAAAAAAZAAAAAAAAABkAAAAAAAAAGQAAAAAAAAAZAAAAAAAAABkAA"
      + "AAAAAAAGQAAAAAAAAAZAAAAAAAAABkAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAFAAAAAAAAAAQAAAAAAAAAAgAAAAAAAAAIAAAAAAAAAAkAAAAA"
      + "AAAAAQAAAAAAAAAHAAAAAAAAAAMAAAAAAAAA";

  private static final String FREQ_STRINGS_620 =
      "BAEKCAQAAAAKAAAAAAAAAOgDAAAAAAAAAAAAAAAAAABkAAAAAAAAAGQAAAAAAAAAZAAAAAAAAABkAAAAAAAAAGQAAAAAAAAAZAAAAAAAAABkAA"
      + "AAAAAAAGQAAAAAAAAAZAAAAAAAAABkAAAAAAAAAAIAAABzOAIAAABzNgIAAABzNAIAAABzMAIAAABzMgIAAABzNQIAAABzNwIAAABzOQIAAABz"
      + "MQIAAABzMw==";

  private static byte[] decode(String base64) {
    return Base64.getDecoder().decode(base64);
  }

  /// Wraps the fixture in a ByteBuffer with a non-zero position to mimic the query-path
  /// `deserializeIntermediateResult` flow reading from a sliced DataTable buffer.
  private static ByteBuffer offsetBuffer(byte[] bytes) {
    ByteBuffer byteBuffer = ByteBuffer.allocate(bytes.length + 5);
    byteBuffer.position(5);
    byteBuffer.put(bytes);
    byteBuffer.position(5);
    return byteBuffer;
  }

  @Test
  public void testThetaSketch620() {
    for (String fixture : new String[]{THETA_ORDERED_620, THETA_UNORDERED_620}) {
      byte[] bytes = decode(fixture);
      assertEquals(ObjectSerDeUtils.DATA_SKETCH_THETA_SER_DE.deserialize(bytes).getEstimate(), 1000.0);
      assertEquals(ObjectSerDeUtils.DATA_SKETCH_THETA_SER_DE.deserialize(ByteBuffer.wrap(bytes)).getEstimate(),
          1000.0);
      assertEquals(ObjectSerDeUtils.DATA_SKETCH_THETA_SER_DE.deserialize(offsetBuffer(bytes)).getEstimate(), 1000.0);
      assertEquals(CustomSerDeUtils.DATA_SKETCH_THETA_SER_DE.deserialize(bytes).getEstimate(), 1000.0);
    }
  }

  @Test
  public void testIntegerTupleSketch620() {
    byte[] bytes = decode(INT_TUPLE_620);
    TupleSketch<IntegerSummary> sketch = ObjectSerDeUtils.DATA_SKETCH_INT_TUPLE_SER_DE.deserialize(bytes);
    assertEquals(sketch.getEstimate(), 1000.0);
    assertEquals(ObjectSerDeUtils.DATA_SKETCH_INT_TUPLE_SER_DE.deserialize(offsetBuffer(bytes)).getEstimate(),
        1000.0);
    assertEquals(CustomSerDeUtils.DATA_SKETCH_INT_TUPLE_SER_DE.deserialize(bytes).getEstimate(), 1000.0);
  }

  @Test
  public void testKllDoublesSketch620() {
    byte[] bytes = decode(KLL_DOUBLES_620);
    KllDoublesSketch sketch = ObjectSerDeUtils.KLL_SKETCH_SER_DE.deserialize(bytes);
    assertEquals(sketch.getN(), 1000);
    assertEquals(sketch.getMinItem(), 0.0);
    assertEquals(sketch.getMaxItem(), 999.0);
    assertEquals(ObjectSerDeUtils.KLL_SKETCH_SER_DE.deserialize(offsetBuffer(bytes)).getN(), 1000);
  }

  @Test
  public void testCpcSketch620() {
    byte[] bytes = decode(CPC_620);
    // Estimate computed by datasketches-java 6.2.0 from this exact serialized image; the ICON estimator is
    // deterministic, so the value must be stable across library versions.
    CpcSketch sketch = ObjectSerDeUtils.DATA_SKETCH_CPC_SER_DE.deserialize(bytes);
    assertEquals(sketch.getEstimate(), 999.378789508911, 1.0);
    assertEquals(ObjectSerDeUtils.DATA_SKETCH_CPC_SER_DE.deserialize(offsetBuffer(bytes)).getEstimate(),
        999.378789508911, 1.0);
    assertEquals(CustomSerDeUtils.DATA_SKETCH_CPC_SER_DE.deserialize(bytes).getEstimate(), 999.378789508911, 1.0);
  }

  @Test
  public void testFrequentLongsSketch620() {
    byte[] bytes = decode(FREQ_LONGS_620);
    FrequentLongsSketch sketch = ObjectSerDeUtils.FREQUENT_LONGS_SKETCH_SER_DE.deserialize(bytes);
    for (long item = 0; item < 10; item++) {
      assertEquals(sketch.getEstimate(item), 100);
    }
    assertEquals(ObjectSerDeUtils.FREQUENT_LONGS_SKETCH_SER_DE.deserialize(offsetBuffer(bytes)).getEstimate(0L), 100);
  }

  @Test
  public void testFrequentStringsSketch620() {
    byte[] bytes = decode(FREQ_STRINGS_620);
    FrequentItemsSketch<String> sketch = ObjectSerDeUtils.FREQUENT_STRINGS_SKETCH_SER_DE.deserialize(bytes);
    for (int item = 0; item < 10; item++) {
      assertEquals(sketch.getEstimate("s" + item), 100);
    }
    assertEquals(ObjectSerDeUtils.FREQUENT_STRINGS_SKETCH_SER_DE.deserialize(offsetBuffer(bytes)).getEstimate("s0"),
        100);
  }
}
