#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM razorpay/onggi:maven-java8 AS thirdeye_build_env

LABEL MAINTAINER=observability@razorpay.com

RUN echo "Trying to build Thirdeye"

ENV TE_HOME=/opt/thirdeye
ENV TE_BUILD_DIR=/opt/thirdeye-build

COPY . ${TE_BUILD_DIR}

RUN apk update \
    && apk add --update vim wget curl git automake bison flex g++ boost-dev libevent-dev openssl-dev libtool make pkgconfig nodejs npm

RUN npm install -g phantomjs --unsafe-perm --ignore-scripts

RUN cd ${TE_BUILD_DIR}/thirdeye  \
    && cd thirdeye-frontend \
    && mvn clean install -X -DskipTests || exit 1 \
    && cd .. \
    && mvn clean install -X -DskipTests || exit 1 \
    && mkdir -p ${TE_HOME}/config/default \
    && mkdir -p ${TE_HOME}/bin \
    && cp -rp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/config/* ${TE_HOME}/config/default/. \
    ## Override local config files for docker-compose
    && cp -rp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/config-templates/dev/data-sources/* ${TE_HOME}/config/default/data-sources/ \
    && cp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/config-templates/dev/persistence.yml ${TE_HOME}/config/default/ \
    ## Copy the jmx config file
    && cp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/config.yml ${TE_HOME}/config/default/jmx_config.yml \
    ## Copy Create Schema for docker-compose run
    && cp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/config-templates/dev/create-schema.sql ${TE_HOME}/config/default/ \
    && rm ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/target/thirdeye-pinot-*-sources.jar \
    && cp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/target/thirdeye-pinot-*.jar ${TE_HOME}/bin/thirdeye-pinot.jar \
    && cp ${TE_BUILD_DIR}/thirdeye/thirdeye-pinot/jmx_prometheus_javaagent-0.13.0.jar ${TE_HOME}/bin/jmx_prometheus_javaagent-0.13.0.jar \
    && cp ${TE_BUILD_DIR}/docker/images/pinot-thirdeye/bin/* ${TE_HOME}/bin/ \
    && rm -rf ${TE_BUILD_DIR}

FROM openjdk:14-alpine

LABEL MAINTAINER=dev@pinot.apache.org

ENV TE_HOME=/opt/thirdeye

COPY --from=thirdeye_build_env ${TE_HOME} ${TE_HOME}

#RUN apk add bzip2=1.0.6-r7 libjpeg-turbo=1.5.3-r6 libtasn1=4.14-r0 libx11=1.6.12-r0 musl=1.1.20-r5 \
#    && apk add --update

EXPOSE 1426 1427
WORKDIR ${TE_HOME}

ENTRYPOINT ["./bin/start-thirdeye.sh"]
