/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
const test =  {"OFFLINE":{"tableName":"baseballStats_OFFLINE","tableType":"OFFLINE","segmentsConfig":{"schemaName":"baseball","replication":"1","segmentPushType":"APPEND","retentionTimeUnit":null,"retentionTimeValue":null,"segmentPushFrequency":null,"replicasPerPartition":null,"timeColumnName":null,"timeType":null,"segmentAssignmentStrategy":"BalanceNumSegmentAssignmentStrategy","replicaGroupStrategyConfig":null,"completionConfig":null},"tenants":{"broker":"DefaultTenant","server":"DefaultTenant","tagOverrideConfig":null},"tableIndexConfig":{"streamConfigs":{},"segmentPartitionConfig":null,"segmentFormatVersion":null,"nullHandlingEnabled":false,"invertedIndexColumns":["playerID","teamID"],"autoGeneratedInvertedIndex":false,"createInvertedIndexDuringSegmentGeneration":false,"sortedColumn":[],"bloomFilterColumns":[],"loadMode":"HEAP","columnMinMaxValueGeneratorMode":null,"noDictionaryColumns":null,"noDictionaryConfig":null,"onHeapDictionaryColumns":null,"starTreeIndexConfigs":null,"aggregateMetrics":false,"varLengthDictionaryColumns":null},"metadata":{"customConfigs":{}}}}

function test1() {
    for(const prop in test) {
        const value = test[prop];
        console.log(value);
        console.log(typeof  value === "object");
    }
}

function populateNode(data, i, name) {
    const node = {};
    node.id = i;
    node.name = name;
    node.children =  [];
    for (const prop in data) {
        const value = data[prop];
        if(typeof value === 'object') {
            node.children.push(JSON.stringify(populateNode(value,++i, prop)));
        } else {
            const child = {id: ++i, name: prop + ':'  +  value};
            node.children.push(child);
        }
    }
    return node;
}


function testing() {
    let value = null;
    console.log(value? value='test':value = 'ee');
}

testing();