/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.segment.spi;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Set;
import javax.annotation.Nullable;
import org.apache.pinot.segment.spi.index.IndexType;
import org.apache.pinot.segment.spi.partition.PartitionFunction;
import org.apache.pinot.spi.annotations.InterfaceAudience;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.FieldSpec.DataType;
import org.apache.pinot.spi.data.FieldSpec.FieldType;


/// The `ColumnMetadata` class holds the column level management information and data statistics.
@InterfaceAudience.Private
@SuppressWarnings("rawtypes")
public interface ColumnMetadata {
  int UNAVAILABLE = -1;

  FieldSpec getFieldSpec();

  default String getColumnName() {
    return getFieldSpec().getName();
  }

  default FieldType getFieldType() {
    return getFieldSpec().getFieldType();
  }

  default DataType getDataType() {
    return getFieldSpec().getDataType();
  }

  default boolean isSingleValue() {
    return getFieldSpec().isSingleValueField();
  }

  /// Returns the total number of documents (rows).
  int getTotalDocs();

  /// Returns the cardinality of the column.
  /// NOTE: When a realtime segment has no-dictionary columns, the cardinality for those columns will be set to
  /// [Constants#UNKNOWN_CARDINALITY].
  int getCardinality();

  /// Returns `true` when the column is dictionary-encoded, `false` otherwise.
  @JsonProperty("hasDictionary")
  boolean hasDictionary();

  /// Returns `true` when all values in a SV column are sorted in ascending order, `false` otherwise.
  boolean isSorted();

  /// Returns the minimum value, or `null` if the value is unavailable.
  @Nullable
  Comparable getMinValue();

  /// Returns the maximum value, or `null` if the value is unavailable.
  @Nullable
  Comparable getMaxValue();

  /// Returns `true` when both min and max value are invalid, and there is no need to regenerate them.
  boolean isMinMaxValueInvalid();

  /// Returns the minimum serialized byte length across all elements. For fixed-width types, returns the fixed size.
  int getLengthOfShortestElement();

  /// Returns the maximum serialized byte length across all elements. For fixed-width types, returns the fixed size.
  int getLengthOfLongestElement();

  /// Returns `true` when all elements of a STRING column contain only ASCII characters.
  boolean isAscii();

  /// Returns the total number of entries.
  /// - For SV columns, equals the number of rows
  /// - For MV columns, sums the number of elements across all rows
  int getTotalNumberOfEntries();

  /// Returns the maximum number of elements within a single MV value, or `0` for SV columns.
  int getMaxNumberOfMultiValues();

  /// For dictionary-encoded columns, returns the bits required for each element, [#UNAVAILABLE] otherwise.
  int getBitsPerElement();

  /// Returns the [PartitionFunction] for the column.
  @Nullable
  PartitionFunction getPartitionFunction();

  /// Returns the partitions within which the values exist.
  @Nullable
  Set<Integer> getPartitions();

  /// Returns `true` when the column is auto-generated by the default column handler.
  boolean isAutoGenerated();

  /// Returns the total number of indexes for the column.
  @JsonIgnore
  int getNumIndexes();

  /// Returns the type of the index at the given position.
  short getIndexType(int position);

  /// Returns the size of the index at the given position.
  long getIndexSize(int position);

  /// Returns the size of the given index type if exists, [#UNAVAILABLE] otherwise.
  long getIndexSizeFor(IndexType type);

  @JsonIgnore
  @Deprecated(since = "1.6.0", forRemoval = true)
  default int getColumnMaxLength() {
    return getLengthOfLongestElement();
  }
}
