/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.segment.spi;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.pinot.segment.spi.index.IndexType;
import org.apache.pinot.spi.annotations.InterfaceAudience;
import org.apache.pinot.spi.config.table.FieldConfig.EncodingType;


/// The `ColumnMetadata` class holds the column level management information and data statistics.
@InterfaceAudience.Private
public interface ColumnMetadata extends ColumnShape {
  int UNAVAILABLE = -1;

  /// Returns `true` when the column has a dictionary, `false` otherwise.
  @JsonProperty("hasDictionary")
  boolean hasDictionary();

  /// Returns the forward-index encoding for this column. The value is persisted under
  /// [V1Constants.MetadataKeys.Column#FORWARD_INDEX_ENCODING]; for old segments that lack the key, implementations
  /// derive it from [#hasDictionary()].
  EncodingType getForwardIndexEncoding();

  /// Returns `true` when both min and max value are invalid, and there is no need to regenerate them.
  boolean isMinMaxValueInvalid();

  /// For dictionary-encoded columns, returns the bits required for each element, [#UNAVAILABLE] otherwise.
  int getBitsPerElement();

  /// Returns `true` when the column is auto-generated by the default column handler.
  boolean isAutoGenerated();

  /// Returns the total number of indexes for the column.
  @JsonIgnore
  int getNumIndexes();

  /// Returns the type of the index at the given position.
  short getIndexType(int position);

  /// Returns the size of the index at the given position.
  long getIndexSize(int position);

  /// Returns the size of the given index type if exists, [#UNAVAILABLE] otherwise.
  long getIndexSizeFor(IndexType type);

  @JsonIgnore
  @Deprecated(since = "1.6.0", forRemoval = true)
  default int getColumnMaxLength() {
    return getLengthOfLongestElement();
  }
}
