frameworks:
    identity:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.NullPipeline

    metricRelated:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.MetricMappingPipeline

    metricAnalysis:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.MetricAnalysisPipeline

    metricBreakdown:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.MetricBreakdownPipeline

    metricComponentAnalysis:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.MetricComponentAnalysisPipeline
          properties:
              excludeDimensions: ["environment", "continent"]
              parallelism: 5
              k: 5

    eventExperiment:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.ThirdEyeEventsPipeline
          properties:
            strategy: COMPOUND
            k: 500
            eventType: LIX

    eventHoliday:
        - outputName: METRIC_RELATED
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.MetricAnalysisPipeline

        - outputName: OUTPUT
          inputNames: [INPUT, METRIC_RELATED]
          className: org.apache.pinot.thirdeye.rootcause.impl.ThirdEyeEventsPipeline
          properties:
              strategy: COMPOUND
              k: 500
              eventType: HOLIDAY

    eventCustom:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.ThirdEyeEventsPipeline
          properties:
              strategy: COMPOUND
              k: 500
              eventType: CUSTOM

    eventAnomaly:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.AnomalyEventsPipeline
          properties:
              strategyClass: org.apache.pinot.thirdeye.rootcause.impl.AnomalyEventsPipeline$TimeRangeScoreStrategy
              strategyProperties:
                  type: HYPERBOLA
              k: 500

    eventIssue:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.EmptyPipeline

    eventChange:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.ThirdEyeEventsPipeline
          properties:
            strategy: COMPOUND
            k: 500
            eventType: CM

    eventDeployment:
        - outputName: OUTPUT
          inputNames: [INPUT]
          className: org.apache.pinot.thirdeye.rootcause.impl.ThirdEyeEventsPipeline
          properties:
            strategy: COMPOUND
            k: 500
            eventType: INFORMED

    eventAC:
      - outputName: OUTPUT
        inputNames: [INPUT]
        className: org.apache.pinot.thirdeye.rootcause.impl.EmptyPipeline
