/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.sql.ddl.reverse;

import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import javax.annotation.Nullable;
import org.apache.pinot.spi.config.table.IndexingConfig;
import org.apache.pinot.spi.config.table.SegmentsValidationAndRetentionConfig;
import org.apache.pinot.spi.config.table.TableConfig;
import org.apache.pinot.spi.config.table.TableCustomConfig;
import org.apache.pinot.spi.config.table.TableTaskConfig;
import org.apache.pinot.spi.config.table.TenantConfig;
import org.apache.pinot.spi.utils.JsonUtils;
import org.apache.pinot.sql.ddl.compile.PropertyMapping;


/// Inverse of `PropertyMapping`: walks a [TableConfig] and emits a property map
/// suitable for the `PROPERTIES (...)` clause in canonical DDL. The map is sorted
/// lexicographically so canonical output is deterministic.
///
/// Routing rules mirror `PropertyMapping`:
/// - Promoted fields (timeColumnName, replication, brokerTenant, …) emit under their
/// known property keys.
/// - Stream configs are emitted verbatim using their original key (preserving the
/// `stream.`/`realtime.` prefix).
/// - Task configs are emitted as `task.<type>.<key> = <value>`.
/// - Table custom-config entries are emitted verbatim.
/// - Complex nested configs (ingestionConfig, upsertConfig, routingConfig, etc.) that have no
/// first-class clause yet are emitted as JSON-string property values under the same key
/// used by Pinot's own JSON serialization. The forward `PropertyMapping` parses
/// these blobs back into the corresponding TableConfig fields.
///
/// Defaults are skipped where doing so doesn't lose information (e.g. `loadMode=MMAP`
/// or `replication=1`) so canonical output stays compact.
///
/// **Coverage scope (Slice 2):** this extractor covers the TableConfig fields most users
/// configure today plus a JSON-blob fallback for the major nested configs. Several long-tail
/// fields are intentionally not yet emitted; when they are set to non-default values, canonical
/// DDL emission fails fast instead of returning a replay script that would silently lose them:
/// - SegmentsValidationAndRetentionConfig: `segmentPushType`/`segmentPushFrequency`
/// (deprecated; use IngestionConfig), `replacedSegmentsRetentionPeriod`,
/// `lineageEntryCleanupRetentionPeriod`, `minimizeDataMovement`,
/// `untrackedSegmentsDeletion*` fields.
/// - IndexingConfig: `rangeIndexVersion`, `bloomFilterConfigs`,
/// `noDictionaryConfig`, `enableDefaultStarTree`,
/// `enableDynamicStarTreeCreation`, `columnMajorSegmentBuilderEnabled`,
/// `skipSegmentPreprocess`, `optimizeNoDictStatsCollection`,
/// `optimizeDictionary*`, `noDictionarySize/CardinalityRatioThreshold`,
/// `segmentNameGeneratorType`, `columnMinMaxValueGeneratorMode`,
/// `autoGeneratedInvertedIndex`, `createInvertedIndexDuringSegmentGeneration`.
/// Later slices can replace these guards with explicit property handlers as the grammar expands.
public final class PropertyExtractor {

  /// Property keys whose values are JSON-serialized blobs of the corresponding nested config.
  static final String KEY_INGESTION_CONFIG = "ingestionConfig";
  static final String KEY_UPSERT_CONFIG = "upsertConfig";
  static final String KEY_DEDUP_CONFIG = "dedupConfig";
  static final String KEY_ROUTING_CONFIG = "routingConfig";
  static final String KEY_QUERY_CONFIG = "queryConfig";
  static final String KEY_QUOTA_CONFIG = "quotaConfig";
  static final String KEY_TIER_CONFIGS = "tierConfigs";
  static final String KEY_TUNER_CONFIGS = "tunerConfigs";
  static final String KEY_FIELD_CONFIGS = "fieldConfigs";
  static final String KEY_INSTANCE_ASSIGNMENT = "instanceAssignmentConfigMap";
  static final String KEY_INSTANCE_PARTITIONS = "instancePartitionsMap";
  static final String KEY_SEGMENT_ASSIGNMENT = "segmentAssignmentConfigMap";
  static final String KEY_DIMENSION_TABLE_CONFIG = "dimensionTableConfig";
  static final String KEY_TAG_OVERRIDE_CONFIG = "tagOverrideConfig";
  static final String KEY_REPLICA_GROUP_STRATEGY = "replicaGroupStrategyConfig";
  static final String KEY_COMPLETION_CONFIG = "completionConfig";
  static final String KEY_STAR_TREE_INDEX_CONFIGS = "starTreeIndexConfigs";
  static final String KEY_MULTI_COLUMN_TEXT_INDEX = "multiColumnTextIndexConfig";
  static final String KEY_JSON_INDEX_CONFIGS = "jsonIndexConfigs";
  static final String KEY_SEGMENT_PARTITION_CONFIG = "segmentPartitionConfig";
  static final String KEY_TIER_OVERWRITES = "tierOverwrites";
  static final String KEY_TABLE_SAMPLERS = "tableSamplers";

  private PropertyExtractor() {
  }

  /// Extracts a deterministic, lexicographically-sorted property map from `config`.
  public static Map<String, String> extract(TableConfig config) {
    rejectUnsupportedFields(config);
    Map<String, String> props = new TreeMap<>();
    extractValidation(config.getValidationConfig(), props);
    extractTenant(config.getTenantConfig(), props);
    extractIndexing(config.getIndexingConfig(), props);
    extractTask(config.getTaskConfig(), props);
    extractCustom(config.getCustomConfig(), props);
    extractTopLevel(config, props);
    extractNestedAsJsonBlobs(config, props);
    return props;
  }

  private static void rejectUnsupportedFields(TableConfig config) {
    rejectUnsupportedValidation(config.getValidationConfig());
    rejectUnsupportedIndexing(config.getIndexingConfig());
  }

  private static void rejectUnsupportedValidation(
      @Nullable SegmentsValidationAndRetentionConfig validationConfig) {
    if (validationConfig == null) {
      return;
    }
    rejectIfPresent("segmentsConfig.replacedSegmentsRetentionPeriod",
        validationConfig.getReplacedSegmentsRetentionPeriod());
    rejectIfPresent("segmentsConfig.lineageEntryCleanupRetentionPeriod",
        validationConfig.getLineageEntryCleanupRetentionPeriod());
    rejectIfPresent("segmentsConfig.segmentPushFrequency",
        validationConfig.getSegmentPushFrequency());
    if (validationConfig.getSegmentPushType() != null
        && !"APPEND".equalsIgnoreCase(validationConfig.getSegmentPushType())) {
      rejectUnsupported("segmentsConfig.segmentPushType");
    }
    if (validationConfig.isMinimizeDataMovement()) {
      rejectUnsupported("segmentsConfig.minimizeDataMovement");
    }
    rejectIfPresent("segmentsConfig.untrackedSegmentsDeletionBatchSize",
        validationConfig.getUntrackedSegmentsDeletionBatchSize());
    rejectIfPresent("segmentsConfig.untrackedSegmentsRetentionTimeUnit",
        validationConfig.getUntrackedSegmentsRetentionTimeUnit());
    rejectIfPresent("segmentsConfig.untrackedSegmentsRetentionTimeValue",
        validationConfig.getUntrackedSegmentsRetentionTimeValue());
  }

  private static void rejectUnsupportedIndexing(@Nullable IndexingConfig indexingConfig) {
    if (indexingConfig == null) {
      return;
    }
    IndexingConfig defaultIndexingConfig = new IndexingConfig();
    if (indexingConfig.getRangeIndexVersion() != defaultIndexingConfig.getRangeIndexVersion()) {
      rejectUnsupported("tableIndexConfig.rangeIndexVersion");
    }
    rejectIfNotEmpty("tableIndexConfig.bloomFilterConfigs",
        indexingConfig.getBloomFilterConfigs());
    rejectIfNotEmpty("tableIndexConfig.noDictionaryConfig",
        indexingConfig.getNoDictionaryConfig());
    if (indexingConfig.isEnableDefaultStarTree()) {
      rejectUnsupported("tableIndexConfig.enableDefaultStarTree");
    }
    if (indexingConfig.isEnableDynamicStarTreeCreation()) {
      rejectUnsupported("tableIndexConfig.enableDynamicStarTreeCreation");
    }
    if (!indexingConfig.isColumnMajorSegmentBuilderEnabled()) {
      rejectUnsupported("tableIndexConfig.columnMajorSegmentBuilderEnabled");
    }
    if (indexingConfig.isSkipSegmentPreprocess()) {
      rejectUnsupported("tableIndexConfig.skipSegmentPreprocess");
    }
    if (indexingConfig.isOptimizeNoDictStatsCollection()) {
      rejectUnsupported("tableIndexConfig.optimizeNoDictStatsCollection");
    }
    if (indexingConfig.isOptimizeDictionary()) {
      rejectUnsupported("tableIndexConfig.optimizeDictionary");
    }
    if (indexingConfig.isOptimizeDictionaryForMetrics()) {
      rejectUnsupported("tableIndexConfig.optimizeDictionaryForMetrics");
    }
    if (indexingConfig.isOptimizeDictionaryType()) {
      rejectUnsupported("tableIndexConfig.optimizeDictionaryType");
    }
    double noDictionarySizeRatioThreshold = indexingConfig.getNoDictionarySizeRatioThreshold();
    if (Double.compare(noDictionarySizeRatioThreshold, 0.0d) != 0
        && Double.compare(noDictionarySizeRatioThreshold,
            IndexingConfig.DEFAULT_NO_DICTIONARY_SIZE_RATIO_THRESHOLD) != 0) {
      rejectUnsupported("tableIndexConfig.noDictionarySizeRatioThreshold");
    }
    Double cardinalityRatioThreshold = indexingConfig.getNoDictionaryCardinalityRatioThreshold();
    if (cardinalityRatioThreshold != null && Double.compare(cardinalityRatioThreshold, 0.0d) != 0) {
      rejectUnsupported("tableIndexConfig.noDictionaryCardinalityRatioThreshold");
    }
    rejectIfPresent("tableIndexConfig.segmentNameGeneratorType",
        indexingConfig.getSegmentNameGeneratorType());
    rejectIfPresent("tableIndexConfig.columnMinMaxValueGeneratorMode",
        indexingConfig.getColumnMinMaxValueGeneratorMode());
    if (indexingConfig.isAutoGeneratedInvertedIndex()) {
      rejectUnsupported("tableIndexConfig.autoGeneratedInvertedIndex");
    }
    if (indexingConfig.isCreateInvertedIndexDuringSegmentGeneration()) {
      rejectUnsupported("tableIndexConfig.createInvertedIndexDuringSegmentGeneration");
    }
  }

  private static void rejectIfPresent(String field, @Nullable String value) {
    if (value != null && !value.isEmpty()) {
      rejectUnsupported(field);
    }
  }

  private static void rejectIfNotEmpty(String field, @Nullable Object value) {
    if (value instanceof Collection && !((Collection<?>) value).isEmpty()) {
      rejectUnsupported(field);
    }
    if (value instanceof Map && !((Map<?, ?>) value).isEmpty()) {
      rejectUnsupported(field);
    }
  }

  private static void rejectUnsupported(String field) {
    throw new IllegalArgumentException("SHOW CREATE TABLE cannot emit field '" + field
        + "' in canonical DDL yet; replaying the emitted DDL would silently drop that setting. "
        + "Use the JSON table config API for this table until the DDL grammar supports it.");
  }

  private static void extractValidation(@Nullable SegmentsValidationAndRetentionConfig v,
      Map<String, String> props) {
    if (v == null) {
      return;
    }
    putIfPresent(props, "timeColumnName", v.getTimeColumnName());
    if (v.getTimeType() != null) {
      props.put("timeType", v.getTimeType().name());
    }
    putIfPresent(props, "retentionTimeUnit", v.getRetentionTimeUnit());
    putIfPresent(props, "retentionTimeValue", v.getRetentionTimeValue());
    // replication defaults to "1"; emit when explicitly different to keep canonical compact.
    String replication = v.getReplication();
    if (replication != null && !"1".equals(replication)) {
      props.put("replication", replication);
    }
    putIfPresent(props, "replicasPerPartition", v.getReplicasPerPartition());
    putIfPresent(props, "peerSegmentDownloadScheme", v.getPeerSegmentDownloadScheme());
    putIfPresent(props, "crypterClassName", v.getCrypterClassName());
    putIfPresent(props, "deletedSegmentsRetentionPeriod",
        skipDefault(v.getDeletedSegmentsRetentionPeriod(), "7d"));
    putJsonIfPresent(props, KEY_REPLICA_GROUP_STRATEGY, v.getReplicaGroupStrategyConfig());
    putJsonIfPresent(props, KEY_COMPLETION_CONFIG, v.getCompletionConfig());
  }

  private static void extractTenant(@Nullable TenantConfig t, Map<String, String> props) {
    if (t == null) {
      return;
    }
    putIfPresent(props, "brokerTenant", t.getBroker());
    putIfPresent(props, "serverTenant", t.getServer());
    putJsonIfPresent(props, KEY_TAG_OVERRIDE_CONFIG, t.getTagOverrideConfig());
  }

  private static void extractIndexing(@Nullable IndexingConfig i, Map<String, String> props) {
    if (i == null) {
      return;
    }
    // loadMode defaults to MMAP.
    String loadMode = i.getLoadMode();
    if (loadMode != null && !"MMAP".equalsIgnoreCase(loadMode)) {
      props.put("loadMode", loadMode);
    }
    putIfPresent(props, "segmentVersion", i.getSegmentFormatVersion());
    // Emit all sort columns as CSV. TableConfigBuilder.setSortedColumn only accepts a single
    // string so PropertyMapping restores only the first column on re-parse; the full list is
    // preserved in canonical DDL so the value is not silently dropped.
    putCsvIfPresent(props, "sortedColumn", i.getSortedColumn(), false);
    putCsvIfPresent(props, "invertedIndexColumns", i.getInvertedIndexColumns(), false);
    putCsvIfPresent(props, "noDictionaryColumns", i.getNoDictionaryColumns(), false);
    putCsvIfPresent(props, "onHeapDictionaryColumns", i.getOnHeapDictionaryColumns(), false);
    putCsvIfPresent(props, "varLengthDictionaryColumns", i.getVarLengthDictionaryColumns(), false);
    putCsvIfPresent(props, "bloomFilterColumns", i.getBloomFilterColumns(), false);
    putCsvIfPresent(props, "rangeIndexColumns", i.getRangeIndexColumns(), false);
    putCsvIfPresent(props, "jsonIndexColumns", i.getJsonIndexColumns(), false);
    if (i.isNullHandlingEnabled()) {
      props.put("nullHandlingEnabled", "true");
    }
    if (i.isAggregateMetrics()) {
      props.put("aggregateMetrics", "true");
    }
    // Stream configs are routed verbatim with their original keys (stream.* / realtime.*).
    Map<String, String> streamConfigs = i.getStreamConfigs();
    if (streamConfigs != null) {
      props.putAll(streamConfigs);
    }
    putJsonIfPresent(props, KEY_SEGMENT_PARTITION_CONFIG, i.getSegmentPartitionConfig());
    putJsonIfPresent(props, KEY_STAR_TREE_INDEX_CONFIGS, i.getStarTreeIndexConfigs());
    putJsonIfPresent(props, KEY_MULTI_COLUMN_TEXT_INDEX, i.getMultiColumnTextIndexConfig());
    putJsonIfPresent(props, KEY_JSON_INDEX_CONFIGS, i.getJsonIndexConfigs());
    putJsonIfPresent(props, KEY_TIER_OVERWRITES, i.getTierOverwrites());
  }

  private static void extractTask(@Nullable TableTaskConfig t, Map<String, String> props) {
    if (t == null || t.getTaskTypeConfigsMap() == null) {
      return;
    }
    for (Map.Entry<String, Map<String, String>> taskEntry : t.getTaskTypeConfigsMap().entrySet()) {
      String taskType = taskEntry.getKey();
      for (Map.Entry<String, String> kv : taskEntry.getValue().entrySet()) {
        props.put("task." + taskType + "." + kv.getKey(), kv.getValue());
      }
    }
  }

  private static void extractCustom(@Nullable TableCustomConfig c, Map<String, String> props) {
    if (c == null || c.getCustomConfigs() == null) {
      return;
    }
    // Custom configs are emitted verbatim and round-trip via the property fall-through case in
    // PropertyMapping. We refuse keys that would shadow a promoted scalar or a JSON-blob key:
    // emitting them would cause re-parse to either misroute the value to the wrong TableConfig
    // field (silent corruption) or fail JSON deserialization. The caller can rename the
    // colliding key to dodge the conflict.
    for (Map.Entry<String, String> e : c.getCustomConfigs().entrySet()) {
      String key = e.getKey();
      String lower = key.toLowerCase(Locale.ROOT);
      if (PropertyMapping.isReservedRoundTripKey(lower)) {
        throw new IllegalArgumentException("TableCustomConfig key '" + key
            + "' collides with a reserved DDL property name (promoted scalar or JSON blob); "
            + "rename the custom-config entry so canonical DDL emission is unambiguous.");
      }
      props.put(key, e.getValue());
    }
  }

  private static void extractTopLevel(TableConfig config, Map<String, String> props) {
    if (config.isDimTable()) {
      props.put("isDimTable", "true");
    }
    putIfPresent(props, "description", config.getDescription());
    List<String> tags = config.getTags();
    if (tags != null && !tags.isEmpty()) {
      rejectCommaBearingValues("tags", tags);
      props.put("tags", String.join(",", tags));
    }
  }

  private static void extractNestedAsJsonBlobs(TableConfig config, Map<String, String> props) {
    putJsonIfPresent(props, KEY_INGESTION_CONFIG, config.getIngestionConfig());
    putJsonIfPresent(props, KEY_UPSERT_CONFIG, config.getUpsertConfig());
    putJsonIfPresent(props, KEY_DEDUP_CONFIG, config.getDedupConfig());
    putJsonIfPresent(props, KEY_DIMENSION_TABLE_CONFIG, config.getDimensionTableConfig());
    putJsonIfPresent(props, KEY_ROUTING_CONFIG, config.getRoutingConfig());
    putJsonIfPresent(props, KEY_QUERY_CONFIG, config.getQueryConfig());
    putJsonIfPresent(props, KEY_QUOTA_CONFIG, config.getQuotaConfig());
    putJsonIfPresent(props, KEY_TIER_CONFIGS, config.getTierConfigsList());
    putJsonIfPresent(props, KEY_TUNER_CONFIGS, config.getTunerConfigsList());
    putJsonIfPresent(props, KEY_FIELD_CONFIGS, config.getFieldConfigList());
    putJsonIfPresent(props, KEY_INSTANCE_ASSIGNMENT, config.getInstanceAssignmentConfigMap());
    putJsonIfPresent(props, KEY_INSTANCE_PARTITIONS, config.getInstancePartitionsMap());
    putJsonIfPresent(props, KEY_SEGMENT_ASSIGNMENT, config.getSegmentAssignmentConfigMap());
    putJsonIfPresent(props, KEY_TABLE_SAMPLERS, config.getTableSamplers());
  }

  // ---------------------------------------------------------------------------------------------

  private static void putIfPresent(Map<String, String> props, String key, @Nullable String value) {
    if (value != null && !value.isEmpty()) {
      props.put(key, value);
    }
  }

  private static void putCsvIfPresent(Map<String, String> props, String key,
      @Nullable List<String> list, boolean firstOnly) {
    if (list == null || list.isEmpty()) {
      return;
    }
    if (firstOnly) {
      rejectCommaBearingValues(key, list);
      props.put(key, list.get(0));
    } else {
      rejectCommaBearingValues(key, list);
      props.put(key, String.join(",", list));
    }
  }

  private static void rejectCommaBearingValues(String key, List<String> list) {
    for (String value : list) {
      if (value != null && value.contains(",")) {
        throw new IllegalArgumentException("SHOW CREATE TABLE cannot emit property '" + key
            + "' as comma-separated DDL because value '" + value + "' contains a comma; "
            + "replaying the emitted DDL would split it into multiple values. Use the JSON "
            + "table config API for this table until the DDL grammar supports escaped CSV values.");
      }
    }
  }

  private static void putJsonIfPresent(Map<String, String> props, String key,
      @Nullable Object obj) {
    if (obj == null) {
      return;
    }
    if (obj instanceof Collection && ((Collection<?>) obj).isEmpty()) {
      return;
    }
    if (obj instanceof Map && ((Map<?, ?>) obj).isEmpty()) {
      return;
    }
    try {
      props.put(key, JsonUtils.objectToString(obj));
    } catch (Exception e) {
      // Defensive: any field we can't serialize can't round-trip; log and skip rather than
      // crash the SHOW CREATE TABLE call.
      throw new IllegalStateException(
          "Failed to serialize TableConfig field '" + key + "' to JSON for canonical DDL emission",
          e);
    }
  }

  @Nullable
  private static String skipDefault(@Nullable String value, String defaultValue) {
    return value == null || defaultValue.equals(value) ? null : value;
  }
}
