<div class="table-responsive">
					<table class="table table-bordered analysis-table">
						<thead>
							<tr>
								<th>8p</th>
								<th>9p</th>
								<th>10p</th>
								<th>11p</th>
								<th>12p</th>
								<th>1a</th>
								<th>2a</th>
								<th>3a</th>
								<th>4a</th>
								<th>5a</th>
								<th>6a</th>
								<th>7a</th>
								<th>8a</th>
								<th>9a</th>
								<th>10a</th>
								<th>11a</th>
								<th>12p</th>
								<th>1p</th>
								<th>2p</th>
								<th>3p</th>
								<th>4p</th>
								<th>5p</th>
								<th>6p</th>
								<th>7p</th>
								<th>8p</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>8p</td>
								<td>+20%</td>
								<td>-50%</td>
								<td>11%</td>
								<td>12%</td>
								<td>1%</td>
								<td>2%</td>
								<td>3%</td>
								<td>4%</td>
								<td>5%</td>
								<td>6%</td>
								<td>7%</td>
								<td>8%</td>
								<td>9%</td>
								<td>10%</td>
								<td>11%</td>
								<td>12%</td>
								<td>1%</td>
								<td>2%</td>
								<td>3%</td>
								<td>4%</td>
								<td>5%</td>
								<td>6%</td>
								<td>7%</td>
								<td>8%</td>
							</tr>
						</tbody>
					</table>
				</div>