/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.perf.aggregation;

import java.nio.ByteBuffer;
import org.apache.pinot.segment.local.utils.TDigestUtils;

/// Creates deterministic legacy TDigest inputs for benchmarks.
final class TDigestBenchmarkUtils {

  private TDigestBenchmarkUtils() {
  }

  /// Creates a deterministic verbose TDigest encoding from sorted raw values.
  ///
  /// The endpoint values remain singleton centroids, matching the TDigest boundary invariant. This layout is used as
  /// a fixed-layout control for benchmarks that otherwise consume the current accumulator encoding.
  /// The bounded bucket-mean calculation differs from the former sum/weight calculation. Comparisons across that
  /// change must reuse the same generated bytes; regenerating FIXED_VERBOSE inputs on each revision changes the input.
  static byte[] createFixedVerboseBytes(double[] sortedValues, double compression) {
    if (sortedValues.length < 2) {
      throw new IllegalArgumentException("Fixed verbose benchmark input requires at least two values");
    }
    int numCentroids = Math.min(sortedValues.length, Math.max(2, (int) Math.ceil(compression * 1.28)));
    ByteBuffer buffer = ByteBuffer.allocate(
        TDigestUtils.VERBOSE_HEADER_SIZE + numCentroids * TDigestUtils.VERBOSE_CENTROID_SIZE);
    buffer.putInt(TDigestUtils.VERBOSE_ENCODING);
    buffer.putDouble(sortedValues[0]);
    buffer.putDouble(sortedValues[sortedValues.length - 1]);
    buffer.putDouble(compression);
    buffer.putInt(numCentroids);
    for (int centroidId = 0; centroidId < numCentroids; centroidId++) {
      int start;
      int end;
      if (centroidId == 0) {
        start = 0;
        end = 1;
      } else if (centroidId == numCentroids - 1) {
        start = sortedValues.length - 1;
        end = sortedValues.length;
      } else {
        int numInteriorCentroids = numCentroids - 2;
        int numInteriorValues = sortedValues.length - 2;
        start = 1 + (centroidId - 1) * numInteriorValues / numInteriorCentroids;
        end = 1 + centroidId * numInteriorValues / numInteriorCentroids;
      }
      double mean = sortedValues[start];
      for (int valueId = start + 1; valueId < end; valueId++) {
        double fraction = 1.0 / (valueId - start + 1);
        double value = sortedValues[valueId];
        mean = Math.copySign(1.0, mean) == Math.copySign(1.0, value)
            ? mean + (value - mean) * fraction
            : mean * (1.0 - fraction) + value * fraction;
      }
      // Rounding must not move a bucket mean beyond its observed range or invert adjacent duplicate buckets.
      mean = Math.max(sortedValues[start], Math.min(sortedValues[end - 1], mean));
      buffer.putDouble(end - start);
      buffer.putDouble(mean);
    }
    return buffer.array();
  }
}
