#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: examples
  namespace: pinot-quickstart
data:
  airlineStats_realtime_table_config.json: |-
    {
      "tableName": "airlineStats",
      "tableType": "REALTIME",
      "segmentsConfig": {
        "timeColumnName": "DaysSinceEpoch",
        "timeType": "DAYS",
        "retentionTimeUnit": "DAYS",
        "retentionTimeValue": "3650",
        "segmentPushType": "APPEND",
        "segmentAssignmentStrategy": "BalanceNumSegmentAssignmentStrategy",
        "schemaName": "airlineStats",
        "replication": "1",
        "replicasPerPartition": "1"
      },
      "tenants": {},
      "tableIndexConfig": {
        "loadMode": "MMAP",
        "streamConfigs": {
          "streamType": "kafka",
          "stream.kafka.consumer.type": "simple",
          "stream.kafka.topic.name": "flights-realtime",
          "stream.kafka.decoder.class.name": "org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder",
          "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
          "stream.kafka.hlc.zk.connect.string": "kafka-zookeeper:2181",
          "stream.kafka.zk.broker.url": "kafka-zookeeper:2181",
          "stream.kafka.broker.list": "kafka:9092",
          "realtime.segment.flush.threshold.time": "3600000",
          "realtime.segment.flush.threshold.size": "50000",
          "stream.kafka.consumer.prop.auto.offset.reset": "smallest"
        }
      },
      "metadata": {
        "customConfigs": {}
      }
    }

  airlineStatsAvro_realtime_table_config.json: |-
    {
      "tableName": "airlineStatsAvro",
      "tableType": "REALTIME",
      "segmentsConfig": {
        "timeColumnName": "DaysSinceEpoch",
        "timeType": "DAYS",
        "retentionTimeUnit": "DAYS",
        "retentionTimeValue": "3650",
        "segmentPushType": "APPEND",
        "segmentAssignmentStrategy": "BalanceNumSegmentAssignmentStrategy",
        "schemaName": "airlineStats",
        "replication": "1",
        "replicasPerPartition": "1"
      },
      "tenants": {},
      "tableIndexConfig": {
        "loadMode": "MMAP",
        "streamConfigs": {
          "streamType": "kafka",
          "stream.kafka.consumer.type": "simple",
          "stream.kafka.topic.name": "flights-realtime-avro",
          "stream.kafka.decoder.class.name": "org.apache.pinot.core.realtime.stream.SimpleAvroMessageDecoder",
          "stream.kafka.decoder.prop.schema": "{\"type\":\"record\",\"name\":\"Flight\",\"namespace\":\"pinot\",\"fields\":[{\"name\":\"DaysSinceEpoch\",\"type\":[\"int\"]},{\"name\":\"Year\",\"type\":[\"int\"]},{\"name\":\"Quarter\",\"type\":[\"int\"]},{\"name\":\"Month\",\"type\":[\"int\"]},{\"name\":\"DayofMonth\",\"type\":[\"int\"]},{\"name\":\"DayOfWeek\",\"type\":[\"int\"]},{\"name\":\"FlightDate\",\"type\":[\"string\"]},{\"name\":\"UniqueCarrier\",\"type\":[\"string\"]},{\"name\":\"AirlineID\",\"type\":[\"int\"]},{\"name\":\"Carrier\",\"type\":[\"string\"]},{\"name\":\"TailNum\",\"type\":[\"string\",\"null\"]},{\"name\":\"FlightNum\",\"type\":[\"int\"]},{\"name\":\"OriginAirportID\",\"type\":[\"int\"]},{\"name\":\"OriginAirportSeqID\",\"type\":[\"int\"]},{\"name\":\"OriginCityMarketID\",\"type\":[\"int\"]},{\"name\":\"Origin\",\"type\":[\"string\"]},{\"name\":\"OriginCityName\",\"type\":[\"string\"]},{\"name\":\"OriginState\",\"type\":[\"string\"]},{\"name\":\"OriginStateFips\",\"type\":[\"int\"]},{\"name\":\"OriginStateName\",\"type\":[\"string\"]},{\"name\":\"OriginWac\",\"type\":[\"int\"]},{\"name\":\"DestAirportID\",\"type\":[\"int\"]},{\"name\":\"DestAirportSeqID\",\"type\":[\"int\"]},{\"name\":\"DestCityMarketID\",\"type\":[\"int\"]},{\"name\":\"Dest\",\"type\":[\"string\"]},{\"name\":\"DestCityName\",\"type\":[\"string\"]},{\"name\":\"DestState\",\"type\":[\"string\"]},{\"name\":\"DestStateFips\",\"type\":[\"int\"]},{\"name\":\"DestStateName\",\"type\":[\"string\"]},{\"name\":\"DestWac\",\"type\":[\"int\"]},{\"name\":\"CRSDepTime\",\"type\":[\"int\"]},{\"name\":\"DepTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"DepDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"DepDelayMinutes\",\"type\":[\"int\",\"null\"]},{\"name\":\"DepDel15\",\"type\":[\"int\",\"null\"]},{\"name\":\"DepartureDelayGroups\",\"type\":[\"int\",\"null\"]},{\"name\":\"DepTimeBlk\",\"type\":[\"string\"]},{\"name\":\"TaxiOut\",\"type\":[\"int\",\"null\"]},{\"name\":\"WheelsOff\",\"type\":[\"int\",\"null\"]},{\"name\":\"WheelsOn\",\"type\":[\"int\",\"null\"]},{\"name\":\"TaxiIn\",\"type\":[\"int\",\"null\"]},{\"name\":\"CRSArrTime\",\"type\":[\"int\"]},{\"name\":\"ArrTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"ArrDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"ArrDelayMinutes\",\"type\":[\"int\",\"null\"]},{\"name\":\"ArrDel15\",\"type\":[\"int\",\"null\"]},{\"name\":\"ArrivalDelayGroups\",\"type\":[\"int\",\"null\"]},{\"name\":\"ArrTimeBlk\",\"type\":[\"string\"]},{\"name\":\"Cancelled\",\"type\":[\"int\"]},{\"name\":\"CancellationCode\",\"type\":[\"string\",\"null\"]},{\"name\":\"Diverted\",\"type\":[\"int\"]},{\"name\":\"CRSElapsedTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"ActualElapsedTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"AirTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"Flights\",\"type\":[\"int\"]},{\"name\":\"Distance\",\"type\":[\"int\"]},{\"name\":\"DistanceGroup\",\"type\":[\"int\"]},{\"name\":\"CarrierDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"WeatherDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"NASDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"SecurityDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"LateAircraftDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"FirstDepTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"TotalAddGTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"LongestAddGTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"DivAirportLandings\",\"type\":[\"int\"]},{\"name\":\"DivReachedDest\",\"type\":[\"int\",\"null\"]},{\"name\":\"DivActualElapsedTime\",\"type\":[\"int\",\"null\"]},{\"name\":\"DivArrDelay\",\"type\":[\"int\",\"null\"]},{\"name\":\"DivDistance\",\"type\":[\"int\",\"null\"]},{\"name\":\"DivAirports\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"DivAirportIDs\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"DivAirportSeqIDs\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"DivWheelsOns\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"DivTotalGTimes\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"DivLongestGTimes\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"DivWheelsOffs\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"DivTailNums\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"RandomAirports\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}",
          "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
          "stream.kafka.hlc.zk.connect.string": "kafka-zookeeper:2181",
          "stream.kafka.zk.broker.url": "kafka-zookeeper:2181",
          "stream.kafka.broker.list": "kafka:9092",
          "realtime.segment.flush.threshold.time": "3600000",
          "realtime.segment.flush.threshold.size": "50000",
          "stream.kafka.consumer.prop.auto.offset.reset": "smallest"
        }
      },
      "metadata": {
        "customConfigs": {}
      }
    }

  airlineStats_schema.json: |-
    {
      "metricFieldSpecs": [
      ],
      "dimensionFieldSpecs": [
        {
          "dataType": "INT",
          "name": "ActualElapsedTime"
        },
        {
          "dataType": "INT",
          "name": "AirTime"
        },
        {
          "dataType": "INT",
          "name": "AirlineID"
        },
        {
          "dataType": "INT",
          "name": "ArrDel15"
        },
        {
          "dataType": "INT",
          "name": "ArrDelay"
        },
        {
          "dataType": "INT",
          "name": "ArrDelayMinutes"
        },
        {
          "dataType": "INT",
          "name": "ArrTime"
        },
        {
          "dataType": "STRING",
          "name": "ArrTimeBlk"
        },
        {
          "dataType": "INT",
          "name": "ArrivalDelayGroups"
        },
        {
          "dataType": "INT",
          "name": "CRSArrTime"
        },
        {
          "dataType": "INT",
          "name": "CRSDepTime"
        },
        {
          "dataType": "INT",
          "name": "CRSElapsedTime"
        },
        {
          "dataType": "STRING",
          "name": "CancellationCode"
        },
        {
          "dataType": "INT",
          "name": "Cancelled"
        },
        {
          "dataType": "STRING",
          "name": "Carrier"
        },
        {
          "dataType": "INT",
          "name": "CarrierDelay"
        },
        {
          "dataType": "INT",
          "name": "DayOfWeek"
        },
        {
          "dataType": "INT",
          "name": "DayofMonth"
        },
        {
          "dataType": "INT",
          "name": "DepDel15"
        },
        {
          "dataType": "INT",
          "name": "DepDelay"
        },
        {
          "dataType": "INT",
          "name": "DepDelayMinutes"
        },
        {
          "dataType": "INT",
          "name": "DepTime"
        },
        {
          "dataType": "STRING",
          "name": "DepTimeBlk"
        },
        {
          "dataType": "INT",
          "name": "DepartureDelayGroups"
        },
        {
          "dataType": "STRING",
          "name": "Dest"
        },
        {
          "dataType": "INT",
          "name": "DestAirportID"
        },
        {
          "dataType": "INT",
          "name": "DestAirportSeqID"
        },
        {
          "dataType": "INT",
          "name": "DestCityMarketID"
        },
        {
          "dataType": "STRING",
          "name": "DestCityName"
        },
        {
          "dataType": "STRING",
          "name": "DestState"
        },
        {
          "dataType": "INT",
          "name": "DestStateFips"
        },
        {
          "dataType": "STRING",
          "name": "DestStateName"
        },
        {
          "dataType": "INT",
          "name": "DestWac"
        },
        {
          "dataType": "INT",
          "name": "Distance"
        },
        {
          "dataType": "INT",
          "name": "DistanceGroup"
        },
        {
          "dataType": "INT",
          "name": "DivActualElapsedTime"
        },
        {
          "dataType": "INT",
          "name": "DivAirportIDs",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "DivAirportLandings"
        },
        {
          "dataType": "INT",
          "name": "DivAirportSeqIDs",
          "singleValueField": false
        },
        {
          "dataType": "STRING",
          "name": "DivAirports",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "DivArrDelay"
        },
        {
          "dataType": "INT",
          "name": "DivDistance"
        },
        {
          "dataType": "INT",
          "name": "DivLongestGTimes",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "DivReachedDest"
        },
        {
          "dataType": "STRING",
          "name": "DivTailNums",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "DivTotalGTimes",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "DivWheelsOffs",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "DivWheelsOns",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "Diverted"
        },
        {
          "dataType": "INT",
          "name": "FirstDepTime"
        },
        {
          "dataType": "STRING",
          "name": "FlightDate"
        },
        {
          "dataType": "INT",
          "name": "FlightNum"
        },
        {
          "dataType": "INT",
          "name": "Flights"
        },
        {
          "dataType": "INT",
          "name": "LateAircraftDelay"
        },
        {
          "dataType": "INT",
          "name": "LongestAddGTime"
        },
        {
          "dataType": "INT",
          "name": "Month"
        },
        {
          "dataType": "INT",
          "name": "NASDelay"
        },
        {
          "dataType": "STRING",
          "name": "Origin"
        },
        {
          "dataType": "INT",
          "name": "OriginAirportID"
        },
        {
          "dataType": "INT",
          "name": "OriginAirportSeqID"
        },
        {
          "dataType": "INT",
          "name": "OriginCityMarketID"
        },
        {
          "dataType": "STRING",
          "name": "OriginCityName"
        },
        {
          "dataType": "STRING",
          "name": "OriginState"
        },
        {
          "dataType": "INT",
          "name": "OriginStateFips"
        },
        {
          "dataType": "STRING",
          "name": "OriginStateName"
        },
        {
          "dataType": "INT",
          "name": "OriginWac"
        },
        {
          "dataType": "INT",
          "name": "Quarter"
        },
        {
          "dataType": "STRING",
          "name": "RandomAirports",
          "singleValueField": false
        },
        {
          "dataType": "INT",
          "name": "SecurityDelay"
        },
        {
          "dataType": "STRING",
          "name": "TailNum"
        },
        {
          "dataType": "INT",
          "name": "TaxiIn"
        },
        {
          "dataType": "INT",
          "name": "TaxiOut"
        },
        {
          "dataType": "INT",
          "name": "Year"
        },
        {
          "dataType": "INT",
          "name": "WheelsOn"
        },
        {
          "dataType": "INT",
          "name": "WheelsOff"
        },
        {
          "dataType": "INT",
          "name": "WeatherDelay"
        },
        {
          "dataType": "STRING",
          "name": "UniqueCarrier"
        },
        {
          "dataType": "INT",
          "name": "TotalAddGTime"
        },
        {
          "dataType": "INT",
          "name": "DaysSinceEpoch"
        }

      ],
      "timeFieldSpec": {
        "incomingGranularitySpec": {
          "dataType": "INT",
          "timeType": "DAYS",
          "name": "DaysSinceEpoch"
        },
        "outgoingGranularitySpec": {
          "dataType": "LONG",
          "timeType": "SECONDS",
          "name": "SecondsSinceEpoch"
        }
      },
      "schemaName": "airlineStats"
    }

---
apiVersion: batch/v1
kind: Job
metadata:
  name: pinot-realtime-quickstart-pinot-table-creation
  namespace: pinot-quickstart
spec:
  template:
    spec:
      containers:
        - name: pinot-add-example-realtime-table-json
          image: apachepinot/pinot:0.3.0-SNAPSHOT
          args: [ "AddTable", "-schemaFile", "/var/pinot/examples/airlineStats_schema.json", "-tableConfigFile", "/var/pinot/examples/airlineStats_realtime_table_config.json", "-controllerHost", "pinot-controller", "-controllerPort", "9000", "-exec" ]
          env:
            - name: JAVA_OPTS
              value: "-Xms4G -Xmx4G -Dpinot.admin.system.exit=true"
          volumeMounts:
            - name: examples
              mountPath: /var/pinot/examples
        - name: pinot-add-example-realtime-table-avro
          image: apachepinot/pinot:0.3.0-SNAPSHOT
          args: [ "AddTable", "-schemaFile", "/var/pinot/examples/airlineStats_schema.json", "-tableConfigFile", "/var/pinot/examples/airlineStatsAvro_realtime_table_config.json", "-controllerHost", "pinot-controller", "-controllerPort", "9000", "-exec" ]
          env:
            - name: JAVA_OPTS
              value: "-Xms4G -Xmx4G -Dpinot.admin.system.exit=true"
          volumeMounts:
            - name: examples
              mountPath: /var/pinot/examples
      restartPolicy: OnFailure
      volumes:
        - name: examples
          configMap:
            name: examples
  backoffLimit: 100
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pinot-realtime-quickstart-load-data-into-kafka
  namespace: pinot-quickstart
spec:
  template:
    spec:
      containers:
        - name: loading-json-data-to-kafka
          image: apachepinot/pinot:0.3.0-SNAPSHOT
          args: [ "StreamAvroIntoKafka", "-avroFile", "examples/stream/airlineStats/sample_data/airlineStats_data.avro", "-kafkaTopic", "flights-realtime", "-kafkaBrokerList", "kafka:9092", "-zkAddress", "kafka-zookeeper:2181" ]
        - name: loading-avro-data-to-kafka
          image: apachepinot/pinot:0.3.0-SNAPSHOT
          args: [ "StreamAvroIntoKafka", "-avroFile", "examples/stream/airlineStats/sample_data/airlineStats_data.avro", "-kafkaTopic", "flights-realtime-avro", "-kafkaBrokerList", "kafka:9092", "-zkAddress", "kafka-zookeeper:2181", "-outputFormat", "avro" ]
      restartPolicy: OnFailure
  backoffLimit: 3


