#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-worker-etc
data:
  config.properties: |-
    coordinator=false
    http-server.http.port={{ .Values.worker.port }}
    query.max-memory={{ .Values.worker.query.maxMemory }}
    query.max-memory-per-node={{ .Values.worker.query.maxMemoryPerNode }}
    query.max-total-memory-per-node={{ .Values.worker.query.maxTotalMemoryPerNode }}
    discovery.uri={{ .Values.worker.discovery.uri }}

  jvm.config:
{{ toYaml .Values.worker.jvm | indent 4 }}

  log.properties:
{{ toYaml .Values.worker.log | indent 4 }}

  node.properties: |-
    node.environment={{ .Values.worker.node.environment }}
    {{- if .Values.worker.node.id }}
    node.id={{ .Values.worker.node.id }}
    {{ end }}
    node.data-dir={{ .Values.worker.node.dataDir }}
