/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.integration.tests.legacy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.File;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.commons.io.FileUtils;
import org.apache.pinot.integration.tests.BaseClusterIntegrationTest;
import org.apache.pinot.segment.local.segment.index.loader.invertedindex.LegacyRawValueInvertedIndexCleanup;
import org.apache.pinot.segment.local.segment.store.SegmentLocalFSDirectory;
import org.apache.pinot.segment.spi.ColumnMetadata;
import org.apache.pinot.segment.spi.creator.SegmentVersion;
import org.apache.pinot.segment.spi.index.StandardIndexes;
import org.apache.pinot.segment.spi.index.metadata.SegmentMetadataImpl;
import org.apache.pinot.segment.spi.memory.PinotDataBuffer;
import org.apache.pinot.segment.spi.store.SegmentDirectory;
import org.apache.pinot.spi.config.table.FieldConfig;
import org.apache.pinot.spi.config.table.TableConfig;
import org.apache.pinot.spi.config.table.TableType;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.Schema;
import org.apache.pinot.spi.utils.JsonUtils;
import org.apache.pinot.spi.utils.ReadMode;
import org.apache.pinot.spi.utils.builder.TableConfigBuilder;
import org.apache.pinot.spi.utils.builder.TableNameBuilder;
import org.apache.pinot.util.TestUtils;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertFalse;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertTrue;


/// Backward-compatibility integration test for the legacy raw-value inverted index migration path.
///
/// **Two fixtures** are loaded into two separate tables, exercising both on-disk segment formats:
///
/// - `legacy/legacyRawInverted_OFFLINE_0.tar.gz` (v1) — each index is its own file (`category.bitmap.inv`,
///   `category.sv.raw.fwd`). Generated by an OLDER Pinot codebase that still contains the now-deleted
///   `RawValueBitmapInvertedIndexCreator` (commit `669ef058e0`, see header for the one-line patch needed to
///   permit STRING).
/// - `legacy/legacyRawInverted_v3_OFFLINE_0.tar.gz` (v3) — all indexes packed into a single `columns.psf` with
///   an `index_map` that declares offsets and sizes per index. Produced by running the v1 fixture through
///   `SegmentV1V2ToV3FormatConverter` from Pinot 1.5.0; the legacy embedded-dictionary bytes are byte-identical
///   to the v1 fixture (the `SingleFileIndexDirectory` magic-marker prefix is added by the writer and stripped by
///   `getIndexFor` on read, so the bytes the format detector sees are the same as in v1).
///
/// **What the new code must do on segment load** to remain backward-compatible (both fixtures):
///
///   1. `SegmentPreProcessor.removeLegacyRawValueInvertedIndexes` (pre-pass before all index handlers) detects
///      the legacy 44-byte big-endian header and removes the index entry — for v1 it deletes the file, for v3 it
///      removes the `index_map` entry (the bytes inside `columns.psf` are no longer referenced).
///   2. `ForwardIndexHandler.ENABLE_DICTIONARY` op materializes a standalone dictionary on the column (driven by
///      the cluster's table config still requesting an inverted index, which now requires a dictionary).
///   3. `InvertedIndexHandler` builds a standard dict-id-based bitmap inverted index from the new dictionary.
///
/// **Verification:**
///
/// - **Black-box query checks** — COUNT(*), EQ, IN, NOT_EQ — would crash or report wildly wrong counts if the
///   modern `BitmapInvertedIndexReader` mis-interpreted the legacy header.
/// - **White-box on-disk checks** ([#assertSegmentMigratedOnDisk]) inspect the server's local segment
///   directory after load: assert that the column metadata flips to `hasDictionary=true`, that the dictionary
///   index is present, that the inverted index is no longer in the legacy embedded-dict format, and that the
///   forward index is preserved (raw forward stays).
public class LegacyRawValueInvertedIndexMigrationIntegrationTest extends BaseClusterIntegrationTest {
  private static final String CATEGORY_COLUMN = "category";
  /// Mirrors the deterministic values written by the fixture generator. 6-element cycle:
  /// alpha 3× per cycle, beta/gamma/delta 1× each.
  private static final String[] DISTINCT_VALUES = {"alpha", "beta", "gamma", "delta"};
  private static final int NUM_DOCS = 600;
  private static final int CYCLE_LENGTH = 6;
  private static final String SEGMENT_NAME = "legacyRawInverted_OFFLINE_0";

  private static final String V1_TABLE = "legacyRawInvertedV1";
  private static final String V3_TABLE = "legacyRawInvertedV3";
  private static final String V1_FIXTURE_RESOURCE = "legacy/legacyRawInverted_OFFLINE_0.tar.gz";
  private static final String V3_FIXTURE_RESOURCE = "legacy/legacyRawInverted_v3_OFFLINE_0.tar.gz";

  @Override
  protected long getCountStarResult() {
    return NUM_DOCS;
  }

  @BeforeClass
  public void setUp()
      throws Exception {
    TestUtils.ensureDirectoriesExistAndEmpty(_tempDir, _segmentDir, _tarDir);

    startZk();
    startController();
    startBroker();
    startServer();

    setUpFixtureTable(V1_TABLE, V1_FIXTURE_RESOURCE);
    setUpFixtureTable(V3_TABLE, V3_FIXTURE_RESOURCE);
  }

  /// Cluster-side schema and table config request `noDictionaryColumns` overlapping `invertedIndexColumns` on
  /// the same column — the legacy "raw forward + inverted" config that, in the old code, produced the
  /// embedded-dict format. The new code must auto-create the missing dictionary on segment load.
  private void setUpFixtureTable(String tableName, String fixtureResource)
      throws Exception {
    Schema schema = new Schema.SchemaBuilder()
        .setSchemaName(tableName)
        .addSingleValueDimension(CATEGORY_COLUMN, FieldSpec.DataType.STRING)
        .build();
    addSchema(schema);

    // FieldConfig requires an explicit `dictionary: {}` block per the new
    // `validateExplicitDictionaryForRawForwardIndex` rule: a column with `noDictionaryColumns +
    // invertedIndexColumns` overlap must opt in to the auto-created shared dictionary.
    ObjectNode indexes = JsonUtils.newObjectNode();
    indexes.set("dictionary", JsonUtils.newObjectNode());
    FieldConfig categoryFieldConfig = new FieldConfig.Builder(CATEGORY_COLUMN)
        .withEncodingType(FieldConfig.EncodingType.RAW)
        .withIndexes(indexes)
        .build();
    TableConfig tableConfig = new TableConfigBuilder(TableType.OFFLINE)
        .setTableName(tableName)
        .setInvertedIndexColumns(List.of(CATEGORY_COLUMN))
        .setFieldConfigList(List.of(categoryFieldConfig))
        .build();
    addTableConfig(tableConfig);

    File perTableTarDir = new File(_tarDir, tableName);
    FileUtils.forceMkdir(perTableTarDir);
    File stagedTar = new File(perTableTarDir, SEGMENT_NAME + ".tar.gz");
    try (InputStream legacyResource =
        getClass().getClassLoader().getResourceAsStream(fixtureResource)) {
      assertNotNull(legacyResource,
          "Legacy fixture resource not found on test classpath: " + fixtureResource);
      FileUtils.copyInputStreamToFile(legacyResource, stagedTar);
    }

    uploadSegments(tableName, perTableTarDir);
    waitForDocsLoaded(tableName, 60_000L);
  }

  private void waitForDocsLoaded(String tableName, long timeoutMs)
      throws Exception {
    TestUtils.waitForCondition(aVoid -> {
      try {
        return getCurrentCountStarResult(tableName) == NUM_DOCS;
      } catch (Exception e) {
        return null;
      }
    }, 100L, timeoutMs, "Failed to load all documents into table: " + tableName);
  }

  @AfterClass
  public void tearDown()
      throws Exception {
    dropOfflineTable(V1_TABLE);
    dropOfflineTable(V3_TABLE);
    stopServer();
    stopBroker();
    stopController();
    stopZk();
    FileUtils.deleteDirectory(_tempDir);
  }

  @DataProvider(name = "fixtures")
  public Object[][] fixtures() {
    return new Object[][] {
        {V1_TABLE, "v1"},
        {V3_TABLE, "v3"}
    };
  }

  /// COUNT(*) doesn't itself depend on the inverted index, but if the legacy file weren't dropped during
  /// preprocess the segment would either fail to load or report a corrupted doc count.
  @Test(dataProvider = "fixtures")
  public void testCountStarMatchesIngestedDocs(String tableName, String formatLabel)
      throws Exception {
    JsonNode result = postQuery("SELECT COUNT(*) FROM " + tableName);
    assertEquals(result.get("resultTable").get("rows").get(0).get(0).asLong(), NUM_DOCS,
        formatLabel + ": doc count must equal the ingested row count after migration");
  }

  /// Each EQ predicate would, in pre-migration state, hit the legacy embedded-dict reader. After migration the
  /// new dict-id-based `BitmapInvertedIndexReader` serves it. The two should produce the same results — verified
  /// by checking against the inline expected counts.
  @Test(dataProvider = "fixtures")
  public void testEqualityCountsAfterMigration(String tableName, String formatLabel)
      throws Exception {
    Map<String, Long> expected = expectedCountsByValue();
    for (Map.Entry<String, Long> e : expected.entrySet()) {
      String value = e.getKey();
      long expectedCount = e.getValue();
      JsonNode result = postQuery(
          "SELECT COUNT(*) FROM " + tableName + " WHERE " + CATEGORY_COLUMN + " = '" + value + "'");
      long actual = result.get("resultTable").get("rows").get(0).get(0).asLong();
      assertEquals(actual, expectedCount,
          formatLabel + ": EQ count mismatch for '" + value + "' — migration may have failed");
    }
  }

  @Test(dataProvider = "fixtures")
  public void testInPredicateAfterMigration(String tableName, String formatLabel)
      throws Exception {
    Map<String, Long> expected = expectedCountsByValue();
    long expectedAlphaBeta = expected.get(DISTINCT_VALUES[0]) + expected.get(DISTINCT_VALUES[1]);
    JsonNode result = postQuery("SELECT COUNT(*) FROM " + tableName + " WHERE " + CATEGORY_COLUMN
        + " IN ('" + DISTINCT_VALUES[0] + "', '" + DISTINCT_VALUES[1] + "')");
    long actual = result.get("resultTable").get("rows").get(0).get(0).asLong();
    assertEquals(actual, expectedAlphaBeta,
        formatLabel + ": IN-predicate count mismatch — migration may have failed");
  }

  @Test(dataProvider = "fixtures")
  public void testNotEqualPredicateAfterMigration(String tableName, String formatLabel)
      throws Exception {
    long expectedNotAlpha = NUM_DOCS - expectedCountsByValue().get(DISTINCT_VALUES[0]);
    JsonNode result = postQuery("SELECT COUNT(*) FROM " + tableName + " WHERE " + CATEGORY_COLUMN
        + " != '" + DISTINCT_VALUES[0] + "'");
    long actual = result.get("resultTable").get("rows").get(0).get(0).asLong();
    assertEquals(actual, expectedNotAlpha,
        formatLabel + ": NOT_EQ count mismatch — migration may have failed");
  }

  /// White-box check: open the server's local segment directory, parse `metadata.properties` + `index_map` (or
  /// equivalent v1 file layout), and assert that the migration mutated the on-disk state correctly:
  ///
  /// - `column.category.hasDictionary = true` — `ForwardIndexHandler.ENABLE_DICTIONARY` flipped this.
  /// - The dictionary index is now registered with the segment directory.
  /// - The inverted index is registered, and its bytes are NOT in the legacy embedded-dictionary format.
  /// - The forward index is still raw (we kept it; the shared dictionary is standalone).
  @Test(dataProvider = "fixtures")
  public void testSegmentMigratedOnDisk(String tableName, String formatLabel)
      throws Exception {
    File segmentDir = locateServerSegmentDir(tableName);
    assertTrue(segmentDir.isDirectory(),
        formatLabel + ": expected server-side segment dir at " + segmentDir);

    SegmentMetadataImpl segmentMetadata = new SegmentMetadataImpl(segmentDir);
    ColumnMetadata categoryMeta = segmentMetadata.getColumnMetadataFor(CATEGORY_COLUMN);
    assertNotNull(categoryMeta, formatLabel + ": missing column metadata for " + CATEGORY_COLUMN);
    assertTrue(categoryMeta.hasDictionary(),
        formatLabel + ": metadata must show hasDictionary=true after migration (was=false in fixture)");
    assertEquals(categoryMeta.getCardinality(), DISTINCT_VALUES.length,
        formatLabel + ": cardinality should match the fixture's distinct-value count");

    // Server normalizes all loaded segments to v3 (per the test cluster's segment.format.version=v3 setting),
    // so post-load we expect v3 regardless of fixture's source format.
    assertEquals(segmentMetadata.getVersion(), SegmentVersion.v3,
        formatLabel + ": server should normalize the loaded segment to v3");
    try (SegmentDirectory directory = new SegmentLocalFSDirectory(segmentDir, ReadMode.mmap);
        SegmentDirectory.Reader reader = directory.createReader()) {
      assertTrue(reader.hasIndexFor(CATEGORY_COLUMN, StandardIndexes.dictionary()),
          formatLabel + ": dictionary index must be present after migration");
      assertTrue(reader.hasIndexFor(CATEGORY_COLUMN, StandardIndexes.inverted()),
          formatLabel + ": inverted index must be present after migration");
      assertTrue(reader.hasIndexFor(CATEGORY_COLUMN, StandardIndexes.forward()),
          formatLabel + ": forward index must remain after migration (raw forward is preserved)");

      try (PinotDataBuffer invBuffer =
          reader.getIndexFor(CATEGORY_COLUMN, StandardIndexes.inverted())) {
        assertFalse(LegacyRawValueInvertedIndexCleanup.isLegacyRawValueInvertedIndexFormat(invBuffer, categoryMeta),
            formatLabel + ": rebuilt inverted index must NOT be in legacy embedded-dict format");
      }
    }
  }

  /// Resolve the on-disk segment directory under the in-process server's `INSTANCE_DATA_DIR`. Layout is
  /// `<dataDir>/<tableNameWithType>/<segmentName>` for offline tables.
  private File locateServerSegmentDir(String tableName) {
    String tableNameWithType = TableNameBuilder.OFFLINE.tableNameWithType(tableName);
    return new File(
        TEMP_SERVER_DIR + File.separator + "dataDir-0" + File.separator + tableNameWithType,
        SEGMENT_NAME);
  }

  /// Per-value expected multiplicity from the fixture's deterministic 6-element cycle:
  /// alpha appears 3× per cycle, beta/gamma/delta each 1×.
  private static Map<String, Long> expectedCountsByValue() {
    long cycles = NUM_DOCS / CYCLE_LENGTH;
    Map<String, Long> counts = new HashMap<>();
    counts.put(DISTINCT_VALUES[0], cycles * 3);
    counts.put(DISTINCT_VALUES[1], cycles);
    counts.put(DISTINCT_VALUES[2], cycles);
    counts.put(DISTINCT_VALUES[3], cycles);
    long total = counts.values().stream().mapToLong(Long::longValue).sum();
    assertEquals(total, NUM_DOCS, "Inline expected counts must sum to NUM_DOCS");
    return counts;
  }
}
