SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS generic_json_entity;
DROP TABLE IF EXISTS anomaly_function_index;
DROP TABLE IF EXISTS job_index;
DROP TABLE IF EXISTS task_index;
DROP TABLE IF EXISTS anomaly_feedback_index;
DROP TABLE IF EXISTS raw_anomaly_result_index;
DROP TABLE IF EXISTS merged_anomaly_result_index;
DROP TABLE IF EXISTS dataset_config_index;
DROP TABLE IF EXISTS metric_config_index;
DROP TABLE IF EXISTS override_config_index;
DROP TABLE IF EXISTS alert_config_index;
DROP TABLE IF EXISTS data_completeness_config_index;
DROP TABLE IF EXISTS event_index;
DROP TABLE IF EXISTS detection_status_index;
DROP TABLE IF EXISTS autotune_config_index;
DROP TABLE IF EXISTS classification_config_index;
DROP TABLE IF EXISTS entity_to_entity_mapping_index;
DROP TABLE IF EXISTS grouped_anomaly_results_index;
DROP TABLE IF EXISTS onboard_dataset_metric_index;
DROP TABLE IF EXISTS config_index;
DROP TABLE IF EXISTS application_index;
DROP TABLE IF EXISTS alert_snapshot_index;
DROP TABLE IF EXISTS rootcause_session_index;
DROP TABLE IF EXISTS session_index;
DROP TABLE IF EXISTS detection_config_index;
DROP TABLE IF EXISTS detection_alert_config_index;
DROP TABLE IF EXISTS evaluation_index;

SET FOREIGN_KEY_CHECKS = 1;
