/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.segment.local.segment.index.map;

import java.util.Set;
import javax.annotation.Nullable;
import org.apache.pinot.segment.spi.ColumnMetadata;
import org.apache.pinot.segment.spi.index.IndexType;
import org.apache.pinot.segment.spi.partition.PartitionFunction;
import org.apache.pinot.spi.data.DimensionFieldSpec;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.FieldSpec.DataType;


// TODO: THIS IS A HACK with all stats UNAVAILABLE. Revisit to fill the actual stats for the column.
@SuppressWarnings("rawtypes")
public class SimpleColumnMetadata implements ColumnMetadata {
  private final FieldSpec _fieldSpec;
  private final int _totalDocs;

  public SimpleColumnMetadata(FieldSpec fieldSpec, int totalDocs) {
    _fieldSpec = fieldSpec;
    _totalDocs = totalDocs;
  }

  public SimpleColumnMetadata(String columnName, DataType dataType, int totalDocs) {
    this(new DimensionFieldSpec(columnName, dataType, true), totalDocs);
  }

  @Override
  public FieldSpec getFieldSpec() {
    return _fieldSpec;
  }

  @Override
  public int getTotalDocs() {
    return _totalDocs;
  }

  @Override
  public int getCardinality() {
    return UNAVAILABLE;
  }

  @Override
  public boolean hasDictionary() {
    return false;
  }

  @Override
  public boolean isSorted() {
    return false;
  }

  @Nullable
  @Override
  public Comparable getMinValue() {
    return null;
  }

  @Nullable
  @Override
  public Comparable getMaxValue() {
    return null;
  }

  @Override
  public boolean isMinMaxValueInvalid() {
    return true;
  }

  @Override
  public int getLengthOfShortestElement() {
    return UNAVAILABLE;
  }

  @Override
  public int getLengthOfLongestElement() {
    return UNAVAILABLE;
  }

  @Override
  public boolean isAscii() {
    return false;
  }

  @Override
  public int getTotalNumberOfEntries() {
    return UNAVAILABLE;
  }

  @Override
  public int getMaxNumberOfMultiValues() {
    return UNAVAILABLE;
  }

  @Override
  public int getBitsPerElement() {
    return UNAVAILABLE;
  }

  @Nullable
  @Override
  public PartitionFunction getPartitionFunction() {
    return null;
  }

  @Nullable
  @Override
  public Set<Integer> getPartitions() {
    return null;
  }

  @Override
  public boolean isAutoGenerated() {
    return false;
  }

  @Override
  public int getNumIndexes() {
    return 0;
  }

  @Override
  public short getIndexType(int position) {
    throw new UnsupportedOperationException();
  }

  @Override
  public long getIndexSize(int position) {
    throw new UnsupportedOperationException();
  }

  @Override
  public long getIndexSizeFor(IndexType type) {
    return UNAVAILABLE;
  }
}
