#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Pinot Quickstart Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "contrib/**"
      - "docs/**"
      - "docker/**"
      - "kubernetes/**"
      - "licenses/**"
      - "licenses-binary/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "contrib/**"
      - "docs/**"
      - "docker/**"
      - "kubernetes/**"
      - "licenses/**"
      - "licenses-binary/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  quickstarts:
    if: github.repository == 'apache/pinot'
    runs-on: ubuntu-latest
    strategy:
      # Changed to false in order to improve coverage using unsafe buffers
      fail-fast: false
      matrix:
        java: [ 21 ]
        distribution: [ "temurin" ]
    name: Pinot Quickstart on JDK ${{ matrix.java }}-${{ matrix.distribution }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'
      # Step that does that actual cache save and restore
      - uses: actions/cache@v5
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 10
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Quickstart on JDK ${{ matrix.java }}
        timeout-minutes: 120
        run: |
          .github/workflows/scripts/.pinot_quickstart.sh
