/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.segment.local.recordtransformer;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import javax.annotation.Nullable;
import org.apache.pinot.common.utils.ThrottledLogger;
import org.apache.pinot.segment.local.utils.DataTypeTransformerUtils;
import org.apache.pinot.spi.config.table.TableConfig;
import org.apache.pinot.spi.config.table.ingestion.IngestionConfig;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.Schema;
import org.apache.pinot.spi.data.readers.GenericRow;
import org.apache.pinot.spi.recordtransformer.RecordTransformer;
import org.apache.pinot.spi.utils.PinotDataType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * The {@code DataTypeTransformer} class converts column values to follow the configured {@link PinotDataType}s. It has
 * two usages:
 * <ul>
 *   <li>Schema columns: constructed from the {@link Schema}, it should run after all the values have been generated by
 *   other transformers (such as {@link ExpressionTransformer}) so that all values follow the data types in
 *   {@link FieldSpec}.</li>
 *   <li>Source fields: constructed from an explicit column-to-{@link PinotDataType} map (see
 *   {@code IngestionConfig.sourceFieldConfigs}), it runs before other transformers (such as
 *   {@link ExpressionTransformer}) to fix the data types of the source fields they consume.</li>
 * </ul>
 */
public class DataTypeTransformer implements RecordTransformer {
  private static final Logger LOGGER = LoggerFactory.getLogger(DataTypeTransformer.class);

  private final Map<String, PinotDataType> _dataTypes;
  private final boolean _continueOnError;
  private final ThrottledLogger _throttledLogger;
  // UUID primary key columns for upsert/dedup tables; non-null and non-empty when applicable.
  // Non-canonical (uppercase) UUID strings in these columns will be rejected at ingest time because
  // Kafka partition routing is decided by the producer before Pinot normalises the value. Accepting
  // uppercase UUIDs as primary keys silently causes dedup failures in multi-partition realtime
  // upsert tables when the same logical UUID is routed to different partitions.
  @Nullable
  private final Set<String> _upsertUuidPrimaryKeyColumns;

  /// Creates a [DataTypeTransformer] that converts the (non-virtual) schema columns to the data types defined in the
  /// [Schema].
  public DataTypeTransformer(TableConfig tableConfig, Schema schema) {
    this(tableConfig, extractSchemaDataTypes(schema), schema);
  }

  /// Creates a [DataTypeTransformer] that converts the given columns to the provided [PinotDataType]s. This is useful
  /// for fixing the data types of source fields before other transformers (such as [ExpressionTransformer]) consume
  /// them.
  public DataTypeTransformer(TableConfig tableConfig, Map<String, PinotDataType> dataTypes) {
    this(tableConfig, dataTypes, null);
  }

  private DataTypeTransformer(TableConfig tableConfig, Map<String, PinotDataType> dataTypes, @Nullable Schema schema) {
    _dataTypes = dataTypes;
    IngestionConfig ingestionConfig = tableConfig.getIngestionConfig();
    _continueOnError = ingestionConfig != null && ingestionConfig.isContinueOnError();
    _throttledLogger = new ThrottledLogger(LOGGER, ingestionConfig);

    // Enforce canonical-form UUID PKs only when upsert/dedup is actually enabled — a present-but-disabled config
    // (e.g., UpsertConfig with Mode.NONE) must not reject otherwise-valid rows.
    if (schema != null && (tableConfig.isUpsertEnabled() || tableConfig.isDedupEnabled())) {
      List<String> primaryKeyColumns = schema.getPrimaryKeyColumns();
      if (primaryKeyColumns != null && !primaryKeyColumns.isEmpty()) {
        Set<String> uuidPkCols = new HashSet<>();
        for (String col : primaryKeyColumns) {
          FieldSpec spec = schema.getFieldSpecFor(col);
          if (spec != null && spec.getDataType() == FieldSpec.DataType.UUID) {
            uuidPkCols.add(col);
          }
        }
        _upsertUuidPrimaryKeyColumns = uuidPkCols.isEmpty() ? null : Set.copyOf(uuidPkCols);
      } else {
        _upsertUuidPrimaryKeyColumns = null;
      }
    } else {
      _upsertUuidPrimaryKeyColumns = null;
    }
  }

  private static Map<String, PinotDataType> extractSchemaDataTypes(Schema schema) {
    Map<String, PinotDataType> dataTypes = new HashMap<>();
    for (FieldSpec fieldSpec : schema.getAllFieldSpecs()) {
      if (!fieldSpec.isVirtualColumn()) {
        dataTypes.put(fieldSpec.getName(), PinotDataType.getPinotDataTypeForIngestion(fieldSpec));
      }
    }
    return dataTypes;
  }

  @Override
  public boolean isNoOp() {
    return _dataTypes.isEmpty();
  }

  @Override
  public Set<String> getInputColumns() {
    return _dataTypes.keySet();
  }

  @Override
  public void transform(GenericRow record) {
    for (Map.Entry<String, PinotDataType> entry : _dataTypes.entrySet()) {
      String column = entry.getKey();
      try {
        Object value = record.getValue(column);
        if (_upsertUuidPrimaryKeyColumns != null && _upsertUuidPrimaryKeyColumns.contains(column)
            && value instanceof CharSequence) {
          validateCanonicalUuidPrimaryKey(column, value.toString());
        }
        value = DataTypeTransformerUtils.transformValue(column, value, entry.getValue());
        record.putValue(column, value);
      } catch (Exception e) {
        if (!_continueOnError) {
          throw new RuntimeException("Caught exception while transforming data type for column: " + column, e);
        }
        _throttledLogger.warn("Caught exception while transforming data type for column: " + column, e);
        record.putValue(column, null);
        record.markIncomplete();
      }
    }
  }

  /**
   * Validates that a UUID primary key string value is in canonical lowercase RFC 4122 form.
   *
   * <p>UUID primary keys in upsert/dedup realtime tables must be canonical because Kafka partition routing
   * is determined by the raw string value that the producer sends. If the producer sends the same logical
   * UUID with different casing (e.g. uppercase vs lowercase), Kafka will hash the strings differently
   * and the messages may land on different partitions. Pinot then normalises them to the same bytes
   * inside each consuming segment, so within-segment dedup works, but cross-partition dedup never
   * fires - producing duplicate or stale rows silently.
   *
   * <p>By rejecting any non-canonical UUID here (before bytes conversion loses the original string),
   * we ensure that a producer-side inconsistency surfaces as an ingestion error rather than a silent
   * correctness failure. This covers not only casing but also the dash-less 32-hex form and
   * whitespace-padded values: {@code UuidUtils.toBytes(String)} (used by the downstream conversion)
   * accepts those and would normalise them to the same bytes as the canonical string, so they must be
   * rejected here too. Producers must canonicalise UUID primary keys to lowercase RFC 4122 form before
   * publishing to Kafka.
   */
  private static void validateCanonicalUuidPrimaryKey(String column, String uuidStr) {
    String canonical = null;
    try {
      canonical = UUID.fromString(uuidStr).toString();
    } catch (IllegalArgumentException e) {
      // Not parseable as a dashed RFC 4122 UUID (e.g. dash-less 32-hex or whitespace-padded). Reject below rather
      // than defer to DataTypeTransformerUtils.transformValue, whose UuidUtils.toBytes would accept it as a
      // non-canonical value and defeat the Kafka partition-routing guarantee.
    }
    if (!uuidStr.equals(canonical)) {
      throw new IllegalArgumentException(
          "Non-canonical UUID primary key value '" + uuidStr + "' in upsert/dedup column '" + column + "'. "
              + "Expected canonical lowercase RFC 4122 form"
              + (canonical != null ? ": '" + canonical + "'" : " (8-4-4-4-12 dashed lowercase)") + ". "
              + "UUID primary keys must be in canonical lowercase form to ensure consistent Kafka partition "
              + "routing. Non-canonical values cause silent dedup failures in multi-partition realtime tables.");
    }
  }
}
