/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.pinot.segment.local.recordtransformer;

import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import javax.annotation.Nullable;
import org.apache.pinot.common.utils.ThrottledLogger;
import org.apache.pinot.segment.local.utils.DataTypeTransformerUtils;
import org.apache.pinot.segment.spi.index.FieldIndexConfigs;
import org.apache.pinot.segment.spi.index.FieldIndexConfigsUtil;
import org.apache.pinot.segment.spi.index.StandardIndexes;
import org.apache.pinot.spi.config.table.TableConfig;
import org.apache.pinot.spi.config.table.ingestion.IngestionConfig;
import org.apache.pinot.spi.data.FieldSpec;
import org.apache.pinot.spi.data.Schema;
import org.apache.pinot.spi.data.readers.GenericRow;
import org.apache.pinot.spi.recordtransformer.RecordTransformer;
import org.apache.pinot.spi.utils.JsonUtils;
import org.apache.pinot.spi.utils.PinotDataType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/// The `DataTypeTransformer` class converts column values to follow the configured [PinotDataType]s. It has
/// two usages:
///
/// - Schema columns: constructed from the [Schema], it should run after all the values have been generated by
///   other transformers (such as [ExpressionTransformer]) so that all values follow the data types in
///   [FieldSpec].
/// - Source fields: constructed from an explicit column-to-[PinotDataType] map (see
///   `IngestionConfig.sourceFieldConfigs`), it runs before other transformers (such as
///   [ExpressionTransformer]) to fix the data types of the source fields they consume.
public class DataTypeTransformer implements RecordTransformer {
  private static final Logger LOGGER = LoggerFactory.getLogger(DataTypeTransformer.class);

  private final Map<String, PinotDataType> _dataTypes;
  /// JSON-typed columns that have a JSON index. For these the parsed value is cached on the row (before it is
  /// serialized to a string for the forward index) so the JSON index can flatten it directly instead of re-parsing.
  /// Computed once here so we only pay for the cache when a JSON index will actually consume the parsed value. Empty
  /// for the source-field usage, which runs before indexing.
  private final Set<String> _jsonCacheColumns;
  private final boolean _continueOnError;
  private final ThrottledLogger _throttledLogger;
  // UUID primary key columns for upsert/dedup tables; non-null and non-empty when applicable.
  // Non-canonical (uppercase) UUID strings in these columns will be rejected at ingest time because
  // Kafka partition routing is decided by the producer before Pinot normalises the value. Accepting
  // uppercase UUIDs as primary keys silently causes dedup failures in multi-partition realtime
  // upsert tables when the same logical UUID is routed to different partitions.
  @Nullable
  private final Set<String> _upsertUuidPrimaryKeyColumns;

  /// Creates a [DataTypeTransformer] that converts the (non-virtual) schema columns to the data types defined in the
  /// [Schema].
  public DataTypeTransformer(TableConfig tableConfig, Schema schema) {
    this(tableConfig, extractSchemaDataTypes(schema), schema, computeJsonCacheColumns(tableConfig, schema));
  }

  /// Creates a [DataTypeTransformer] that converts the given columns to the provided [PinotDataType]s. This is useful
  /// for fixing the data types of source fields before other transformers (such as [ExpressionTransformer]) consume
  /// them.
  public DataTypeTransformer(TableConfig tableConfig, Map<String, PinotDataType> dataTypes) {
    this(tableConfig, dataTypes, null, Set.of());
  }

  private DataTypeTransformer(TableConfig tableConfig, Map<String, PinotDataType> dataTypes,
      @Nullable Schema schema, Set<String> jsonCacheColumns) {
    _dataTypes = dataTypes;
    _jsonCacheColumns = jsonCacheColumns;
    IngestionConfig ingestionConfig = tableConfig.getIngestionConfig();
    _continueOnError = ingestionConfig != null && ingestionConfig.isContinueOnError();
    _throttledLogger = new ThrottledLogger(LOGGER, ingestionConfig);

    // Enforce canonical-form UUID PKs only when upsert/dedup is actually enabled — a present-but-disabled config
    // (e.g., UpsertConfig with Mode.NONE) must not reject otherwise-valid rows.
    if (schema != null && (tableConfig.isUpsertEnabled() || tableConfig.isDedupEnabled())) {
      List<String> primaryKeyColumns = schema.getPrimaryKeyColumns();
      if (primaryKeyColumns != null && !primaryKeyColumns.isEmpty()) {
        Set<String> uuidPkCols = new HashSet<>();
        for (String col : primaryKeyColumns) {
          FieldSpec spec = schema.getFieldSpecFor(col);
          if (spec != null && spec.getDataType() == FieldSpec.DataType.UUID) {
            uuidPkCols.add(col);
          }
        }
        _upsertUuidPrimaryKeyColumns = uuidPkCols.isEmpty() ? null : Set.copyOf(uuidPkCols);
      } else {
        _upsertUuidPrimaryKeyColumns = null;
      }
    } else {
      _upsertUuidPrimaryKeyColumns = null;
    }
  }

  private static Map<String, PinotDataType> extractSchemaDataTypes(Schema schema) {
    Map<String, PinotDataType> dataTypes = new HashMap<>();
    for (FieldSpec fieldSpec : schema.getAllFieldSpecs()) {
      if (!fieldSpec.isVirtualColumn()) {
        dataTypes.put(fieldSpec.getName(), PinotDataType.getPinotDataTypeForIngestion(fieldSpec));
      }
    }
    return dataTypes;
  }

  @Override
  public boolean isNoOp() {
    return _dataTypes.isEmpty();
  }

  /// Returns the JSON-typed columns that have an (enabled) JSON index, i.e. the columns worth caching the parsed value
  /// for. If the index configs cannot be resolved, returns an empty set and the optimization is disabled (the JSON
  /// index simply re-parses the serialized string, as before).
  private static Set<String> computeJsonCacheColumns(TableConfig tableConfig, Schema schema) {
    Set<String> columns = new HashSet<>();
    try {
      Map<String, FieldIndexConfigs> indexConfigsByColumn =
          FieldIndexConfigsUtil.createIndexConfigsByColName(tableConfig, schema);
      for (FieldSpec fieldSpec : schema.getAllFieldSpecs()) {
        if (!fieldSpec.isVirtualColumn() && fieldSpec.getDataType() == FieldSpec.DataType.JSON) {
          FieldIndexConfigs configs = indexConfigsByColumn.get(fieldSpec.getName());
          if (configs != null && configs.getConfig(StandardIndexes.json()).isEnabled()) {
            columns.add(fieldSpec.getName());
          }
        }
      }
    } catch (Exception e) {
      LOGGER.warn("Failed to compute JSON parse-once cache columns; disabling the optimization", e);
      return Set.of();
    }
    return columns;
  }

  @Override
  public Set<String> getInputColumns() {
    return _dataTypes.keySet();
  }

  @Override
  public void transform(GenericRow record) {
    for (Map.Entry<String, PinotDataType> entry : _dataTypes.entrySet()) {
      String column = entry.getKey();
      try {
        Object value = record.getValue(column);
        if (_upsertUuidPrimaryKeyColumns != null && _upsertUuidPrimaryKeyColumns.contains(column)
            && value instanceof CharSequence) {
          validateCanonicalUuidPrimaryKey(column, value.toString());
        }
        // For a JSON column with a JSON index, cache the parsed value so the index flattens it directly instead of
        // re-parsing the string the value is serialized into for the forward index. The parsed value is cached AFTER
        // the forward value is written (below), because putValue invalidates the parsed-JSON cache: a later transformer
        // that rewrites the value (e.g. sanitization trimming an over-length JSON string) must not leave a stale node.
        Object parsedToCache = null;
        if (value != null && !_jsonCacheColumns.isEmpty() && _jsonCacheColumns.contains(column)) {
          if (value instanceof Map || value instanceof List || value instanceof JsonNode) {
            // Already-parsed JSON: serialize it for the forward index (below) and cache the parsed value for the index.
            parsedToCache = value;
            value = DataTypeTransformerUtils.transformValue(column, value, entry.getValue());
          } else if (value instanceof String) {
            // The column value is JSON text. The JSON conversion parses it (preserving BigDecimal) and re-serializes it
            // to the canonical string for the forward index; the JSON index then re-parses that string. Parse it once
            // here instead: reuse the node's canonical string for the forward index and cache the node for the index.
            JsonNode parsed = tryParseJson((String) value);
            if (parsed != null) {
              parsedToCache = parsed;
              // parsed.toString() equals PinotDataType.JSON.convert(value) for well-formed JSON (byte-identical).
              value = parsed.toString();
            } else {
              // Not well-formed JSON: the normal conversion wraps it as a JSON string.
              value = DataTypeTransformerUtils.transformValue(column, value, entry.getValue());
            }
          } else {
            value = DataTypeTransformerUtils.transformValue(column, value, entry.getValue());
          }
        } else {
          value = DataTypeTransformerUtils.transformValue(column, value, entry.getValue());
        }
        record.putValue(column, value);
        if (parsedToCache != null) {
          record.putParsedJsonValue(column, parsedToCache);
        }
      } catch (Exception e) {
        if (!_continueOnError) {
          throw new RuntimeException("Caught exception while transforming data type for column: " + column, e);
        }
        _throttledLogger.warn("Caught exception while transforming data type for column: " + column, e);
        record.putValue(column, null);
        record.markIncomplete();
      }
    }
  }

  /// Validates that a UUID primary key string value is in canonical lowercase RFC 4122 form.
  ///
  /// UUID primary keys in upsert/dedup realtime tables must be canonical because Kafka partition routing
  /// is determined by the raw string value that the producer sends. If the producer sends the same logical
  /// UUID with different casing (e.g. uppercase vs lowercase), Kafka will hash the strings differently
  /// and the messages may land on different partitions. Pinot then normalises them to the same bytes
  /// inside each consuming segment, so within-segment dedup works, but cross-partition dedup never
  /// fires - producing duplicate or stale rows silently.
  ///
  /// By rejecting any non-canonical UUID here (before bytes conversion loses the original string),
  /// we ensure that a producer-side inconsistency surfaces as an ingestion error rather than a silent
  /// correctness failure. This covers not only casing but also the dash-less 32-hex form and
  /// whitespace-padded values: `UuidUtils.toBytes(String)` (used by the downstream conversion)
  /// accepts those and would normalise them to the same bytes as the canonical string, so they must be
  /// rejected here too. Producers must canonicalise UUID primary keys to lowercase RFC 4122 form before
  /// publishing to Kafka.
  private static void validateCanonicalUuidPrimaryKey(String column, String uuidStr) {
    String canonical = null;
    try {
      canonical = UUID.fromString(uuidStr).toString();
    } catch (IllegalArgumentException e) {
      // Not parseable as a dashed RFC 4122 UUID (e.g. dash-less 32-hex or whitespace-padded). Reject below rather
      // than defer to DataTypeTransformerUtils.transformValue, whose UuidUtils.toBytes would accept it as a
      // non-canonical value and defeat the Kafka partition-routing guarantee.
    }
    if (!uuidStr.equals(canonical)) {
      throw new IllegalArgumentException(
          "Non-canonical UUID primary key value '" + uuidStr + "' in upsert/dedup column '" + column + "'. "
              + "Expected canonical lowercase RFC 4122 form"
              + (canonical != null ? ": '" + canonical + "'" : " (8-4-4-4-12 dashed lowercase)") + ". "
              + "UUID primary keys must be in canonical lowercase form to ensure consistent Kafka partition "
              + "routing. Non-canonical values cause silent dedup failures in multi-partition realtime tables.");
    }
  }

  /// Parses JSON text the way [PinotDataType]'s JSON conversion does (preserving `BigDecimal` floats so the
  /// canonical string is byte-identical), or returns `null` if the text is not well-formed JSON so the caller
  /// falls back to the normal conversion (which wraps a non-JSON string as a JSON string).
  @Nullable
  private static JsonNode tryParseJson(String jsonText) {
    try {
      return JsonUtils.stringToJsonNodeWithBigDecimal(jsonText);
    } catch (IOException e) {
      // Not well-formed JSON; let the caller fall back to the normal conversion (which wraps it as a JSON string).
      return null;
    }
  }
}
